### ISSUE TITLE
Link a Research Plan from a reaction

### ISSUE THREAD

**Issue by BenjaminGolub** [ComPlat/chemotion_ELN#1001]
I am an ELNer and ELN admin

# Description
It would be nice to have the possibility to link a research plan from a reaction. This would be useful for users, that use the research plan as an overview when screening multiple reactions conditions and so on. 

I think the simplest thing would be to have a new field called "research plan" or something link this. Or a new segment (or generic segment) called "links" or something. So, in general, a better linking system would be very useful.

**Comment by PiTrem** [comment]
released  in [v1.8.1](https://github.com/ComPlat/chemotion_ELN/blob/main/CHANGELOG.md#v181)
