### ISSUE TITLE
Strange sample sorting

### ISSUE THREAD

**Issue by BenjaminGolub** [ComPlat/chemotion_ELN#1006]
- [x] I am an ELNer
- I am a developer
- [x] I am a system/ELN admin

# Expected Behavior

In one collection, I would expect, that all molecules of one kind are found in one place. Like here:
All benzene samples are listed below the structure. And this should be true for all my molecules/samples in my collection.
![grafik](https://user-images.githubusercontent.com/107389350/199222543-9308d680-d76a-4a22-8cc0-c903a34bb838.png)

# Current Behavior

I have a collection, where I do the same reaction over and over again. At some point, the first page of the sample overview is full, and a new one is starting, and then it looks like this:
![grafik](https://user-images.githubusercontent.com/107389350/199222964-dcdea3f8-6b37-47ef-bb3f-4ea0dbc29833.png)
![grafik](https://user-images.githubusercontent.com/107389350/199223018-d7c3e749-5c6a-4a77-aae0-4340f87302bf.png)

I would expect that all e.g. benzene entries are listed with one benzene and not scattered over different pages. (If one page is not enough, another one is needed, that is clear).

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create a collection with e.g. 3 molecules
2. start making reactions with these 3 molecules until the first page of the sample overview is full
3. check the sorting of the sample overview

I attached a slightly longer video to show the process and problem in more detail, in case I couldn't describe it very well. This is just an example how the problem can be reproduced. The problem was found in a used ELN, and leads to confusion. Is this a bug, or is there a reason why it is sorting the samples like this?

https://user-images.githubusercontent.com/107389350/199232508-1326f998-1e9c-4658-b578-63fd0ed6c9da.mp4
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: Windows 10
 - Chrome Browser 
 - ELN version 1.3.1

**Comment by MTenb** [comment]
I can confirm. We observe similar behavior on our instance in Mainz. Chemotion sorts absolutely identical samples into two or more containers on multiple pages instead of having one large container with all identical samples.

**Comment by TasnimMehzabin** [comment]
@BenjaminGolub In the samples' list, we have an option to group the list by either sample or molecule. When you order the list by molecules, it behaves as you are expecting. Could you kindly check the attached video and let us know if it will resolve the issue for you when you group by molecules? Keeping the number of items each page at 10, I basically created the same collection as in your video. 

When the list is grouped by samples, then it particularly shows as many samples as allowed by the input field in the bottom right corner and moves the other samples on the next page. However when you group by molecules, then the samples with same molecular structure will all appear grouped together as shows in the video.

https://github.com/ComPlat/chemotion_ELN/assets/8912580/63645a42-22e5-4840-ac61-b128f12e189c

**Comment by BenjaminGolub** [comment]
I agree, it should work like this, but unfortunately, it is not the case (as you can see here in the video). We will update to Chemotion ELN v1.7.2 on Wednesday, maybe this will solve the problem. I will let you know. 

https://github.com/ComPlat/chemotion_ELN/assets/107389350/597ab38d-6c58-440c-8e65-ec7d4301c80f

**Comment by BenjaminGolub** [comment]
With the update to Chemotion ELN v1.7.2 the problem was solved.

**Comment by TasnimMehzabin** [comment]
Thank you for the confirmation.

With the grouping feature, as the issue gets resolved, I am closing the issue.
