### ISSUE TITLE
URL Paths are not updating when re-log in as a different user

### ISSUE THREAD

**Issue by mehmood86** [ComPlat/chemotion_ELN#1011]
https://user-images.githubusercontent.com/5851022/199764056-c55e2a10-d2e0-4ced-b804-00edb2a774aa.mp4

- I am an developer

# Description
When sign in as a user and click on any sample, the url changes in the address bar, this is normal behavior BUT when you sign out and sign in again as different user, this url path should be cleared from the memory.

1. what enhancement you suggest
The url should point to the the page it showing at the moment.

2. why you think it is needed (You might provide a use case here)
Every page in the application must reflect the url in the address bar corresponding to the content it shows. Currently, it shows the url of collections but the content for dashboard is displayed.

# Video
Please see the attached video for a better understanding of the issue I am refering about.

**Comment by adambasha0** [comment]
Do we need to check this behaviour in production mode as well, for clarity?

**Comment by mehmood86** [comment]
Yes, If you could test it on production mode, it will be more clear. 

FYI: I tested it on on docker based production instance ()via cli-installation method) and dockerized development instance which is running on development branch. (not development-5 branch).

**Comment by jhmegorei** [comment]
@mehmood86 You are aware that the development branch is over a year old and thus completely irrelevant?

Only development-5 matters as a base for future development

@PiTrem can you delete the old development branch to prevent future confusion?

**Comment by TasnimMehzabin** [comment]
The issue is currently obsolete and hence might be closed.


https://github.com/ComPlat/chemotion_ELN/assets/8912580/660acbeb-9896-40d7-b556-2de305f8caf4
