### ISSUE TITLE
Reaction Name is overwritten when choosing a role

### ISSUE THREAD

**Issue by martin-held-hereon** [ComPlat/chemotion_ELN#1012]
- I am an ELNer
- I am a system/ELN admin

# Expected Behavior
When filling in the name field of a reaction and then choosing a role (single, GP, part of GP), the name should remain, because it creates clarity in the list of reactions. 

# Current Behavior
When filling in the name field of a reaction and then choosing a role (single, GP, part of GP), the name gets overwritten with the role and a consecutive number. 
--> see Video below

## Context
- Chemotion V 1.2
Maybe this is not a bug, but intended. However, I am sure that some users will be frustrated.

**Comment by adambasha0** [comment]
Hi Martin, 

Can you provide a video for clarity?

Thanks,
Adam

**Comment by martin-held-hereon** [comment]
here is a video:
https://user-images.githubusercontent.com/91550882/200280479-3ce2b48a-0781-4fb9-8489-35fc0e68591c.mp4

**Comment by adambasha0** [comment]
I think that was made on purpose. I will refer it in the weekly meeting for discussion.

**Comment by JanCBrammer** [comment]
@PiTrem, can we close this? Seems resolved.
