### ISSUE TITLE
Error message when entering masses in reactions with decoupled products

### ISSUE THREAD

**Issue by martin-held-hereon** [ComPlat/chemotion_ELN#1013]
- I am an ELNer
- I am a system/ELN admin

# Expected Behavior
No error messages when documenting reactions with decoupled products.

# Current Behavior + Steps to Reproduce
Probably related to issue #1014. I am entering masses for reactions with decoupled products, e.g. a polymerisation, where the Mw of the educt (styrene) is defined and the Mw of the product (polystyrene) isn't, hence the product is marked as "decoupled". Only BuLi is involved as a catalyst. When entering realistic masses (e.g. 1mg styrene --> 0.5mg polystyrene), an error message pops up, as if I had entered unrealistic masses (e.g. 1mg styrene --> 10mg polystyrene). 

# Failure Information 
This is reproducible whenever a product is "decoupled". Please turn it off as it confuses the users! Saving the reaction is possible and the error message disappears thereafter.

## Context
 - OS: Win 10
  - Firefox Browser
 - ELN V1.2

## Failure Logs / Screenshots
![Chemotion_mass_bug1](https://user-images.githubusercontent.com/91550882/200284652-b99f5031-947b-411e-9a20-e5d4cd92b5cc.png)

**Comment by martin-held-hereon** [comment]
![Chemotion_mass_bug1](https://user-images.githubusercontent.com/91550882/200284564-7c23916a-6487-4e8c-9b44-4bf3c90722eb.png)

**Comment by adambasha0** [comment]
fixed with PR #1531
