### ISSUE TITLE
Yield percentage is 100% for reactions with decoupled products

### ISSUE THREAD

**Issue by martin-held-hereon** [ComPlat/chemotion_ELN#1014]
- I am an ELNer
- I am a system/ELN admin

# Expected Behavior
When saving a reaction with decoupled products, no yield should be calculated or shown in the reaction scheme, because the product's molecular mass is not defined.

# Current Behavior
Probably related to issue #1013. When creating a reaction with a decoupled product, the yield is 100% after saving, independent of the entered masses.  This will be midleading and confusing for the users.

## Context
 - OS: Win 10
 - Firefox Browser
 - ELN V1.2

## Failure Logs / Screenshots
![Chemotion_yield_bug1](https://user-images.githubusercontent.com/91550882/200286628-695ff684-a006-4c0c-bc6c-0d42015c6aea.png)

**Comment by nicolejung** [comment]
The user is right: for decoupled samples, we have the option to enter the mass. If this is given (for starting material/reference compound and product - both needed), then the calculation should be possible

**Comment by adambasha0** [comment]
Hi @nicolejung, how do you want to disable the yield option in this case? - one option is to hide the yield field (not sure if it is a good idea), and another option is to make the yield field equal to another thing other than 100%?!

**Comment by adambasha0** [comment]
fixed with PR #1531
