### ISSUE TITLE
Units for generic objects - add MHz for frequency

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#1027]
1 MHz = 1000000 Hz

**Comment by cllde8** [comment]
Dear @NRayya,

The MHz for frequency has been added. You can find the full list at this [link](https://github.com/LabIMotion/Labimotion/wiki/Supported-Units-for-System-Defined-Field).

If you have any questions or suggestions, please create an issue or start a discussion at https://github.com/LabIMotion/labimotion.

Thank you.

Best regards,
Claire
