### ISSUE TITLE
Report / Supporting Info - Space between yield value and sign

### ISSUE THREAD

**Issue by SimoneGraessle** [ComPlat/chemotion_ELN#1029]
The space in the yield between the number and the % must be deleted. This error is still present when you generating a Supporting Info in the Repo.

**Comment by FabianMauz** [comment]
In ELN Version 1.4.1 there is no space between the value and the percent sign

**Comment by endevor-music** [comment]
In ELN v1.5, there is no space between the value and % sign when generating a report.

Report - [2023-03-21H11M18S49.docx](https://github.com/ComPlat/chemotion_ELN/files/11027200/2023-03-21H11M18S49.docx)

![Screenshot 2023-03-21 112523](https://user-images.githubusercontent.com/67055123/226579286-dd4bba0c-3f1b-4905-86a6-4028579cbe67.png)
![Screenshot 2023-03-21 112537](https://user-images.githubusercontent.com/67055123/226579292-1b7c7885-11a5-4736-af15-bd681adbeb6c.png)

**Comment by SimoneGraessle** [comment]
Hi, 

I can not see the yield in the reaction table. So there is a new bug. 
[Supporting_Information_2023-03-22H15M59S54.docx](https://github.com/ComPlat/chemotion_ELN/files/11041574/Supporting_Information_2023-03-22H15M59S54.docx)

**Comment by PiTrem** [comment]
I had a quick check and I think the discussed issues have been resolved for a while now on both systems.
