### ISSUE TITLE
Shared function with read label

### ISSUE THREAD

**Issue by SimoneGraessle** [ComPlat/chemotion_ELN#1030]
If you shared a reaction in the ELN and only specified Read as the permission label, then the other person cannot see the reaction. You only see stars.

**Comment by SimoneGraessle** [comment]
Hi Adam,

here is a picture what Helena can see:
***@***.***



And here is a picture what a choose for sharing:
***@***.***

Best wishes,
Simone




Von: Adam Basha ***@***.***>
Gesendet: Donnerstag, 10. November 2022 10:35
An: ComPlat/chemotion_ELN ***@***.***>
Cc: Gräßle, Simone (IBCS) ***@***.***>; Author ***@***.***>
Betreff: Re: [ComPlat/chemotion_ELN] Shared function with read label (Issue #1030)


Hi Simone, can you provide a video for clarity?
Thanks,
Adam

**Comment by jhmegorei** [comment]
In a call with Nicole, we were not able to reproduce this error.
The reporters were asked to check again if the issue persists and if so, to create some screenshots to document the issue properly. Then a new issue should be opened with the screenshots and if possible, information about which ELN release is deployed on the machine in question.
