### ISSUE TITLE
Performance problems due to frequent sizeColumnsToFit() calls

### ISSUE THREAD

**Issue by jliermann** [ComPlat/chemotion_ELN#1052]
- I am a system/ELN admin

# Expected Behavior

# Current Behavior

Text input in reaction description lags in Chemotion 1.3.1

# Failure Information 

For some reactions, every keystroke in the reaction decription gives this console warning:
`AG Grid: tried to call sizeColumnsToFit() but the grid is coming back with zero width, maybe the grid is not visible yet on the screen? 6 react_devtools_backend.js:4026:25`

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. import the attached demo collection
2. open reaction JCL-R3 oder JCL-R4
3. open the browser console
4. start typing in "Description"

## Context

Tested on Firefox 107.0 32 bit (Windows 10) on our Chemotion 1.3.1 instance as well as on https://demo.chemotion.ibcs.kit.edu/home

## Failure Logs / Screenshots

Demo dataset for reproducing:
[9712543c-3a27-49e7-9a80-442d517fb154.zip](https://github.com/ComPlat/chemotion_ELN/files/10084080/9712543c-3a27-49e7-9a80-442d517fb154.zip)

**Comment by JanCBrammer** [comment]
Useful links (WIP):
* https://stackoverflow.com/questions/54038024/warning-grid-zero-width-when-using-ag-grids-sizecolumnstofit-on-two-separat
