### ISSUE TITLE
Avoiding Mistakes and data loss when copying (Surmof) reactions

### ISSUE THREAD

**Issue by Alexwelle1** [ComPlat/chemotion_ELN#1064]
- I am an ELNer

# Description
A colleague of mine noticed the following unexpected behavior on our Chemotion ELN at IFG/KIT:
If attempting to copy a (Surmof) reaction, instantly a new reaction (new running number) is created. OK.
If he doesn't save this new entry immediately but first changes reaction parameters or deletes attachments and adds new ones ALL THESE CHANGES which should affect the copy only also affect the original reaction. In other words entries for the original reaction could be lost! That's dangerous and caused confusion.

So, it's imperative to SAFE the copied reaction first and then make all necessary changes. If done so the original reaction is not affected and no data/attachments get lost.
This workaround fixes the issue, but I wonder if that mistake can't be avoided by changed code.
Have a good day,
Alex

**Comment by phuang26** [comment]
It has been fixed in LabIMotion 1.3.0, which is included in ELN version 1.9.2 and later. Therefore, if you have ELN version 1.9.2 or newer, the issue should be resolved.

**Comment by phuang26** [comment]
It has been fixed in LabIMotion 1.3.0, which is included in ELN version 1.9.2 and later. Therefore, if you have ELN version 1.9.2 or newer, the issue should be resolved.
