### ISSUE TITLE
theoretical mass not shown

### ISSUE THREAD

**Issue by SimoneGraessle** [ComPlat/chemotion_ELN#1076]
- I am an ELNer

The maximum theoretical mass is no longer displayed for the product in the reaction table. It just says NaN there.

![image](https://user-images.githubusercontent.com/114132791/206377149-89392b5e-68f0-442f-a651-99900c89b3af.png)

**Comment by FabianMauz** [comment]
Can confirm it


![Image](https://user-images.githubusercontent.com/23172219/217856906-5a41172e-86f9-44e7-b543-3a3103dbfd0c.png)

**Comment by nicolejung** [comment]
BTW: I think the max amount should be visible as mouse over for the field "amount" while the molecular weight should be available as mouse over for the label of the sample (in addition to the labels given there)
