### ISSUE TITLE
Dropdown menues in reaction scheme and analyses tab bugged

### ISSUE THREAD

**Issue by MTenb** [ComPlat/chemotion_ELN#1078]
- I am an ELNer

# Expected Behavior

Normally, you can pick the reaction or analysis ontology via dropdown menu when editing a reaction.

# Current Behavior

Sometimes (not everytime though) the dropdown menu is not displayed correctly and you can't choose the ontology for example. Happend frequently when adding new analyses to a reaction. Usually occurs on all dropdown field in the current tab. Refreshing the page leads to normal behavior, but when editing another reaction afterwards the same bug appears.

# Failure Information 

see current behavior

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. open random reaction sfrom random collection
2. go to analyses tab
3. click add analysis
4. try to click on the dropdown fields

## Context

 - OS: Win 10
 - Chrome Browser 
 - ELN version 1.4.1

## Failure Logs / Screenshots

Include any relevant log snippets or files here.
![Chemotion dropdown bug_rxn modal](https://user-images.githubusercontent.com/100708486/207066674-43ff29f0-c390-4187-bd08-d353bfa6e565.PNG)
![Chemotion dropdown bug_nmr ontology](https://user-images.githubusercontent.com/100708486/207066676-fb3c29a0-f423-4c5e-946b-126f9836df74.PNG)

**Comment by PiTrem** [comment]
should be solved with https://github.com/ptrxyz/chemotion/commit/ba4b4620ab2aaa6be32df78189c29970335b1989

**Comment by harivyasi** [comment]
The dockerized version of the ELN is available [here](https://hub.docker.com/r/ptrxyz/chemotion/tags),

**Comment by MTenb** [comment]
The issue was solved with the mentioned update.
Thank you!
