### ISSUE TITLE
PubChem link / Query from PubChem entries / name generation for samples buggy

### ISSUE THREAD

**Issue by MTenb** [ComPlat/chemotion_ELN#1079]
- I am an ELNer

# Expected Behavior

For known compounds with an existing PubChem entry, a link to this entry is embadded and names are generated when creating a new sample.

# Current Behavior

For some compounds that definitely have a PubChem entry the PubChem logo stays gray and no link in embadded. Furthermore, no names are generated for the sample.
For some other examples it works just as expected. 
There might as well be a connection to issues #836 and #846.

## Steps to Reproduce

1. add new samples, fast-create via CAS or SMILES 
2. for some compounds link to PubChem works for others not

## Context

 - OS: Win 10
 - Chrome Browser 
 - ELN version 1.4.1

## Failure Logs / Screenshots

I added two examples, both have a PubChem entry, both created via fast-create with CAS number: 
Example 1: https://pubchem.ncbi.nlm.nih.gov/compound/69676, works fine, names generated, link works
![PubChem1](https://user-images.githubusercontent.com/100708486/207073660-135ee4ca-b667-448b-a798-e46e220c1b81.png)
![PubChem2](https://user-images.githubusercontent.com/100708486/207073650-732511e3-c2ef-4eb9-94da-81a37f29c3b8.png)

Example 2: https://pubchem.ncbi.nlm.nih.gov/compound/604716, the descriped behavior occurs, no names, no link 
![PubChem3](https://user-images.githubusercontent.com/100708486/207073654-1e6b07f3-d1f4-4895-89f9-c04db0969d16.png)
![PubChem4](https://user-images.githubusercontent.com/100708486/207073657-f7374a60-c419-4c37-8914-56506887bf39.png)

**Comment by FabianMauz** [comment]
Hi @MTenb 

I tried to reproduce the issue with the current latest version (1.8.0) but could not reproduce your problems.
First i created a sample by the fast creation by CAS number with your second example
![image](https://github.com/ComPlat/chemotion_ELN/assets/23172219/0c1599bb-8b05-4315-95a5-dadda195f7e4)

After creation everything looks fine for me
![image](https://github.com/ComPlat/chemotion_ELN/assets/23172219/8a364f2f-3cd1-4c85-8244-9947d8e1fb57)

**Comment by FabianMauz** [comment]
Fast Creation via SMILES is also working, it took only 1 second

**Comment by FabianMauz** [comment]
It would be great if you could test the functionality again on the latest version. If the problem still exists it would be very helpful if  you could add a snapshot of the console output of the browser as well as a snapshot of the network connection. 
If you need help with this I am very happy to help you.

**Comment by MTenb** [comment]
Hi @FabianMauz,

Thanks for your reply. Its been a while since I reported that bug.
We are currently on version 1.7.2 and the issue about the fast creation got resolved with one of the last updates. Loading times for both, creation via CAS and SMILES, are fine now.
I just retried both exact examples I gave in the report. As I said the fast creation works fine now but the link to the pubchem entry is still missing in the case of the Cycloheptanone (https://pubchem.ncbi.nlm.nih.gov/compound/604716). To be clear here: The Icon is there, but its grey because Chemotion does not have the link to the pubchem entry eventhough this compound has a pubchem entry. So the questions is why Chemotion does not find the pubchem entry for this compound.
Another thing I just noticed which is not recessary connected or even know already: When I just created this sample via fast create no thumbnail for the structure was generated. I had to click to edit the structure and save for it to be loaded and displayed.

**Comment by FabianMauz** [comment]
Hi @MTenb 

Thank you very much for your response. 
I tried again with your examples to reproduce the problem and could not reproduce it on the official testserver nor in my local instance. 

However, I have the assumption that due to the incorrect pubchem call in the past the data entry of the pubchem information in your molecule Cycloheptanone is corrupted and this now prevents a new query at pubchem.
I could reproduce this case locally and come to the same result as you (link on icon not clickable).
We will introduce a routine/feature to re-request pubchem data for a molecule and correct it if necessary.

**Comment by FabianMauz** [comment]
For your other note, I have a question: are you running the Ketcher service locally and if so, what version.

On my local development instance the same behaviour occurs, but this is due to a missing Ketcher Service instance. On the official test server I could not observe such behaviour.

**Comment by MTenb** [comment]
Hi @FabianMauz,

That sounds like good solution to me.
Regarding Ketcher: Im actually not sure, can I look that up anywhere? Otherwise I'd have to ask our admin team about that.
