### ISSUE TITLE
DragNDrop Breaks UI

### ISSUE THREAD

**Issue by mehmood86** [ComPlat/chemotion_ELN#1105]
- I am an ELNer
- I am a developer
- I am a system/ELN admin

# Expected Behavior

The UI should not break when draging items in the collection managment window.

# Current Behavior

The UI simply breaks when a collection dragged to parent element?

# Failure Information 

For reference, a video is also attached for clarification.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step1: sigin as a user and create any collection item in collection management window.
2. step 2: drag this item and move up to 'My collection' tab. 
3. you will get the error

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - Chrome Browser 
 - Firefox Browser
 - ELN version, or branch, or commit

https://user-images.githubusercontent.com/5851022/215501481-707b8621-e52d-4452-bfa4-6e5da7eab12d.mp4

## Failure Logs / Screenshots

Include any relevant log snippets or files here.

**Comment by FabianMauz** [comment]
Was fixed with https://github.com/ComPlat/chemotion_ELN/pull/1639
