### ISSUE TITLE
rails console not found

### ISSUE THREAD

**Issue by brammeleman** [ComPlat/chemotion_ELN#1125]
- I am a system/ELN admin

# Expected Behavior

When starting `chemotion railsc`, you should be dropped in the rails console.

# Current Behavior

Instead, you get the error:
```
bash: rails: command not found
```

## Steps to Reproduce

1. `docker-compose up -d`
2. `docker-compose exec eln bash`
3. `chemotion railsc`

## Workaround

```
# PATH=/chemotion/app/bin/:$PATH
# chemotion railsc
...
Loading production environment (Rails 5.2.7.1)
irb(main):001:0> 
```

**Comment by ptrxyz** [comment]
Thanks a bunch! Will be fixed in next release.

You can stick to the workaround, or simply run `bundle exec rails c` in `/chemotion/app/`.
