### ISSUE TITLE
whitescreen on login page after previous login

### ISSUE THREAD

**Issue by SylviaVanderheiden** [ComPlat/chemotion_ELN#1127]
- I am an ELNer
I logged in into ELN, closed the window (Chrome) and again opened the ELN (home) page.
If you do not direct to ELN or somewhere else directly, it ends in a whitescreen after max. 5 seconds. 
![image](https://user-images.githubusercontent.com/94039752/218944120-bf70a999-4dac-4688-93a3-18fe8f55fc22.png)
This is the page I reopened.
I was still logged in.

**Comment by TasnimMehzabin** [comment]
Fixed.

https://user-images.githubusercontent.com/8912580/227230430-ec3e67d5-0ea0-47a0-bde6-750387f3ce90.mp4

Also this issue becomes obsolete with https://github.com/ComPlat/chemotion_ELN/pull/1225
