### ISSUE TITLE
report function for research plan not available

### ISSUE THREAD

**Issue by SylviaVanderheiden** [ComPlat/chemotion_ELN#1129]
- I am an ELNer

Tried to generate a report for a research plan. 
Though plan was marked it is not possible to push the button for generation, no preview available. 

It should be possible to generate a report (as .docx) of one or more research plans at once. 
![image](https://user-images.githubusercontent.com/94039752/218962095-eb46850a-8856-41d7-a56b-4ab712ba30cf.png)

**Comment by PiTrem** [comment]
resolved with https://github.com/ComPlat/chemotion_ELN/pull/1055
