### ISSUE TITLE
Disabled textbox is actually editable

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#1150]
on v1.4.1, when you open a sample, in the area where you specify "Amount", some inputs are disabled. Yet double clicking allows editing. This deletes the content of the other "Amount" inputs and is probably dangerous. The value is also saved server side and persisted.

[Peek 2023-02-24 11-41.webm](https://user-images.githubusercontent.com/209056/221159497-d1a37164-7880-46cd-9e91-0f7ee7dc30cf.webm)

**Comment by ptrxyz** [comment]
Please note: Density is set to 0.0000

**Comment by TasnimMehzabin** [comment]
https://github.com/ComPlat/chemotion_ELN/pull/1434 resolves this.
