### ISSUE TITLE
Template for Analyses Table Output

### ISSUE THREAD

**Issue by herrdivad** [ComPlat/chemotion_ELN#1156]
# Template for Analyses Table Output

Please create the csv table output as followed:
[Template_CV_V1.csv](https://github.com/ComPlat/chemotion_ELN/files/10839996/Template_CV_V1.csv)

# Format for csv output

CV as a first Example
 
## upper Part

Metadata according to:
Key;Value

## down Part

- Peak Table with header and Data.
- Columns Sepperated by semicolon

**Comment by baolanlequang** [comment]
The feature for CV layout has been implemented at PR https://github.com/ComPlat/chemotion_ELN/pull/1273
This feature is in version https://github.com/ComPlat/chemotion_ELN/releases/tag/v1.6.0
