### ISSUE TITLE
v1.5: Tab bar in sample details pane is off

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#1199]
![image](https://user-images.githubusercontent.com/209056/225446468-37891f03-456b-41be-adf0-a9a05ab24dfa.png)

See picture, sometimes the tab bar in the sample details pane starts somewhere in the middle, not on the left side and thus there is not enough space for tall tabs and they line-break.

**Comment by endevor-music** [comment]
For some reason, I do not have the sample safety information available when running main branch natively, nor can I see it on the public dev-uncharted instance supposedly for testing v1.5?

**Comment by adambasha0** [comment]
The same safety information are only available when the backend service runs in production mode. Therefore, it is not available with development mode. I find it also annoying that it is not available. Maybe there is a trick to run it in development. Not sure who developed the feature, maybe claire. Let's talk about it next week in the group meeting.

**Comment by endevor-music** [comment]
keeping this open for other developers to work on.

**Comment by adambasha0** [comment]
Fixed with PR #1395
https://github.com/ComPlat/chemotion_ELN/assets/55552142/b184edf7-7f7a-4ddc-ace9-5188d31ecf6a
