### ISSUE TITLE
v1.5: Advanced Search does not work

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#1200]
Using the advanced search results in a  error 400 during post request:

![image](https://user-images.githubusercontent.com/209056/225447130-0d4bce78-0f06-4760-bce7-1cd8812a0566.png)
![image](https://user-images.githubusercontent.com/209056/225447274-94e29e9e-f189-4b74-b95a-48620231db7c.png)
![image](https://user-images.githubusercontent.com/209056/225447089-0b6010bb-26a8-4b37-8eb0-e1a034c838b5.png)

**Comment by endevor-music** [comment]
The advanced search works as intended for CAS numbers, _provided a search type is selected by the user_.

A default search type (EXACT, as it may be the most likely option for users), should be provided, to avoid this problem for the entire advanced search functionality.

Testing on v1.5 public test server

Search type EXACT & CAS # 71-43-2 (expecting benzene)
![sample cas number 3](https://user-images.githubusercontent.com/67055123/226879247-c2892974-7d7f-426c-b38c-7490ea44ae96.png)
![sample cas number 4](https://user-images.githubusercontent.com/67055123/226879270-23a55319-27f3-44bc-8355-f66f8b2c39ec.png)

No search type, only CAS number (as above)
![sample cas number 5](https://user-images.githubusercontent.com/67055123/226880343-785e98cb-36c7-4a34-9507-4c580f85dff6.png)
![sample cas number 6](https://user-images.githubusercontent.com/67055123/226880347-80de5c9f-1282-4580-bf4e-b9d9a6cfc240.png)
