### ISSUE TITLE
v1.5: Tab layout popups are messed up

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#1203]
![image](https://user-images.githubusercontent.com/209056/225449389-aed3488c-28eb-4842-9958-451d1ff64593.png)

actually 5 sub-issues, all related to tab layout popups

**Comment by endevor-music** [comment]
Adding the prop `shouldUpdatePosition` to both popups works for the element detail popup, but not the main element list popup: 

https://github.com/ComPlat/chemotion_ELN/blob/e4157c8efa1631729bf850cae0f10c8cc6f338a0/app/packs/src/apps/mydb/elements/details/ElementDetailSortTab.js#L166

https://github.com/ComPlat/chemotion_ELN/blob/e4157c8efa1631729bf850cae0f10c8cc6f338a0/app/packs/src/apps/mydb/elements/list/ElementsTableSettings.js#L241

Video to follow.
