### ISSUE TITLE
lowering threshold does not affect peak picking

### ISSUE THREAD

**Issue by SylviaVanderheiden** [ComPlat/chemotion_ELN#1248]
- I am an ELNer

# Expected Behavior

When you lower the threshold additional peaks within the desired range should additionally be picked.

# Current Behavior

Threshold is changed (line moves and values change) but no more peaks are picked. 

# Failure Information 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. opening spectra editor
2. changing threshold using the arrows

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 
 - Chrome Browser 
 Version: 1.4.1
Base revision: 3270aa43a53c64c89655083faf09dc8999bcf382
Current revision: 66428cf39521b4b5525a28bb64c744eac2226c36

## Failure Logs / Screenshots

![lowering treshhold01](https://user-images.githubusercontent.co
![lowering treshhold02](https://user-images.githubusercontent.com/94039752/228530112-8695cf3a-27b1-4fd4-9ecf-af7dc44bef9e.png)
m/94039752/228530096-68d50247-0b30-4327-a120-1ade21e48aaa.png)

**Comment by SylviaVanderheiden** [comment]
![lowering treshhold01](https://user-images.githubusercontent.com/94039752/228530567-2183eb59-652a-4cb0-98be-f5e0b0043062.png)

**Comment by baolanlequang** [comment]
It's a feature. So we closed it.
