### ISSUE TITLE
White Screen after clicking on CAS-Number.

### ISSUE THREAD

**Issue by MiroHalacz** [ComPlat/chemotion_ELN#1304]
- I am an ELNer
- I am a system/ELN admin

# Expected Behavior

After pressing in CAS-Nr field, text cursor appears there and you could write in CAS-Nr-field.

# Current Behavior

White screen, Chemotion page has to be reloaded with all not safed data lost.

# Failure Information 

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. open a sample
2. under chemical identifiers, press in CAS-field. Bug only if CAS-field is filled with a CAS Number

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: Win 11
 - Chrome Browser 
 - Firefox Browser
 - ELN v1.5.2

**Comment by adambasha0** [comment]
Hello @MiroHalacz, which ELN version do you use?
