### ISSUE TITLE
After Update to v1.5.3 research plan with .tif cannot be opened

### ISSUE THREAD

**Issue by BenjaminGolub** [ComPlat/chemotion_ELN#1316]
- I am a ELN admin

# Expected Behavior

Clicking on a research plan should open the detailed view of the research plan.

# Current Behavior

We updated our Chemotion ELN instance to v1.5.3. One of your users has a research plan with .tif files in it. This specific research plan can now no longer be opened. When clicking on the research plan, the detailed view is not opening. Furthermore, all other open detailed views (e.g. samples or other research plans) are closed.  The .tif files were in the research plan itself.
All the other research plans (without .tif files) are fine.

## Steps to Reproduce

We cannot reproduce the error but assume it should be possible the following way:

1. use Chemotion ELN v1.5.2 and make a research plan with a .tif file in a research plan
2. update Chemotion ELN to v.1.5.3
3. try to open the research plan with the .tif file in it

## Context

We used docker for installing Chemotion ELN and our past versions were: v1.4.1-3; v1.5.2 and now v1.5.3. Unfortunately, we are not 100% sure when the research plan was created. We assume the following:
The research plan was created in v1.4.1-3 (without .tif files), with the updated to v1.5.2 .tif-files were added to the research plan. With the update to v1.5.3 opening the research plan is no longer possible.

## Failure Logs / Screenshots

[error_tif_file_research_plan..txt](https://github.com/ComPlat/chemotion_ELN/files/11486345/error_tif_file_research_plan.txt)

**Comment by endevor-music** [comment]
closing as solved
