### ISSUE TITLE
Import of example XLSX template fails

### ISSUE THREAD

**Issue by timoleistner** [ComPlat/chemotion_ELN#1326]
- [x] I am an ELNer
- [ ] I am a developer
- [ ] I am a system/ELN admin

# Expected Behavior

Example data gets imported.

# Current Behavior

The example data is not imported and following error is thrown "Collection import: There was an issue while processing"

# Failure Information

Collection import: There was an issue while processing
(Are there more detailed error logs? I looked into the [docs](https://chemotion.net/docs/eln/troubleshooting) and couldnt find anything)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open the [live demo](https://demo.chemotion.ibcs.kit.edu/mydb/collection)
2. Download the [example file](https://chemotion.net/docs/eln/ui/toolbar#importing-data)
3. Import the xlsx as collection.

I tried this first with my own sdf file acquired from pubchem. Then I tried the provided example file.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: Microsoft Windows 10 Enterprise
 - Firefox Browser
 - Demo ELN Version

## Failure Logs / Screenshots

Where can I find the logs for the live demo?

**Comment by adambasha0** [comment]
Hello @timoleistner. Thank you for reporting, we are aware of the issue and it will be fixed soon

**Comment by adambasha0** [comment]
fixed with  #1321

**Comment by timoleistner** [comment]
Doesn't work yet for me.

**Comment by adambasha0** [comment]
Hello @timoleistner, The fix has been released with version 1.7. which version are you using currently?

**Comment by timoleistner** [comment]
I'm trying to use the demo on the [website](https://demo.chemotion.ibcs.kit.edu/home) which states that its "Chemotion ELN v1.7.0".

**Comment by adambasha0** [comment]
which file are you trying to import? .. I just tried to import the file you used to open this ticket (https://chemotion.net/docs/eln/ui/toolbar#importing-data) on the demo website and it works well!
