### ISSUE TITLE
Cannot use Chemdraw in samples

### ISSUE THREAD

**Issue by Konrad1991** [ComPlat/chemotion_ELN#1370]
- I am an ELNer

# Expected Behavior

It should be possible to use within the editor to draw molecules (when defining a sample) to use Chemdraw.

# Current Behavior

If choosing Chemdraw instead of Ketcher only a white field appears.

![image](https://github.com/ComPlat/chemotion_ELN/assets/35558461/a92b39a4-5767-4496-abe1-3fac0a82475d)

## Steps to Reproduce

step 1
![image](https://github.com/ComPlat/chemotion_ELN/assets/35558461/fd8293ff-c3ed-40e2-b930-ba376c518176)

step 2
![image](https://github.com/ComPlat/chemotion_ELN/assets/35558461/a1cd3258-5d2f-47e4-9668-8159a6227a34)

**Comment by PiTrem** [comment]
could not reproduce.

Feel free to reopen with more context/info
