### ISSUE TITLE
Total number of research plans, after deleting some

### ISSUE THREAD

**Issue by BenjaminGolub** [ComPlat/chemotion_ELN#1383]
- I am a ELN admin

The bug is hard to explain, I hope the video makes it understandable:
https://cloud.tu-braunschweig.de/s/fcjWtZ3NxJAScZY

# Expected Behavior

The total number of research plans, should always be shown correctly.

# Current Behavior

Example:
I have 33 research plans and on one page there are shown 15 of them (standard), I will have 3 pages, if I now delete 3 research plans from page 2, I only have 30 research plans and only 2 pages. But there is something strange happening, as you can see in the video. On page 1 you still see a total of 33 research plans and you can see, that you have 3 pages not two. If you click on page 3 you will see that nothing changes. Refreshing the page or logging in new into the eln does not help.

## Steps to Reproduce

1. Create 33 research plans 
2. delete 3 research plans from page 2 of the overview of research plans in the collection
3. click on page 1 of the overview of the research plan 

I hope the video makes it understandable, if not, I am happy to provide more information. 

## Context

 - Windows 10
 - Chrome Browser 
 - Chemotion ELN v1.6.0

**Comment by BenjaminGolub** [comment]
I can't see the video (seem to be broken) but sure, we can make a video call if you'd like to? I can show the problem in more detail. Or what information do you need?

**Comment by adambasha0** [comment]
Hi Benjamin, thanks for the reply. The video works for me! - can you reproduce the error on the following test instance:
https://uncharted.chemotion.ibcs.kit.edu/

**Comment by BenjaminGolub** [comment]
I check really fast, and on the test instance, very thing is working fine. (I have no time to make more tests today, but it looks like a problem with our instance). I wil make some more tests tomorrow.

**Comment by BenjaminGolub** [comment]
So, I had to delete the cache in my Chrome-Browser and now very thing works as intended. I apologize for the trouble, I could have thought of this before. (not sure what was in the cache that this was happening with new entries, but it is working now)

**Comment by adambasha0** [comment]
Thank you, Benjamin. I will mark this issue as closed then

**Comment by adambasha0** [comment]
Thank you, Benjamin. I will mark this issue as closed then
