### ISSUE TITLE
Shibboleth connection

### ISSUE THREAD

**Issue by sasscz** [ComPlat/chemotion_ELN#1408]
Hello everyone, we would like to offer Chemotion as a service at our university. This requires a connection to our identity management. There is now the possibility to connect Shibboleth. Unfortunately, there is not so much in the documentation. Therefore, I would like to ask if there is a possibility to get a sample configuration or something similar, so that we can connect our Chemotion to our Shibboleth.
Thank you & best regards
Sascha

**Comment by phuang26** [comment]
@sasscz Thank you for your interest in Chemotion. I would be happy to assist you with the installation and configuration of Shibboleth through a meeting. Please send me an email if this works for you. My email is [pei-chi.huang@kit.edu](mailto:pei-chi.huang@kit.edu).

**Comment by sasscz** [comment]
I have sent you an email and will close the ticket from here.
