### ISSUE TITLE
NMRium button

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#1420]
The button to open NMRium is visible and clickable in ELN for analysis that do not deal with NMR data.

**Comment by baolanlequang** [comment]
Hi @nicolejung, could you provide more details about this issue?

**Comment by SylviaVanderheiden** [comment]
![image](https://github.com/ComPlat/chemotion_ELN/assets/94039752/585b6250-e9c1-4ffa-ba64-e1cd6946d01f)


The NMRium button should only be visible in case one has chosen an NMR-related method (or when the system realizes it is an NMR-file - dont't know if it does)

**Comment by baolanlequang** [comment]
@SylviaVanderheiden 
In the case of Chemspectra cannot read the data and ELN doesn't know what kind of that data is so it cannot determine whether to show NMRium button or not. That is the reason why we always display NMRium button.
