### ISSUE TITLE
Missing sample informations

### ISSUE THREAD

**Issue by MiroHalacz** [ComPlat/chemotion_ELN#1422]
- I am an ELNer
- I am a system/ELN admin

# Expected Behavior

Sample informations showing like in screenshot (works on other accounts, just not on mine)
![Screenshot 2023-07-21 111646](https://github.com/ComPlat/chemotion_ELN/assets/113168734/b38369db-b344-449b-a76c-24fa374600c5)

# Current Behavior

On my acount, no informations are shown (see screenshot). I also cant switch between reactions and samples when i have a sample or reaction opended.

![Screenshot 2023-07-21 113259](https://github.com/ComPlat/chemotion_ELN/assets/113168734/115034f5-2a5a-4673-a511-04d364bceebf)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: Win 11
 - Chrome Browser 
 - Firefox Browser
 - ELN version, 1.7.0

**Comment by MiroHalacz** [comment]
Hi Nicole, I tried that, there is nothing to select (just the Inverntory tab if activated)
![Screenshot 2023-07-21 172248](https://github.com/ComPlat/chemotion_ELN/assets/113168734/0cc61fb5-6e30-4ef1-ac8f-103858347153)
The accounts that works looks like that( as it should I guess):
![Screenshot 2023-07-21 171902](https://github.com/ComPlat/chemotion_ELN/assets/113168734/e4edb70f-695a-4469-96b6-cabcb71e78bb)

**Comment by nicolejung** [comment]
Hi Miro, 
you are right, we will fix it in the next batch-version. In the meantime, I suggest a short call to explain you a workaround - sorry. Patch will come soon.

**Comment by PiTrem** [comment]
Resolved with https://github.com/ComPlat/chemotion_ELN/pull/1411

Available in [1.7.2](https://github.com/ComPlat/chemotion_ELN/releases/tag/v1.7.2)
