### ISSUE TITLE
Unable to activate the comment feature in the admin panel (Internal Server Error)

### ISSUE THREAD

**Issue by BenjaminGolub** [ComPlat/chemotion_ELN#1466]
- I am a ELN admin

# Expected Behavior

In the "UI features" tab of the admin panel, it should be possible to enable the comment feature globally.

# Current Behavior

When trying to activate the "commentActivation" globally an internal server error occurs (see picture). The error also occurs when yo try to activate it only for one account. 
The error output can be read in the censored "CommentFunction_error.txt".

## Steps to Reproduce

1. Update to Version v1.7.2
2. Log in as admin
3. go to "UI features" and try to set "commentActivation" to "true"

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - Chrome Browser 
 - Firefox Browser
 - ELN version v1.7.2

## Failure Logs / Screenshots

![grafik](https://github.com/ComPlat/chemotion_ELN/assets/107389350/a92989a7-1784-4d24-9333-9fd472d8be35)

Error file:
[CommentFunction_error.txt](https://github.com/ComPlat/chemotion_ELN/files/12300900/CommentFunction_error.txt)

**Comment by harivyasi** [comment]
Hi @BenjaminGolub, what was the update made here i.e. from what version of ELN to 1.7.2.

**Comment by BenjaminGolub** [comment]
The update was made from version v1.6.0

**Comment by harivyasi** [comment]
And was the update done using the CLI

**Comment by BenjaminGolub** [comment]
I asked our system admin, the CLI was not used.

**Comment by phuang26** [comment]
confirmed by user and the issue has been solved.
