### ISSUE TITLE
Display bug for wellplates with more than on readout

### ISSUE THREAD

**Issue by BenjaminGolub** [ComPlat/chemotion_ELN#1473]
- I am a ELN admin

# Expected Behavior

The size of the popout window of the information when clicking on one well in the wellplate should scale with the numbers of readouts. 

# Current Behavior

When more than one readout is added, the colors and the save button are out of the window (see picture).
(in older versions, this was not a problem)

## Steps to Reproduce

1. make a wellplate with more than one read out
2. click on a well to the the detail view widnos

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: windows 10/11
 - Chrome Browser 
 - ELN version v.1.7.2

## Failure Logs / Screenshots

![grafik](https://github.com/ComPlat/chemotion_ELN/assets/107389350/da3b0275-9245-4713-b483-c756285442bf)

**Comment by mekkyz** [comment]
Hello BenjaminGolub, 

I fixed this by adding a scroll bar prevent the content getting out of bounds.
Check the video below: I tested with 10 readouts.

file:///home/mostafa/Videos/Screencasts/Screencast%20from%2011.08.2023%2015:05:13.webm

**Comment by BenjaminGolub** [comment]
Thanks, looks good to me :)
