### ISSUE TITLE
Unit conversion and calculations in general

### ISSUE THREAD

**Issue by PaulhatesChem** [ComPlat/chemotion_ELN#1490]
- I am a user of chemotion

# Expected Behavior

Yield and masses are calculted correctly.

# Current Behavior

A yield of >=100% is always calculated, no matter the actual yield.
When given mmol/mol of a starting material, the conversion to mg is just wrong.

# Failure Information 

600 mg of product expected at 100%, 300 mg product mass given -> 100% yield

Starting material has a M of 426.1 g/mol, 200 mmol are given -> 8.522 mg
20 mmol given -> 8522 mg
2 mmol given -> 852.2 mg
2000 mmol given -> 8.522 mg

No calculation at all for mol:
2, 20, 200, 2000 mol all give a mass of 8.522 mg

## Steps to Reproduce

1. Open reaction scheme
2. Put in starting materials, reactants and stuff
3. Fill in an amount of substance (n) as starting material
4. Conversion to mass is wrong

Same for yields
1. follow 1 and 2 as above
2. put in any mass as yield
3. get 0% or 100%, even though the theoretical mass is correct

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - Firefox Browser
 - Version 1.7.2

**Comment by FabianMauz** [comment]
Could not reproduce the error on current main (31.08.23).

Steps to reproduce:
1) create C16H36SeSn, which has a 426.11804 g/mol
2) add it as Starting material and as product
3) enter 2 / 20 / 200 / 2000 mmol for starting material -> autocalculations:
![image](https://github.com/ComPlat/chemotion_ELN/assets/23172219/6cfdde2d-a77e-47f6-9ef0-a8a7b79d3045)
![image](https://github.com/ComPlat/chemotion_ELN/assets/23172219/ae7510cb-2ae5-400b-bc33-21ec58d84fe5)
![image](https://github.com/ComPlat/chemotion_ELN/assets/23172219/65d3a124-07b5-4d27-a1a6-749bb6c4fc44)
![image](https://github.com/ComPlat/chemotion_ELN/assets/23172219/da806256-1180-4975-a8a7-abf1e77ecf11)
4) switching the mol value represantation from mmol -> mol 
![image](https://github.com/ComPlat/chemotion_ELN/assets/23172219/67862130-ff2e-4ea4-9d1b-bad1bb9e6937)
5) Try calculation of different yields
zero product amount
![image](https://github.com/ComPlat/chemotion_ELN/assets/23172219/f90e2aa7-c502-4b5d-ab09-57187397786a)
852.2 product amount -> total conversion
![image](https://github.com/ComPlat/chemotion_ELN/assets/23172219/1dfac231-2a17-4e36-bbc6-a7ea342f5627)
set coefficient to 2
![image](https://github.com/ComPlat/chemotion_ELN/assets/23172219/68af64a0-770a-400c-9886-d972130cc9c1)
half the product amount to 426.1 with coeff 2
![image](https://github.com/ComPlat/chemotion_ELN/assets/23172219/3c95e428-39bc-4b48-888a-493e4321516c)

**Comment by FabianMauz** [comment]
Repeated the whole tests with an decoupled sample with a molecular mass of 426.1 g/mol. Same results, could not reproduce the bug.

**Comment by FabianMauz** [comment]
I noticed that the yield value in the generated svg reaction file is not correct

**Comment by nicolejung** [comment]
Hi PaulhatesChem, we are working on v1.7.2 as productive instance and we don't see the issue. However, if you need and want support, please let us know and we will take care. The helpdesk (mailto:helpdesk@nfdi4chem.de) is a good contact option - or get in contact to me directly, best Nicole

**Comment by PiTrem** [comment]
Will close for now.
Feel free to re-open if it happens again or have more info.
