### ISSUE TITLE
Import chemicals to inventory based on CAS number not SMILES

### ISSUE THREAD

**Issue by matterhorn103** [ComPlat/chemotion_ELN#1493]
- I am an ELN admin

Currently it is possible to import an inventory from an Excel spreadsheet and an entry will automatically be generated for each row if a SMILES string is given. A search is carried out via OpenBabel based on the SMILES string and various fields of the new sample are automatically populated. However, spreadsheet entries without a SMILES are not imported. Since v1.7.0/#1306 it seems it is at least possible to import the CAS number data as a field, but not to use it as the basis for the search. Using the CAS number as the primary basis for a search has a variety of benefits:

- Inventories (certainly ours is) tend to be organized around CAS number rather than SMILES
- Various macromolecules, bulk substances, mixtures, biomolecules, or substances with complex structures don't have (sensible) SMILES strings at all
- Many substances have several different CAS numbers for different forms of the same SMILES string and so the SMILES is ambiguous, but as synthetic chemists it is important to distinguish them. An example would be SiO2, where silicon dioxide, silica gel, quartz and various other forms are distinguishable by CAS but not by SMILES
- The CAS number is then always included within the inventory entry, allowing for searching through the inventory by CAS, and allows the user to much more easily e.g. reorder from chemical suppliers (Sigma-Aldrich doesn't even accept SMILES strings as a search term), find Safety Data Sheets or search SciFinder/Reaxys databases, for all of which the CAS is far more useful than the SMILES. Otherwise the CAS number must be added manually from the dropdown list on each sample, which is obviously impossible for an entire inventory

When creating a sample in ChemMotion, the "fast create" box works very well using the CAS number to automatically get the structure, formula etc. of a chemical. Can this same functionality not be easily reused for the import inventory .xlsx function? Can't the import inventory function just work as an automated version of the create sample function, which works well?

Unfortunately this is the absolute dealbreaker that prevents our adoption of ChemMotion as we would have to manually add thousands of chemicals. As I have only experience in Python and none in Ruby, I am sadly unable to contribute a solution myself.

**Comment by adambasha0** [comment]
Hi @matterhorn103,

The Import & Export chemicals feature is now available for testing on our testing instance: https://uncharted.chemotion.ibcs.kit.edu/mydb
you can create a new user for testing.

With the new updates,  users should be able to import chemical samples with no defined chemical structure (referred to as decoupled samples) based on CAS number

Here is the documentation to guide you on how to use the feature: https://www.chemotion.net/docs/eln/ui/inventory?_highlight=chemical#import-and-export-chemicals

The feature is marked to be released with chemotion version 1.8

Best,
Adam Basha
