### ISSUE TITLE
Can't have liquid sample with only volume data but not mass or density

### ISSUE THREAD

**Issue by matterhorn103** [ComPlat/chemotion_ELN#1494]
- I am an ELN admin

Often a chemical, particularly if it is a solution, has a known volume but not a known density or mass. Unfortunately the volume cannot be specified independently. A substance always has to have a density or mass provided. This limits the capabilities of the ELN unnecessarily.

This is particularly relevant when e.g. 25 mL of a chemical/solution has been purchased and needs to be added to the system. As the density is not automatically sourced by the program when a CAS number or SMILES is provided, it would have to be manually found. Finding accurate density data is often a challenge and for less common chemicals or for solutions the density is sometimes not even known.

**Comment by mekkyz** [comment]
Hi @matterhorn103,
Can you please specify the exact expected/wanted behaviour?

**Comment by matterhorn103** [comment]
Simply that the user should be able to arbitrarily provide a value for the volume, which should be saved by the system without flagging an error, without having to first provide a density or mass. Currently a volume cannot be assigned independently of the other variables.

**Comment by nicolejung** [comment]
Seems that we have a bug in the way how to use the volume for reagents in 1.8.0

**Comment by adambasha0** [comment]
After a discussion with @nicolejung, we agreed to have a volume field for chemicals in the chemical tab. This field will be independent of the mass/density of the sample.
