### ISSUE TITLE
Molecule name field ignored during import to inventory

### ISSUE THREAD

**Issue by matterhorn103** [ComPlat/chemotion_ELN#1495]
- I am an ELN admin

Various fields that can be specified for a sample within the ELN cannot be automatically read from a provided Excel spreadsheet during import. It would be nice if any field that the ELN supports could be imported, but particularly important is the ability to retain names. This is particularly import for us as in our current inventory system the name often contains specific information about the sample such as form (powder, beads, etc), purity, solvent (for solutions) etc.

**Comment by FabianMauz** [comment]
Hi,

i tried to reproduce the issue with the template one can download at [XLS template]( https://chemotion.net/docs/eln/ui/import?_highlight=import). 
After the import with some manual added values all the names of the molecules were present in the eln.

The import as a chemical in the context of the inventory is currently (version 1.7.3) not active, but will be available soon.

@matterhorn103 
It would be a great help for us, if you can provide the xlsx file which causes the problem and make a short description of the steps you did to import it.

Best regards
