### ISSUE TITLE
Not possible to add sample with CAS number if not recognized by "fast create"

### ISSUE THREAD

**Issue by matterhorn103** [ComPlat/chemotion_ELN#1496]
- I am a system/ELN admin

It is possible to add a substance without a structure or SMILES, though the discovery of this could be more obvious - it is only possible to save a new sample after the draw structure box has been clicked, nothing is drawn, then save is clicked to return to the sample entry screen.

It is then possible to return to the sample, which is now classified as a "no-structure sample", and manually add a CAS number.

If a CAS number is entered in the fast create box and it is found, the structure is populated no problem, and the sample can be saved.

If a CAS number is provided but the program doesn't find a corresponding structure, the sample cannot be saved. It should be possible to provide the CAS number from the beginning (i.e. the "CAS" box in the top left of the screenshot below should also be available on the Create Sample screen) and it should be possible to create a sample with only a CAS, even if it is not recognized by the program.

![Screenshot_20230822_143904](https://github.com/ComPlat/chemotion_ELN/assets/83813148/343d2ddb-6a53-4f22-97c0-9d9f50db3bea)

A good example is silica (as referred to in #1493 as well) - a sample with CAS 7631-86-9 (silicon dioxide) can be created successfully but trying to use "fast create" with the CAS of silica gel 112945-52-5 or quartz 14808-60-7 doesn't work, despite them being valid CAS numbers with associated molecular formulae, just no defined structure/SMILES.

**Comment by adambasha0** [comment]
Hi @matterhorn103,

We have a decoupled check box option for no-structure samples. It looks disabled in your Chemotion ELN instance. This feature can be enabled from the admin profile. After creating a decoupled samples, users have the ability to add cas number manually for the created decoupled sample. We have updated the decoupled feature and fixed some bugs in the upcoming version 1.8. You are welcome to test it now on our test instance. 
 
Kindly refer to my comment on issue [#1493](https://github.com/ComPlat/chemotion_ELN/issues/1493#issuecomment-1735252610) to know how to test it

![image](https://github.com/ComPlat/chemotion_ELN/assets/55552142/abfe4a5b-5a2c-44eb-99d1-6c301a9ea503)


Best Regards,
Adam

**Comment by matterhorn103** [comment]
Great, thanks, we'll give it a spin :)

Perhaps having the option on by default, rather than having to enable it in the admin settings, and maybe calling it something else more descriptive than decoupling, would help with discoverability? We were completely unaware that this option existed!

Thanks

**Comment by adambasha0** [comment]
fixed with #1524
