### ISSUE TITLE
style issue for boxes in sample

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#1499]
A style issue for samples - properties tab: 
the area "properties" and "solvents" are given in boxes. Is this really necessary? It is a bit confusing as none of the other information is given in that way. 
The alignment of information in particular in the solvents box needs to be optimized
There is a style bug when opening the dropdown for solvents - the box is not closed at the right side

**Comment by mekkyz** [comment]
Hi Nicole.

I removed the collapse boxes for "additional properties" and "solvents" and instead made them as titles to separate sections in the properties tab "Additional Properties" and "Solvents" to match design to other fields.

I also adjusted the layout of the solvent box to match other fields.
Style bug for the dropdown is fixed.
Please check the video below to see the changes
[Screencast from 24.08.2023 19:01:47.webm](https://github.com/ComPlat/chemotion_ELN/assets/59936007/a1fd696d-8995-4419-aee6-38cb097ec1a0)
Please tell me if this needs further adjustment

**Comment by nicolejung** [comment]
I think it makes the sample clearer and is nice - but needs additional space. Let's keep it as suggested and try to find improvements in the future
