### ISSUE TITLE
Showing ELN address - to be used to send files to the ELN inbox

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#1500]
Could we find/define a way to let the users know about the email address they have to send information to for adding files to the ELN -inbox? At the moment, I think most of the users don't know that this is possible - others know but don't remember the email address. In the end, the feature is not used - but could help a lot

**Comment by PiTrem** [comment]
https://github.com/ComPlat/chemotion_ELN/pull/1529

**Comment by PiTrem** [comment]
duplicate #1514
