### ISSUE TITLE
XRD data in ChemSpectra

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#1515]
For XRD data, we need two additional ways to summarize the content of an XRD measurement: (1) inline notation, (2) table format. For both, we need information on general description/metadata and data. 
Metadata: Measurement type (fix = XRD), source that is used (e.g. Cu Kα, needs to come from user input in layout), general information on the data recorded/plotting (fix = 2θ [°] (d [nm])). 
Therfore, the inline notation should look like: 
General description: XRD (Cu Kα1, 0.15406 nm), 2θ [°] (d [nm]): 
Data: x-value (d-value) --> both gained from peak picking in the layout

XRD (Cu Kα1, 0.15406 nm), 2θ [°] (d [nm]): 5.2 (1.68), 10.1 (0.83).

A table layout would be the next step - to be defined soon

**Comment by nicolejung** [comment]
Here an update: -> we need to include the temperature in °C (xxx = value), please see the corrected description below. The temperature should be part of the metadata from the measurement, if possible, should be taken from there. If we need clarification/discussion, please let me know:
XRD (Cu Kα1, 0.15406 nm, xxx °C), 2θ [°] (d [nm]): 5.2 (1.68), 10.1 (0.83)

**Comment by schatzsc** [comment]
Minimum required data on XRD measurements by typical journals in the figure below

![XRD](https://github.com/ComPlat/chemotion_ELN/assets/88166560/1c691de8-501a-46b6-9547-30ddb534fa24)

**Comment by nicolejung** [comment]
topic above deals with PXRD - sorry for the confusion
