### ISSUE TITLE
Adding User to Group via Admin Interface fails

### ISSUE THREAD

**Issue by MichaelOCI** [ComPlat/chemotion_ELN#1525]
- I am a system/ELN admin

# Expected Behavior

Until recently I was able to login to Chemotion ELN (1.5.3) as Admin to create and add the new Users to our (Work)Group

# Current Behavior

Currently I am still able to Create new Users. Even with logging out from Chemotion and loging in again I am unable to add the new User to our (Work)Group as the new user is not found in the search field.
The problem is not limited to my Admin account, if one logs in with another Admin login the same problem occurs.

# Workaround

If a normal user is given Admin privileges for the User Group the nomal user can login to Chemotion ELN and add the user. - But the search result list is cutoff in FireFox. The Search function apparently  also only accepts only the beginning of the User Abbr.

**Comment by PiTrem** [comment]
should be resolved with 

https://github.com/ComPlat/chemotion_ELN/pull/1385 that fixed https://github.com/ComPlat/chemotion_ELN/issues/1384 and #1360 

Available from version 1.7.0
