### ISSUE TITLE
Additional system-defined unit + selecting a default unit

### ISSUE THREAD

**Issue by f-idiris** [ComPlat/chemotion_ELN#1532]
- I am a developer 

# Description
1. Could we add the unit nm/min in speed system-defined units? 
2. When creating generic datasets and using system-defined units, it would be helpful if we could set a default unit from the list.

**Comment by cllde8** [comment]
Hi all,

LabIMotion 1.3.0 has been released! You can try it out in ELN 1.9.2, which includes LabIMotion 1.3.0.

One of the key topics addressed in this release is the System Units. More system units are now supported. Please visit [LabIMotion 1.3.0](https://github.com/LabIMotion/labimotion/wiki/blog) for more details. Click [here](https://github.com/LabIMotion/labimotion/wiki/Supported-Units-of-System-Defined-Field) to view the complete list.

If you have any further questions or suggestions, please don't hesitate to reach out to us at https://github.com/LabIMotion/labimotion/tree/main.

Thank you for your support.

Best regards,
Claire
