### ISSUE TITLE
1H NMR Reference values for solvents: D2O

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#1535]
The list of solvents-reference values for 1H NMR data needs to be corrected for D2O (deuterium oxide as given in the list): 
Please change: "deuterium oxide" -> "D2O" (in the dropdown list/selection of solvents)
Please change value from "4.75" to "4.79".

**Comment by baolanlequang** [comment]
@PiTrem this issue is solved by https://github.com/ComPlat/chemotion_ELN/pull/1557
