### ISSUE TITLE
PR #1523 broke callers of `BaseFetcher.fetchByCollectionId()`?

### ISSUE THREAD

**Issue by JanCBrammer** [ComPlat/chemotion_ELN#1543]
PR #1523 (commit 7c8acc00136515d90f48d1dc50c2596380bf73c1) changed the call signature (i.e., order of parameters) of `fetchByCollectionId()` from
`fetchByCollectionId(id, queryParams = {}, isSync = false, type = 'samples', ElKlass)` to
`fetchByCollectionId(id, ElKlass, queryParams = {}, isSync = false, type = 'samples')`,
seemingly as a result of automated formatting.

However, the callers of `fetchByCollectionId()` haven't been updated correspondingly.
This seems to result in broken requests:
![image](https://github.com/ComPlat/chemotion_ELN/assets/30125107/d8ad32bc-60c5-4270-9f27-3e1656a4b6c6)

After restoring the call signature, the requests no longer fail.

**Comment by PiTrem** [comment]
solution ?
https://github.com/ComPlat/chemotion_ELN/pull/1542

**Comment by JanCBrammer** [comment]
Didn't see #1542. Yes, that's the exact fix I've had in mind.
