### ISSUE TITLE
Show some preview in the Screen, Research Plan, and Generic Elements lists

### ISSUE THREAD

**Issue by schatzsc** [ComPlat/chemotion_ELN#1549]
In contrast to the Sample and Reaction listings, the Screen, Research Plan, and Generic Elements lists look very uninformative, with the large white space highlighted in red in the attached picture. Is it possible to show some preview there to get a better idea of what's in there, like the first text or graphical element, or a "thumbnail" of the full expanded window?

![research plan](https://github.com/ComPlat/chemotion_ELN/assets/88166560/89f8ce4a-14fb-4988-b0c7-3045184ecf77)

**Comment by nicolejung** [comment]
You can add an image file (*.png, *.jpg) as image to the attachment tab of the research plan. This image is taken as preview image in the list entry

**Comment by schatzsc** [comment]
That's generally a nice feature, although it does not seem to be much known, since the trainers in today's on-site course did not know about it.

Besides that, the functionality does not work at least in the test installation used for the training on xxx.chemotion.scc.kit.edu

(top) after dropping a test *.png file into the file select box
(bottom) after pressing "save", the "animated circle symbol" appears indicating upload, but when it has finished, the Files box is empty again and reads "There are currently no attachments." Also tried with *.jpg and did not work either

![attach1](https://github.com/ComPlat/chemotion_ELN/assets/88166560/b6900b70-836f-4a46-a41b-1e03429decba)
![attach2](https://github.com/ComPlat/chemotion_ELN/assets/88166560/78eb117a-0a09-450b-b947-4864242687b8)

**Comment by nicolejung** [comment]
ok - seems to be a special issue with the test server. I tested with the central test instance at https://chemotion.net/ (v1.7.3) and also the version v1.7.2 and they work as expected.  We will discuss and will test again before the next release.

**Comment by PiTrem** [comment]
resolved with #1558

having an image in the ResearchPlan body or as an attachment should generate a thumbnail that is visible form the list

![image](https://github.com/ComPlat/chemotion_ELN/assets/15799181/06fddff1-49f8-4be3-b70c-16fadda2b93a)

![image](https://github.com/ComPlat/chemotion_ELN/assets/15799181/3a28aa8e-8173-4bf8-ba37-a6bf5dde81e4)


We could think of previewing a page of the whole body 🤔 .

closing for now.
