### ISSUE TITLE
Control of standard user login and sign-up

### ISSUE THREAD

**Issue by schatzsc** [ComPlat/chemotion_ELN#1577]
General faculty-wide access to Chemotion will start at the University of Würzburg on 16.10.2023. For that purpose, **we need to control how standard (non-admin) users can sign-up and then afterwards login in to Chemotion.**

The intended method is login via the university Shibboleth identify control system while standard users should not be able to sign-up to Chemotion separately. Therefore, a customizable option is needed for the main administrator to enable/disable the "sign-up" button highlighted as a red box and arrow in the attached picture.

![chemotion_uw](https://github.com/ComPlat/chemotion_ELN/assets/88166560/15a779ab-fda2-4333-8383-c176e963a179)

**Comment by phuang26** [comment]
@schatzsc Hi Ulrich, this feature has been included in ELN v1.7.0, please refer to:
https://www.chemotion.net/docs/eln/admin/features#user-authentication-userprovider "extra rules".

**Comment by schatzsc** [comment]
@phuang26 Well, thatever the issue was, Christoph Brüning from our computer center was able to solve it with the information provided and now it works as intended with only the Shibboleth login available to regular users, see attached picture.

Today, we also opened official user operations for Chemotion at the University of Würzburg on an institution-wide scale and in my group a new Master student doing a 8-week practical started to use it and filled in the first reaction (-:=

![Chemotion login](https://github.com/ComPlat/chemotion_ELN/assets/88166560/f94d6b5a-4fe2-4e41-8a3d-86e78b44e7a5)
