### ISSUE TITLE
Expand options available in the "Purification" section of a reaction

### ISSUE THREAD

**Issue by schatzsc** [ComPlat/chemotion_ELN#1594]
A situation that we encounter quite often is that a crude product contains solvent (an assessment usually based on NMR and/or CHN analysis) and has to be dried before final analysis. Therefore, the "purification" options available for reactions should be supplemented with a "Solvent removal" or "Drying" option:

![chemotion purification](https://github.com/ComPlat/chemotion_ELN/assets/88166560/c1c198d3-1013-4be3-ae5b-734338f9023b)

Usually, this requires information on

- at which temperature the sample is dried (room temperature or another higher value)
- if the sample is dried under reduced pressure (usually, on the oil pump)
- how long the sample is dried

Sometimes, in particular with sensitive biomolecules, also other methods such as freeze-drying on a lyophilizer are used, in which the temperature is significantly below 0 °C.

**Comment by nicolejung** [comment]
the idea of this dropdown is to give purification methods as an additional hint. The details on drying an other possible topics need to go into the full text description of the reaction process. 
We are working on a comprehensive model to describe chemical reactions with all details - without textual description - but it won't be available before 2024.

**Comment by nicolejung** [comment]
Ok to close it with the info given above? @schatzsc

**Comment by schatzsc** [comment]
Well, not 100% sure - in a way the "drying on the pump" is a important step of operation from crude product to final analyzed product, possibly not only in inorganic chemistry. It also relates to the issue of the different "yields" and which yield to put into the top of the reaction field.

I guess it can be closed here for the moment but should indeed be included in a more detailed revision of the chemical reaction descripton.

My coworkers did not really like it because it requires recording at lot of (in their opinion: too much) details but I think the "flow of matter" from initial mixing of reactants and reagents to final pure product that is used for further studies or as a precursor in another reaction step is the core of describing a reaction and the changes in matter (= weight) should be easier to record from step to step.

**Comment by nicolejung** [comment]
ok, we will close it here and bring it back later - if the detailed version does not fit all requirements

**Comment by nicolejung** [comment]
-> later development: FAIR reaction description
