### ISSUE TITLE
Import of Bruker NMR files not working

### ISSUE THREAD

**Issue by schatzsc** [ComPlat/chemotion_ELN#1597]
In the attached ZIP archive there is a recently measured Bruker NMR spectrum from our group. Whatever we do and which folder or subfolder we pack, it does not open in the spectrum editor of Chemotion. The [documentation](https://chemotion.net/docs/services/chemspectra/nmr) mentions that "For NMR analysis, we currently support ... zip (Bruker FID ...) files" but neither packing just the fid file or anything else solves the problem?!?

Our version of Chemotion is v1.7.2 with base revision 2d8e2fabd

[USC-XD256-01.zip](https://github.com/ComPlat/chemotion_ELN/files/13120152/USC-XD256-01.zip)

**Comment by nicolejung** [comment]
Confirmed - doesn't work for me either on complat-eln
