### ISSUE TITLE
NMRium does not close 

### ISSUE THREAD

**Issue by SimoneGraessle** [ComPlat/chemotion_ELN#1602]
Hi all, 

First, the NMRium takes a very long time to open a 2D spectrum I try it with HSQC, HMBC and COSY). 
If you then go to "Close with Save", it also takes a long time to upload the spectra. And then the program does not close. 
When you then go to "Close without Save", of course nothing is saved. 

But that doesn't always happen. But that it takes a long time is always. 

Best wishes, 
Simone

**Comment by baolanlequang** [comment]
Hi @SimoneGraessle , which instance or version of ChemotionELN that you used?
