### ISSUE TITLE
Converter Profile not visible from My Devices

### ISSUE THREAD

**Issue by tilfischer** [ComPlat/chemotion_ELN#1621]
Dear all,

- I am an ELN user
- I am a system/ELN admin

# Current Behavior

Login as user.

If I select my name on the top right, I see seven options: Account & Profile, Change Password, My Affiliation, My Group & Devices, Converter Profile, My Devices, Generic Designer. 

If I select My Devices and select my name on the top right, I see six options: Account & Profile, Change Password, My Affiliation, My Group & Devices, My Devices, Generic Designer. 

--> Converter Profile is missing.

# Expected Behavior

To also see and may select seven options, including Converter Profile, when on page of My Devices.

## Context

 - OS: macOS Catalina 10.15.7
 - Chrome Browser 118.0.5993.88 
 - ELN version v1.8.0

**Comment by phuang26** [comment]
will be included in 1.9

**Comment by tilfischer** [comment]
Thank you!
