### ISSUE TITLE
Template HRMS-FAB 

### ISSUE THREAD

**Issue by SimoneGraessle** [ComPlat/chemotion_ELN#1624]
If you select the template for the HRMS-FAB, this is what appears at the moment: 
HRMS–FAB (m/z): [M + H]+ calcd for MASS; found MASS.

But this would be the right one:
HRMS–FAB (m/z): [M+H]+ Calcd for MASS; Found MASS.

Can you please change that?

Thank you and best regards, 
Simone

**Comment by nicolejung** [comment]
HRMS (FAB, matrix NBA): m/z = calcd for **sum formula** [M]+: xxxx; found: xxxx. 
Info: "]+" -> "+" should be superscript

**Comment by mekkyz** [comment]
Hi, can you please provide a screenshot?

**Comment by PiTrem** [comment]
- HR-FAB: 
![image](https://github.com/ComPlat/chemotion_ELN/assets/15799181/ad1163fb-1f10-424b-830d-a3bff830fd45)


- HR-EI:
![image](https://github.com/ComPlat/chemotion_ELN/assets/15799181/147acfec-39c0-4e43-a0be-24f0961a4474)

**Comment by SimoneGraessle** [comment]
Hi all, 

The spaces between M and + and + and H are not right. Can you delete them?
Everything else is perfect. Thank you :)

Best regards 
Simone
