### ISSUE TITLE
Can't use ketcher to draw structures

### ISSUE THREAD

**Issue by SethosII** [ComPlat/chemotion_ELN#1628]
- I am a system/ELN admin

# Expected Behavior

It should be possible to draw the structure of some sample with ketcher.

# Current Behavior

When you open the structure editor you get different results depending on the browser. With Firefox you will get a note that it blocked the iframe for security reasons and get the option to open it in a new tab. Opening it in a new tab (https://FQDN/ketcher) displays the editor. However, you can't save your drawing. 

# Failure Information 

The concole in Chrome says: `Refused to display 'https://FQDN/' in a frame because it set multiple 'X-Frame-Options' headers with conflicting values ('SAMEORIGIN, DENY'). Falling back to 'deny'.` Firefox also complains about no valid X-frame option and afterwards `Uncaught DOMException: Permission denied to access property "ketcher" on cross-origin object`

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. I created a fresh installation with chemCLI
2. log in with a test user
3. create a new sample
4. click on the strucutre editor
5. only save and cancel buttons are displayed, the main editor window isn't displayed

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: Ubuntu 22.04 for the server, Windows 11 on the client
 - Chrome and Firefox Browser
 - ELN version 1.8.0

## Failure Logs / Screenshots

Screenshot from Chrome: ![chemotion_ketcher](https://github.com/ComPlat/chemotion_ELN/assets/4445745/82600752-7dbe-431e-9d77-0915d74251b7)

**Comment by PiTrem** [comment]
@SethosII 
Does your server configurations set the X-Frame-Options twice?
This header should only be set to SAMEORIGIN for the editor to load.

**Comment by SethosII** [comment]
@PiTrem Thank you for the hint. The problem was the Nginx reverse proxy in front of Chemotion, which had `add_header X-Frame-Options DENY;` in it's configuration. It works now after changing it to `SAMEORIGIN`.
