### ISSUE TITLE
Drag and Drop of an Inbox Bagit File will not fill out Metadata

### ISSUE THREAD

**Issue by herrdivad** [ComPlat/chemotion_ELN#1636]
- I am an ELNer
- I am a developer

# Expected Behavior

Drag & Dropping a converted Bagit File from Inbox into an analysis and click save, the Picture should be generated and the Generic Metadata Fields should be filled out.

# Current Behavior

For some techniques / ontologies, only the picture will be generated but the Metadata Fields stay empty.

# Failure Information 

Failure occurs for converted GC Files (.gcd.txt -> zip) from INBOX. Converted CV Files from INBOX work. Also uploading any File from hard drive works. 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: Windows
 - Chrome Browser 
 - Firefox Browser
 - ELN version 1.8.0

**Comment by cllde8** [comment]
After a collaborative review of the function with David, it has been confirmed to be functioning effectively in the Complat ELN. As a result, this ticket will be closed, and David will be in touch with the user directly.

**Comment by nicolejung** [comment]
thanks a lot

**Comment by herrdivad** [comment]
Hi Paggy and and Claire,

Sorry for this topic again, but I just tested again with our Chemist / GC User Elena (CC) and regardless of what we do, it will not work.
I’m currently out of ideas, so I would suggests that you will please meet her directly, so that she can show it to you. She’s in our Lab at Campus North.
Maybe we are doing something wrong, but I have no idea what I could be …

Thanks and best wishes
David

Von: Chia-Lin Lin ***@***.***>
Gesendet: Donnerstag, 7. Dezember 2023 11:16
An: ComPlat/chemotion_ELN ***@***.***>
Cc: Herrmann, David (IBCS) ***@***.***>; Author ***@***.***>
Betreff: Re: [ComPlat/chemotion_ELN] Drag and Drop of an Inbox Bagit File will not fill out Metadata (Issue #1636)


After a collaborative review of the function with David, it has been confirmed to be functioning effectively in the Complat ELN. As a result, this ticket will be closed, and David will be in touch with the user directly.
