### ISSUE TITLE
Table Format in Research Plans cannot be altered

### ISSUE THREAD

**Issue by ChrizzleGrazzl** [ComPlat/chemotion_ELN#1640]
- I am an ELNer

# Expected Behavior

When I insert a table into the research plan, I would like to be able to change the number of rows and columns.

# Current Behavior

At the moment a table with 6 columns and 3 rows is inserted. Only the column names can be changed, but no columns or rows can be added or removed.

![Screenshot 2023-11-27 143446](https://github.com/ComPlat/chemotion_ELN/assets/126082604/b397afd3-80d4-40c8-982c-26ea685e8ca7)

**Comment by PiTrem** [comment]
@ChrizzleGrazzl 
you should be able to add/remove rows and columns through the context menu (right-click on a value-cell, not on the header line  )


![image](https://github.com/ComPlat/chemotion_ELN/assets/15799181/c862bb5a-5282-423a-8e42-d1f2b44022aa)

**Comment by ChrizzleGrazzl** [comment]
Thanks a lot for clarification. I thought the x in the header would be used to delete columns.
Works fine!
