### ISSUE TITLE
Little improvements: style

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#1646]
![Screenshot (1183)](https://github.com/ComPlat/chemotion_ELN/assets/7559189/92bd841e-1325-462c-b35d-1f0aaca5f6a8)

please adjust two things: 
- color of the short label/name given in the header (-> change to white)
- add a space

**Comment by mekkyz** [comment]
Hi Nicole, I can not recreate this. Can you please tell me when the sample title turns this color?
