### ISSUE TITLE
Allow the definition of Generic Datasets for any existing Ontology + Use of existing Generic Datasets as Template for new ones

### ISSUE THREAD

**Issue by MichaelOCI** [ComPlat/chemotion_ELN#1705]
- I am an ELN admin

# Definition of Generic Datasets
If one looks at the list of defined Ontologies of analysis methods the list of methods is more comprehensive than the list of generic datasets (5 of them -EA, HPLC, IR, TLC and MS-  even just are defined heading without any data fields and the Admin or User hav to edit the generic dataset to make use of it). It would be great to add generic datasets for analysis methods, where currently no generic dataset is defined.
As the existing generic datasets are quite comprehensive. The definition of a generic Dataset for an ontology, that has no generic dataset would be much easier, if an existing generic dataset could be used as template.
An additional benefit would be, that the use of adapted, already existing  datasets for related Ontologies may contribute to some degree of standardization.

**Comment by cllde8** [comment]
Hi @MichaelOCI 

Thank you for choosing LabIMotion. The LabIMotion Template Hub already provides a variety of segment and dataset templates contributed by the scientific community. You can sync templates that fit your needs from the Template Hub to your instance and start using them. This approach not only leverages the collaborative efforts of scientists but is also highly recommended for designers.

To sync the templates, please refer to the video available at [Sync Templates from Template Hub](https://youtu.be/gddh2q5XYvQ) in the documentation section [Template Sync & Publish](https://www.chemotion.net/docs/labimotion/template-sync-and-publish). Another notable feature is that, through this method, users can benefit from the ChemConverter service, streamlining automatic metadata extraction from raw files and ensuring seamless mapping to the Generic Dataset. A demonstration video is accessible at [Converter Metadata](https://www.chemotion.net/docs/labimotion/guides/user/datasets/converter-metadata). Moreover, this approach effortlessly facilitates the transfer of data to the Repository for publication, see [Publish your work](https://www.chemotion.net/docs/labimotion/template-sync-and-publish#publish-your-work).

For reusing existing templates, simply [download](https://www.chemotion.net/docs/labimotion/guides/designer/template-features/preview-design#download-) the version you need and [upload](https://www.chemotion.net/docs/labimotion/guides/designer/template-features/workarea#toolbar-of-work-area) it to the system for immediate use.

Please feel free to share your use case with us if you can't find the template you need on the Template Hub. Currently, there are more templates in progress. If you'd like to join or get a preview, please feel free to reach out to me, and I'll provide you with the information. 

Thank you.

Best regards, 
Claire
