### ISSUE TITLE
Failure to save data field of Generic Segments if Generic Segment is part of Generic Element if field was not filled before Element creation

### ISSUE THREAD

**Issue by MichaelOCI** [ComPlat/chemotion_ELN#1706]
- I am an ELN admin

# Expected Behavior

After the Creation of the Element extended by a Generic Segment it should be possible to add values of the fields of the Generic Segment.

# Current Behavior + Failure Information + Steps to Reproduce

In Samples the data fields work as expected, other predefined Elements I haven't tested.
BUT if I define a Generic Element and a Generic Segment belonging to this Generic Element:

- Values entered before clicking Create are saved
- The values entered before clicking Create can be changed as expected
- If values are entered into fields, that were empty before clicking Create are deleted if one tries to add the value and clicks SAVE

 
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - Server VirtualBox VM with Ubuntu
 - Client Windows PC
 - both Firefox and Chrome Browser
 - Chemotion ELN 1.8.1

**Comment by cllde8** [comment]
Hi @MichaelOCI 

Thank you for bringing this issue to our attention. This issue has been resolved and the fix will be included in the future release. 

Best regards,
Claire
