### ISSUE TITLE
NMR solvent shift for 13C NMR

### ISSUE THREAD

**Issue by HSimek** [ComPlat/chemotion_ELN#1722]
- I am an ELNer (ComPlat)

The solvent reference shift of Chloroform-d in 13C NMR is 77.16 ppm. However, in the inline notation, this number is rounded by the system to 77.2 ppm. Although we give all other signals with only 1 decimal place, we want the solvent shift to be written with 2 decimal places, meaning the analysis content should contain the solvent shift with 2 decimal places (e.g. 77.16 for Chloroform-d) and start as described here: 13C NMR (100 MHz, Chloroform-d [77.16 ppm], ppm) = .... For more clarity, I´m uploading a picture.
![solvent shift](https://github.com/ComPlat/chemotion_ELN/assets/94601059/796bdf2c-24fa-4b42-b440-90d8c0314dfb)

**Comment by schatzsc** [comment]
Beyond that, it should generally be possible for the user to adjust the number of decimals in the NMR shift, as that strongly depends on the nucleus and local requirement. For example, we always give 13C NMR shifts to two relevant digits!

**Comment by HSimek** [comment]
> Beyond that, it should generally be possible for the user to adjust the number of decimals in the NMR shift, as that strongly depends on the nucleus and local requirement. For example, we always give 13C NMR shifts to two relevant digits!

This is possible within the spectra editor. On the top right side (as marked in the screenshot), the user can decide with how many digits he wants to have the signals given. 
![digits](https://github.com/ComPlat/chemotion_ELN/assets/94601059/540d13c6-76a9-4872-a05c-74575edb46c6)
