### ISSUE TITLE
Faulty assignment of Generic Segment provided by LabIMotion Hub??

### ISSUE THREAD

**Issue by MichaelOCI** [ComPlat/chemotion_ELN#1751]
- I am an ELN admin

I already wrote yesterday to NFDI4Cem helpdesk, but maybe it is better suited for a bug report:

One of the workgroups at our faculty was not too happy using Chemotion ELN as some UI Features important to the group (for MOFs) were missing when we introduced Chemotion ELN.

I am currently testing the Generic Features and was pleasantly surprised to find MOF details and MOF reaction as Generic Segments. After a short look at the Segments I am a bit puzzled:

Both [(Sur) MOF Details]  and [(Sur)MOF Reaction] downloaded from LabIMotion Hub belong to the Element “Sample” – is that an error?? I would have expected [(Sur)MOF Reaction] to belong to the Element “Reaction”.

**Comment by nicolejung** [comment]
Hi Michael, thanks for adding this point here. Do you have time for a short teams/phone call? MOFs are under development at the moment, but some of the features can be used already. Anyhow - it makes sense to talk as we are looking for people that may review the planned additions to the segments... this allows your colleagues and students to contribute and add their thoughts.

**Comment by MichaelOCI** [comment]
Hello,
Last week I tried to import segments downloaded from LabIMotion Hub to a second Test-VM (I want to try to transfer data from generic components from one VM to the other). I imported generic Elements and Segments I designed on the first VM to the second. As the import list of LabIMotion showed the correct assignment  of MOFs to sample and reaction I also imported the three Generic Segments provided by LabIMotion Hub to both VMs.
On the first VM all three Generic Segments were assigned to sample, on the second VM all three Generic Segments were assigned to the Generic element. If one tries to edit the imported Segments the dropdown list of the "parent element" is empty.
Apparently the imported Generic segments lack the information regarding the "parent element" and are always assigned to the same "parent element". The selection of the "parent element" follows no comprehensible rule.
Best regards
Michael

**Comment by cllde8** [comment]
Hi @FabianFink and @MichaelOCI 

Thank you for bringing up the issue and providing the details. I am currently investigating it and will provide updates on the progress [here](https://github.com/LabIMotion/labimotion/issues/7).

Best regards,
Claire

**Comment by MichaelOCI** [comment]
Hello,
regarding your request for the ELN Version(s) by mail. The 1st VM was installed 17.1.2024 with Chemotion ELN 1.8.1
the 2nd VM is from 12.2.2024 with Chemotion ELN 1.8.2
Best regards
Michael

**Comment by MichaelOCI** [comment]
Hello,
thank you for your message. I tested the import on 2 of my test VMs and now the import works as expected.
Thank you
Michael
