### ISSUE TITLE
*** in the analysis name

### ISSUE THREAD

**Issue by HSimek** [ComPlat/chemotion_ELN#1758]
- I am an ELNer (ComPlat)

If I want to change the name of an analysis and delete the current name, three stars *** appear. If I try to delete them, they just appear again. I know there are is a work-arounds for this but not everyone knows it so it would be great if this bug could be fixed. 
![Bug stars in analysis name](https://github.com/ComPlat/chemotion_ELN/assets/94601059/5db51aeb-f964-4ae8-9a98-8a1c9a3ed38a)

**Comment by PiTrem** [comment]
resolved with [fix: analysis name issue #1846](https://github.com/ComPlat/chemotion_ELN/pull/1846)
