### ISSUE TITLE
Opening MS spectra

### ISSUE THREAD

**Issue by HSimek** [ComPlat/chemotion_ELN#1759]
- I am an ELNer (Complat)

We (Complat) normally upload two files for Mass analysis (two datasets in one analysis), one is the MS File which can be processed and analyzed, and the second one is HRMS which appears as a blank spectrum. Per default, the preview is unfortunately generated from this blank HRMS file and this file opens when I open the Spectra Editor. In spectra editor, I have the possibility to select between the two files, and when I select and analyze the MS file and press save and close, the correct preview is also saved, but - if I want to open the spectrum again with the Editor, again the HRMS opens and not the MS and I have to switch files manually. 
Would be great if this could be fixed.
Screenshot 1 (preview) - you can see that the preview has been generated from the correct file as peaks are visible.
Screenshot 2 (spectrum) - you can see that the next attemt to open the file again opened the blank HRMS.
![bug MS-HRMS preview](https://github.com/ComPlat/chemotion_ELN/assets/94601059/222af8d6-5134-4f5a-93fd-af3ecfc61d65)
![bug MS-HRMS spectrum](https://github.com/ComPlat/chemotion_ELN/assets/94601059/d3d64b9e-76be-4bb4-9feb-c59f4ddd824a)

**Comment by baolanlequang** [comment]
This issue will be fixed at https://github.com/ComPlat/chemotion_ELN/pull/1778

**Comment by PiTrem** [comment]
will be in the next release 1.9.0
