### ISSUE TITLE
Export and Import of Collections  containg Data in self designed Generic Components

### ISSUE THREAD

**Issue by MichaelOCI** [ComPlat/chemotion_ELN#1798]
- I am a ELN admin

# Expected Behavior

To be a useful for long term use Chemotion should be able to export Collection containing data in self designed Generic Elements / Segments and Generic Datasets and import all data to Chemotion, even a second Chemotion ELN Instance.

# Current Behavior

## Generic Elements

As discussed with Nicole Jung today -If a collection containing data in self designed Generic Elements is exported and one tries to import the Collection to the same Chemotion instance the imported Collection does not contain data in the self designed Generic element, only data in predefined Elements. Inspecting the json inside the exported ZIP I could not identify data of the Generic Element. 
The same procedure does NOT fail for Samples containing Generic Segments.

## Import to different Servers

1. I opened the Designer for Generic Components on the Server used to export the Test collection. I downloaded the latest version of the self designed Generic Elements and Generic Segments 
2. I opened the Designer on the second Server and
3. Generated an empty Generic Element/Segment and uploaded the respective templates from Server 1
4. I exported a collection of Samples with Data in fields of the Generic Segment and attempted to import into Server 2
The Samples on Server 2 contained only the data in predefined Fields, but none in the Generic Segment

First idea an uuid issue - but attempting to unzip the exported collection, use search and replace to adapt the uuids if one is able to find the correct ones. However this would be prohibited by issue #1797

## Steps to Reproduce

see above

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 -Windows (Client), VM (VirtualBox) with Ubuntu as Server
- Firefox Browser
 -ELN Chemotion; Export VM: 1.8.1, import both the original user on same Server and also a second VM with Chemotion 1.8.2

**Comment by cllde8** [comment]
Hi @MichaelOCI 

Thank you for bringing up the issue and providing the details. I will provide updates on the progress [here](https://github.com/LabIMotion/labimotion/issues/11).

Best regards,
Claire

**Comment by cllde8** [comment]
Closed. Please refer to the update at [LabIMotion#11](https://github.com/LabIMotion/labimotion/issues/11) for details.
