### ISSUE TITLE
Generation of report hangs if the sample or one of the samples is part of reaction equation

### ISSUE THREAD

**Issue by MichaelOCI** [ComPlat/chemotion_ELN#1806]
- I am an ELN admin

# Expected Behavior

A report should be generated even if one of the samples is part of a reaction equation.

# Current Behavior

If one tries to generate a report, that includes at least one sample, that is also part of a reaction equation the preview shows all samples and reaction if both samples and reaction are selected for report generation.

- trying to generate a report for only one sample and no reaction and the sample shows the reaction icon in the samples list no report is generated
- trying to generate a report for multiple samples and no reaction and at least one of the samples shows the reaction icon in the samples list no report is generated

The Generate button turns red during processing and reverts back to blue. the button "processing the report please wait" is never replaced by the download button

Also if the commenting feature is activated and one tries to generate a report for a sample or reaction that includes a comment the generation of the report apparently takes longer (just a gut feeling after exporting one reaction without comment, adding a single word comment to the reaction to test the difference and generating a report again)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - Server Ubuntu
 - Firefox Browser 
 - ELN two test VMs with Chemotion ELN 1.8.2 and our production server also 1.8.2

**Comment by PiTrem** [comment]
The issue about generating the report should be resolved with [v1.9.0](https://github.com/ComPlat/chemotion_ELN/blob/main/CHANGELOG.md#v190)  (resolved with #1835)

Please reopen if the problem persists.

We are looking at the comment impact on lattency in a separate issue.
