### ISSUE TITLE
Yield calculations when purity of sample is not 1

### ISSUE THREAD

**Issue by HSimek** [ComPlat/chemotion_ELN#1809]
- I am an ELNer (ComPlat)

Depending on the use case, the purity of the sample is not taken into account when calculating the yield. 
For example: maximum mass of the product is 100 mg, but I have isolated 105 mg and confirmed purity of 70%. If I enter the purity 0.7 to the sample and then enter 105 mg in the table, I still get an error message that the yield is over 100%, although it is actually 73.5% if the purity is taken into account.

**Comment by PiTrem** [comment]
resolved with https://github.com/ComPlat/chemotion_ELN/pull/1904
