### ISSUE TITLE
User Feedback: advanced search for temperature or time

### ISSUE THREAD

**Issue by FabianMauz** [ComPlat/chemotion_ELN#1815]
A user noted:

searching for temperature 21 °C or duration 48 h never finished - the gear is stirring but doesn't come to an end .

**Comment by FabianMauz** [comment]
Part 2: Advanced search for temperatures of reactions

Temperatures in reactions are saved in a json column. It is structured : 
`{"data": [ ... ] , "userText": "34", "valueUnit": "°C"} `

In the advanced search the userText is used in a sql query and casted to float if not empty.

But as the value of "userText" is a free text in the ui, a user can enter everything into it. This leads to a crash at the casting.

**Comment by PiTrem** [comment]
resolved with https://github.com/ComPlat/chemotion_ELN/pull/1816
