### ISSUE TITLE
register newer scifinder token fails due to browser strict policy

### ISSUE THREAD

**Issue by PiTrem** [ComPlat/chemotion_ELN#1817]
# Expected Behavior

- as a user
- when my scifinder token has expired /is missing
- I can register scifinder token to the ELN

# Current Behavior

- as a user 
- when my scifinder token has expired /is missing
- I can *not* register scifinder token to the ELN

## Steps to Reproduce

- as a signed-in user
- when I go to my **Account & Profile** page (`/pages/settings`)
- when my scifinder token has expired /is missing
- when I press `Get Token`  in the **SciFinder-n Credential** section 
- when I login to my CAS account and get redirected to the ELN
- => 500

## Context

 - ELN version v1.8.x  **with scifinder creds**
- :red_circle: did not work with chrome 122.0.6261.94
- :green_circle:  working with firefox 123.0.1

**Comment by cllde8** [comment]
After confirming with the user, this issue has been resolved and can now be closed. The function has been verified to work correctly for the following Chrome versions (patch number for 122.0.6261):

- Chrome 129 (user's version)
- Chrome 113 (user's version)
- Chrome 94

Additionally, a video demonstration has been provided to confirm the functionality on Chrome 94.

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.03.14-13_23_29.webm](https://github.com/ComPlat/chemotion_ELN/assets/42910431/3e57f954-a34f-47b1-ac6a-e27cf2e9c725)
