### ISSUE TITLE
Reactions - Purification solvents - Incorrect calculation of volume ratio

### ISSUE THREAD

**Issue by schatzsc** [ComPlat/chemotion_ELN#1825]
In the "Reaction" tab, subsection "Purification solvents" a binary mixture was entered and the volumes given as 8 mL for solvent A and 92 mL for solvent B. However, as shown in the screenshot below, the "vol(ume) ratio" is incorrectly calculated as 80% to 920%

![Chemotion purification 180324](https://github.com/ComPlat/chemotion_ELN/assets/88166560/9e4343cf-21ab-47b7-a3af-9b42273bb391)

Furthermore, non-standard acronyms like "DCM" are strongly discouraged and should be changed to "dichloromethane"

**Comment by nicolejung** [comment]
Thanks! Needs to be corrected
