### ISSUE TITLE
Strange texts are appearing when a sample is created using ChemDraw JS

### ISSUE THREAD

**Issue by TasnimMehzabin** [ComPlat/chemotion_ELN#1855]
- I am an ELNer
- I am a developer

# Expected Behavior

When we create a sample using ChemDraw JS, we are able to view the structure image properly

# Current Behavior

Currently the structure shows some additional gibberish text in the image. And when such a problematic sample is used in the reaction, then it does not appear in the reaction SVG as well.

## Steps to Reproduce

1. Create a new sample
2. Use the ChemDraw JS editor to draw it
3. And same the sample. Then you will be some gibberish texts in the sample structure
4. When such a problematic sample is used in the reaction, then it does not appear in the reaction SVG as well

## Context

- ELN v1.9

## Failure Logs / Screenshots

![image](https://github.com/ComPlat/chemotion_ELN/assets/8912580/de6a02e8-ec28-4fb5-9979-040e10a20ab6)

https://github.com/ComPlat/chemotion_ELN/assets/8912580/37ba3409-f3a8-485b-b69f-e992b3fecb5f

**Comment by cllde8** [comment]
Upon investigation, the issue is not related to the ChemDraw editor. It may be due to some SVG-related changes in ELN 1.9.0, where the sample SVGs were subsequently modified. (ELN 1.8 works fine.)
