### ISSUE TITLE
LabIMotion Change unit for minute in field type datetime range

### ISSUE THREAD

**Issue by AnnettNFDI** [ComPlat/chemotion_ELN#1872]
- I am an ELNer / developer / system/ELN admin

# Description
1. In LabIMotion the unit for duration when selecting the field type "datetime range" can be switched to s/m/h/d
2. "m" for minutes is not an official unit. This should be changed to "min". Alternatively, it could have the same design as the datetime range used in the element reaction or the datetime range in the element reaction should be changed to just give the units (s, min, h, ...) instead of wording (second(s), minute(s), ...).

# Image

Screenshot from current LabIMotion used in Chemotion ELN v 1.8.2

![grafik](https://github.com/ComPlat/chemotion_ELN/assets/84778300/1ab4836b-01c4-47c6-a071-882433a8bbb8)

Screenshot datetime range in element reaction

![grafik](https://github.com/ComPlat/chemotion_ELN/assets/84778300/f1d63e26-d38c-44cf-8f07-cbf94fad45f9)

**Comment by nicolejung** [comment]
... to be discussed. We are aware of the difference to official units but changed it in the UI (from "min" to "m") as the addition in particular to tables is problematic with respect to the UI in the case of min or minutes

**Comment by cllde8** [comment]
Dear @AnnettNFDI, 

Thank you for your feedback regarding the field type "datetime range" in LabIMotion. We're pleased to inform you that we have an update to enhance the user experience in [LabIMotion 1.3.0](https://github.com/LabIMotion/labimotion/releases/tag/v1.3.0). In this version, units are now represented as follows: "sec(s)" for seconds, "min(s)" for minutes, "hour(s)" for hours, and "day(s)" for days. You can see these changes reflected in ELN 1.9.2, which includes LabIMotion 1.3.0.

I've tracked your suggestion at [LabIMotion#24](https://github.com/LabIMotion/labimotion/issues/24). If you have any further questions or suggestions, please don't hesitate to reach out to us at https://github.com/LabIMotion/labimotion/tree/main.

Thank you for your help in improving the system.

Best regards,
Claire
