### ISSUE TITLE
picture annotation in a dataset 

### ISSUE THREAD

**Issue by SylviaVanderheiden** [ComPlat/chemotion_ELN#1900]
- I am an ELNer

ich wollte im Repo (auch im ELN probiert) GCMS Bilder einfügen und danach Peaks markieren. 

- Ich kann die Anntotation durchführen, es wird aber nichts gespeichert, wenn ich in der Analytik für die Reaktion bin. 

- In Analytik für Produkte/samples werden die Annotationen gespeichert 
             - Preview scheint im kleinen Bild die Annotation zu enthalten
             - Clickt man auf den Preview zur vergrößerten Ansicht, sieht man die Änderungen nicht
             - Im Datensatz ist nur 1 File enthalten -  das veränderte (zu,mindest sieht es so aus)
             - Sollte das originale Bild nicht erhalten werden? (beim Download des files kann man auswählen, ob man das Original oder 
             das annotierte Bild herunterladen möchte, aber das ist auf den ersten Blick nicht ersichtlich; erst, wenn man den Download- 
             button nutzt)

- Es wäre super, wenn man auswählen könnte, welches Bild im Preview angezeigt werden soll.

Hier der kleine Preview:
![annotation01](https://github.com/ComPlat/chemotion_ELN/assets/94039752/f7f46ff9-2818-4f05-92f1-ccd02c9c1115)

vergrößerte Ansicht des Previews
![annotation02_enlarged](https://github.com/ComPlat/chemotion_ELN/assets/94039752/fec1e39c-7007-4c95-91bd-a8afba6a6e8a)

**Comment by FabianMauz** [comment]
I could confirm and reproduce the problem in my local environment (ELN).

**Comment by FabianMauz** [comment]
It looks like only the container for products is processed for updating annotations but the reaction is missing.

![image](https://github.com/ComPlat/chemotion_ELN/assets/23172219/745a7fc1-786c-41b3-80bc-c2dd7a1e1549)

**Comment by FabianMauz** [comment]
Fixed the bug with not updating the annotation in reaction.

Still open:

- [ ] Selection of which image (annotated or not) should be visible in analysis
- [ ] Improving visibility that downloading of annotated and original image is possible

**Comment by FabianMauz** [comment]
Two  sequel issues were created to deal with the open points from previous comment: https://github.com/ComPlat/chemotion_ELN/issues/1928 and https://github.com/ComPlat/chemotion_ELN/issues/1927. @SylviaVanderheiden Please feel free to add any other ideas or wishes there. I will mark this issue for now as completed.
