### ISSUE TITLE
New ELN entries with generic element templates cannot be deleted

### ISSUE THREAD

**Issue by AnnettNFDI** [ComPlat/chemotion_ELN#1905]
- I am an ELNer
- I am a developer
- I am a system/ELN admin

# Expected Behavior

It should be possible to delete an ELN entry generated with a generic element template.

# Current Behavior

It is not possible to delete it. The fields to delete or move the element are not active.
It is only possible to delete the entry, if you tick the entry from a generic element together with another entry (like a sample) and delete.

# Failure Information 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - Chrome Browser 
 - Firefox Browser
 - ELN version, or branch, or commit

## Failure Logs / Screenshots

Include any relevant log snippets or files here.

![image](https://github.com/ComPlat/chemotion_ELN/assets/84778300/93b2bcf0-2b0e-461c-9c13-0f4b0871a12c)

**Comment by phuang26** [comment]
It has been fixed in LabIMotion 1.4.0, which is included in ELN version 1.10.0 and later. Therefore, if you have ELN version 1.10.0 or newer, the issue should be resolved.
