### ISSUE TITLE
LabIMotion: System-defined unit Amount of Substance not available in Generic Designer

### ISSUE THREAD

**Issue by AnnettNFDI** [ComPlat/chemotion_ELN#1911]
- I am an ELNer
- I am a developer
- I am a system/ELN admin

# Expected Behavior

Accoriding to the list of system-defined unsit (https://github.com/LabIMotion/labimotion/wiki/Supported-Units-for-System-Defined-Field#amount-of-substance) Amount of Substance (Mol, unit mol, mmol, etc) should be available. Please add to the list

# Current Behavior

Amount of Substance ist not in the list of system-defined fields. (see screnshot)

# Failure Information 

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - Chrome Browser 
 - Firefox Browser
 - ELN version, or branch, or commit

## Failure Logs / Screenshots

![grafik](https://github.com/ComPlat/chemotion_ELN/assets/84778300/bad08994-1f98-4c30-9be2-d76a3bcdbe4f)

**Comment by cllde8** [comment]
Dear @AnnettNFDI,

Thank you for bringing up the issue and providing the details. I've created an issue [here](https://github.com/LabIMotion/labimotion/issues/26) and will provide updates.

Best regards,
Claire
