### ISSUE TITLE
Dozens of Ketcher2 error messages

### ISSUE THREAD

**Issue by martin-held-hereon** [ComPlat/chemotion_ELN#1929]
- I am an ELNer
- I am a system/ELN admin

# Expected Behavior

No Ketcher2 error messages

# Current Behavior

Ketcher  2 editor (ketchersvc) throws dozens of error messages (~40). After removing all of them, one can use the sample and edit the molecular structure:

![grafik](https://github.com/ComPlat/chemotion_ELN/assets/91550882/508a7c09-e84e-41b5-8131-a3a60e794bd3)

![grafik](https://github.com/ComPlat/chemotion_ELN/assets/91550882/bd5875f5-35a5-4962-afa1-6c76b1110c84)

# Failure Information 

1)	Error messages appear with Chemotion 1.9.2 (Hereon instance) and 1.9.3 (KIT-hosted instance for Hereon). Since it happens on 2 different instances, it’s not related to the specific instance or our Kubernetes container orchestration
2)	We tested Ketcher 1.9.2 and 1.8.2. on the Chemotion 1.9.2 Hereon instance. Same problem, so it’s not Ketcher.
3)	When turning Ketcher 2 off, the problem disappears, regardless of the instance. So it is merely Ketcher 2 that causes the error messages.
![grafik](https://github.com/ComPlat/chemotion_ELN/assets/91550882/79d64a4d-80dc-44b5-8056-2c6a4974110d)

## Steps to Reproduce

Open any sample.

**Comment by FabianMauz** [comment]
Hi @martin-held-hereon . I could reproduce the problem at our testing instance. We will have a look into this.  Thanks for reporting and have a nice day

**Comment by PiTrem** [comment]
Hi @martin-held-hereon 

- the KIT provided instance is `fixed` (@harivyasi )

- there is a `typo` in the config/structure_editors.yml.example:
the key that defines the assets path for the editor is `extSrc` as described properly in the [docs](https://chemotion.net/docs/eln/install_configure/configuration?_highlight=ketcher2#setup)
However in the config/structure_editors.yml.example the key currently set is [extJs](https://github.com/ComPlat/chemotion_ELN/blob/main/config/structure_editors.yml.example#L17) which is wrong. 

In the current eln docker image, it seems the file is there. One can correct it in the app volume, or overwrite it using the shared/pullin directory.

(Also for the editor to load, the editor files should be present at the designated location. we currently do not ship with ketcher2 but that will change)

**Comment by martin-held-hereon** [comment]
We did the manual fix and that solved the issue. Thanks!
