### ISSUE TITLE
Add storage temperature and expiration date to inventory tab

### ISSUE THREAD

**Issue by BenjaminGolub** [ComPlat/chemotion_ELN#1976]
- I am an ELN admin

# Description
It would be useful to have a field for the "storage temperature" and the "expiration date" of a chemical in the inventory tab. 

Another great enhancement of the inventory would be, if the users got some kind of notification if they add a sample from the inventory with an expired expiration data to a reaction. Or maybe the name of the sample is turning "red" or something like this. I am aware, that the last step is probably harder to do. But adding the two fields "storage temperature" and "expiration date" without any further notification would be very beneficial for us at TU Braunschweig.

**Comment by pychavant** [comment]
I am ELN dans Inventory administrator.
I agree, storage temperature and expiration date are a good idee
