### ISSUE TITLE
DCM as default solvent

### ISSUE THREAD

**Issue by HSimek** [ComPlat/chemotion_ELN#1979]
DCM is missing in the list of solvents in the reaction table (it was there before). Searching by its IUPAC name, dichloromethane, also does not give results, it can only be found by searching for its second name, methylene chloride. 

It would be great if DCM was taken back into the default solvents list - would be great if it would appear in the list as dichloromethane (DCM) so that one can search for both IUPAC name and the abbreviation, and if only DCM appeared in the reaction scheme (the same as for DMSO or THF).

**Comment by PiTrem** [comment]
will be fixed

in the meantime you can try your luck with 

`Methylene chloride` :

**Comment by DianaH583** [comment]
solvent label changed to Dichloromethane (DCM)
