### ISSUE TITLE
Using Reaction Variation leads to buggy display 

### ISSUE THREAD

**Issue by BenjaminGolub** [ComPlat/chemotion_ELN#2000]
- I am a ELN admin

# Expected Behavior

The detail view of the reaction has a blue bar (on top). This bar should be dark blue in case very changes are stored. It switches to light blue in case some unsaved changes are in this tab. So if I just view a reaction, without changing anything, the top bar should always stay dark blue. 

# Current Behavior

When I add the "variation" tab to the reaction detail view, then the dark blue bar on top, will constantly change to light blue, even if nothing has been changed (see video below). As soon as I hide the "variation" tab again, the blue bar stays dark blue as expected. When working with "variation" this is confusing and slightly annoying. 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a reaction and add enable the "variation" segment
2. Store the reaction and open another element in the ELN (another reaction or sample)
3. Open up the reaction again and the dark blue bar on top will change to light blue
4. If you disable "variation" again and do the same thing, the blue bar on top will stay dark blue

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: Windows 11
 - Chrome Browser 
 - ELN version: v1.9.3

## Failure Logs / Screenshots

https://github.com/ComPlat/chemotion_ELN/assets/107389350/d589cf3c-7cea-4954-9f4a-fc47f18f7e7b

**Comment by JanCBrammer** [comment]
Thanks for the issue @BenjaminGolub! I'll look into it.

**Comment by JanCBrammer** [comment]
@BenjaminGolub, I could reproduce and fix the issue. We'll let you know when the fix is released.
