### ISSUE TITLE
Links created by dragging an Element on a "Drag Element" field don't work.

### ISSUE THREAD

**Issue by dudechem-rf** [ComPlat/chemotion_ELN#2004]
- I am an ELNer
- I am a system/ELN admin

# Expected Behavior

Clicking on a link that was created after dragging an Element on a "Drag Element" field opens a view of this Element.

# Current Behavior

Nothing happens after clicking.

# Failure Information 

Clicking on links of elements of a generic element template that was already created with an older version of chemotion (can't tell which one exactly) do still (in this exact instance 1.9.3.) work as expected.
It doesn't work anymore with newly created templates or if the "good" template is copied in the generic designer or if it is exported (json) and reimported.
It also doesn't work if the older "good" template is exported and then imported to another server instance of chemotion 1.9.3.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a new generic element template and release and activate it.
2. Create another new generic element template or a new generic segment template with a new layer with a "Drag Element" field in it and release and activate it.
3. Click "Back to MyDB" and choose any collection.
4. Create a new "element of 1." and create a new "element/segment of 2."
5. Drag the new "element of 1." on the "Drag Element" field of 2.  (--> symbol+name of "element from 1." are shown as expected) and click Save.
6. Click on the "symbol+name link" --> nothing happens!

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - Linux Server
 - Windows and Linux (client)
 - Chrome Browser & Firefox Browser
 - Chemotion 1.9.3

## Failure Logs / Screenshots

Include any relevant log snippets or files here.

**Comment by cllde8** [comment]
Dear @dudechem-rf 

Thank you for bringing up the issue and providing the details. I've created an issue https://github.com/LabIMotion/labimotion/issues/31 and will provide updates there.

Best regards,
Claire
