### ISSUE TITLE
Crashloop of container ketchersvc 1.10.2 from dockerhub/ptrxyz under Openshift/kubernetes

### ISSUE THREAD

**Issue by Thomas-Emmler-Hereon** [ComPlat/chemotion_ELN#2208]
Hi,
I have problems starting the container on our openshift/kubernetes system. When trying to start the container, the container is terminated with the following message:

2024-10-10T07:05:14.122Z Ketcher: 🚀 Starting up...
19135 | return e;
19136 | }
19137 | function captureRawStack() {
19138 | const stackTraceLimit = Error.stackTraceLimit;
19139 | Error.stackTraceLimit = 50;
19140 | const error22 = new Error;
^
error: Executable doesn't exist at /.cache/ms-playwright/chromium-1134/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers: ║
║ ║
║ npx playwright install ║
║ ║
║ <3 Playwright Team ║
╚═════════════════════════════════════════════════════════════════════════╝
at captureRawStack (/app/index.js:19140:21)
at captureLibraryStackTrace (/app/index.js:19146:34)
at /app/index.js:59188:67
at _wrapApiCall (/app/index.js:59183:28)
at /app/index.js:64541:37
at launch (/app/index.js:64526:22)
at /app/index.js:77758:42
note: missing sourcemaps for /app/index.js
note: consider bundling with '--sourcemap' to get unminified traces
Bun v1.1.27 (Linux x64 baseline)

From the point of view of our kubernetes admins it is a problem of the container only.
Do you have an idea how to work around this? Unfortunately, the container does not run long enough to enter something in the terminal.

Viele Gruesse
...Thomas

**Comment by PiTrem** [comment]
Hi @Thomas-Emmler-Hereon
 The image for 1.10.3 has been fixed you should pull [ketchersvc-1.10.3](https://hub.docker.com/layers/ptrxyz/chemotion/ketchersvc-1.10.3/images/sha256-afed70487c0cca8777f121199d62276ba1c9de6e7ab120024173678d4dc02c4b?context=explore)

**Comment by PiTrem** [comment]
ok I think the image have been corrected now.
thx @ptrxyz
