### ISSUE TITLE
creation of new segments and elements

### ISSUE THREAD

**Issue by jmasla** [ComPlat/chemotion_ELN#2233]
I created new elements and segments for different experiments. However, after saving them and activating them, they do not appear in my database/dashboard. 
I am grateful for any tips!

**Comment by phuang26** [comment]
Hi @jmasla, once activated, the elements/segments are ready for use. Users should see them in the "Tab Layout" as hidden by default, and they can unhide them if they prefer them to be displayed by default. For more details, please refer to the following documentation:

[Element List](https://www.chemotion.net/docs/labimotion/guides/user/elements/list?_highlight=tab#element-list)
[Tab Layout](https://www.chemotion.net/docs/labimotion/guides/user/segments#tab-layout)

**Comment by jmasla** [comment]
Hey @phuang26, thanks for your answer! I already checked these pages and I had a workshop yesterday on chemotion, where I discussed this issue with the speaker and we both had no idea, what the problem was. It also does not appear in the hidden parts.

**Comment by phuang26** [comment]
Hi @jmasla, we could schedule a meeting to review all the settings together if that would be helpful.
