### ISSUE TITLE
consider using Zenodo to archive releases

### ISSUE THREAD

**Issue by egonw** [ComPlat/chemotion_ELN#339]
It's fairly easy. See https://guides.github.com/activities/citable-code/

**Comment by PiTrem** [comment]
Definitively! Thx for the suggestion. Added to our roadmap.

**Comment by PiTrem** [comment]
New version releases have been tracked by Zenodo since Nov 2017
[10.5281/zenodo.1054135](https://doi.org/10.5281/zenodo.1054134)

**Comment by egonw** [comment]
Awesome! Maybe you can also list the DOIs (as badge or plain text) on the release pages or in the README? Example here: https://github.com/cdk/cdk/releases/tag/cdk-2.1

**Comment by PiTrem** [comment]
Done (Put it in the release description ). Will also be added to the Readme too. Thx
