### ISSUE TITLE
provide easy to reuse Docker image via DockerHub

### ISSUE THREAD

**Issue by egonw** [ComPlat/chemotion_ELN#340]
I found https://hub.docker.com/r/complat/chemotion-runner/ but I am not sure if that is the Docker for the ELN. Some documentation on DockerHub would be welcome, if it is.

**Comment by PiTrem** [comment]
This was used for pipeline testing. It is not really suitable for development.
We 'll provide another image with documentation (possibly this month).

**Comment by PiTrem** [comment]
Here the link for the pseudo (https not enforced) production image:

https://hub.docker.com/r/complat/chemotion_eln/
