### ISSUE TITLE
Chemotion on Windows Server

### ISSUE THREAD

**Issue by shekfeh** [ComPlat/chemotion_ELN#348]
Thanks for the great software. IF I want to install chemotion on windows, is it only possible by using Docker?

**Comment by CamAnNguyen** [comment]
Hello @shekfeh, thank you for your interesting about our project. Technically, you can use the Docker installation on Windows. As far as I know, `Docker for Windows` currently support on Windows 10 (Windows 10 Pro, Enterprise and Education from 1607 Anniversary Update, Build 14393 or later) and Window Server 2016. I am not sure about `Docker Enterprise Edition` for Window Server 2016 but it should work without any problem. 

With Docker installation please make sure you follow the `BASIC SETUP` part of our `INSTALL.md` file.

If you have any further problem with your setup please let us know, I am happy to support you with that. 
Sorry for my late replying.
