### ISSUE TITLE
chemotion_ELN yield calculation

### ISSUE THREAD

**Issue by RealLemberg** [ComPlat/chemotion_ELN#368]
Hello,
I’m using chemotion_ELN, Version: 0.6.0.
Recently I realized that for some reaction the yield is not calculated properly. For example in a condensation reaction, there the ratio between the components is 2:3 (1:1.5). Theoretical yield of the product is calculated based on the assumption, that ration between ref. starting material and product is 1:1, but in the described case it is 2:1. May be there is a work around for this problem, but I did not find out how to do this.

**Comment by nicolejung** [comment]
Thank you very much. Could you please add an image of the reaction (scheme)? We will have a look if there is a fast solution for the problem

**Comment by RealLemberg** [comment]
> 
> 
> Thank you very much. Could you please add an image of the reaction (scheme)? We will have a look if there is a fast solution for the problem

Sure, here it is:
![reaction](https://user-images.githubusercontent.com/73289912/97043574-fb35e380-1572-11eb-98c6-d253174fd1d2.GIF)

**Comment by nicolejung** [comment]
<img width="597" alt="Screenshot (818)" src="https://user-images.githubusercontent.com/7559189/97081632-fa00c700-1603-11eb-8e7f-5ff9e8b09aa9.png">
Does a scheme such as the attached one solve your problem? At least to gain the correct yield, this is the solution we recommend to users with similar challenges

**Comment by RealLemberg** [comment]
Hello,
yes, it solves the problem, thank you!  I am just wondering if it would be possible in the future version (if any planned) to add an  option, allowing the user to change the yield equivalents? Would be more convenient, I guess…

**Comment by nicolejung** [comment]
Yes, we are planning further improvements and also the rework of the reaction scheme and table options including also multistep reactions and text-in-scheme. At the moment we are busy to include additional functions for other sub-disciplines in chemistry.... therefore, to be realistic, the rework of the existing functions can only be gained in the medium term. However, every input is highly welcome and we collect the user requirements for our further developments. Therefore: thanks a lot for the contribution here :-)
