### ISSUE TITLE
Install script issue

### ISSUE THREAD

**Issue by j-becker** [ComPlat/chemotion_ELN#369]
Hello!

I am trying to install chemotion on Ubuntu Server 20.4 (fresh install with no additional packages) following the instructions in INSTALL.md. The script stops at the following step and does nothing anymore:

```
00:04 npm:install

      01 /tmp/chemotion/nvm-exec.sh npm install --production --silent --no-progress

      01 Now using node v12.18.3 (npm v6.14.6) 
```
I am a bit lost how to look for the problem. Any help would be appreciated.

**Comment by NRayya** [comment]
Hello @j-becker,
During the last year the installation process and its documentation were improved a lot. If you are still interested, please refer to the [documentation](https://www.chemotion.net/chemotionsaurus/docs/eln/native_installation) to find the right installation (native/docker, production/development). If you still face any issues, we would be thankful if you report them in a new issue.

**Comment by NRayya** [comment]
Closing issue: issue about deprecated installation guidelines.
