### ISSUE TITLE
Script install issue

### ISSUE THREAD

**Issue by Grosmon** [ComPlat/chemotion_ELN#373]
Hi !

I am very interested to test chemotion in my lab, but before installing it on our servers, I tested the installation on a VM (Ubuntu Server 18.04) using the corresponding script. Everything runs smoothly until deploy in part 8, where I get an error that seems related to the absence of datacollector.yml config file in the corresponding  /var/www/chemotion_ELN/releases directory, ending the script (I have run the script a second time with the same result).
Would you have any hint to how I can fix this problem ?

Thanks !

![11_12_2020_20_45_09](https://user-images.githubusercontent.com/64079049/101959572-d9b5b780-3c05-11eb-9cac-15109c3ac8ff.png)

**Comment by Grosmon** [comment]
Sorry for the trouble, I found what caused the problem (totally unrelated to my previous assumptions).
I only didn't allocate enough ram to the VM, causing node to crash during the deploy.

**Comment by nicolejung** [comment]
Dear Grosmon, thanks for the feedback on the issue. Please let us know if your installation works or if you face other problems. Also feedback on successful installations helps us. If there are questions with respect to the use of the ELN, feel free to contact us: https://www.chemotion-repository.net/home/contact
