### ISSUE TITLE
Install script failed at capistrano deploy

### ISSUE THREAD

**Issue by Grosmon** [ComPlat/chemotion_ELN#374]
Hello !

I am trying to install chemotion on a server with a fresh install of Ubuntu 18.04 but I get an error during the capistrano deploy ending the script :
```
00:04 deploy:check:linked_files
      ERROR linked file /var/www/chemotion_ELN/shared/config/datacollectors.yml does not exist on localhost
```
This error might be related to [this recent commit](https://git.scc.kit.edu/ComPlat/chemotion_eln_server/-/commit/2f5ddb47ca15e0c1a1f352e382ec6a7668b3d8a9). Would it be possible to add an empty datacollectors.yml file in the config folder without repercussions on the install ?

Thanks !

**Comment by PiTrem** [comment]
Hi,

you are right this commit is the cause. It had been inadvertently pushed to this branch but has been now removed.

**Comment by Grosmon** [comment]
Thanks for the fix, the script ran smoothly and all works well. Can't wait to use it !
