### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by anlancx** [ComPlat/chemotion_ELN#375]
when i installed the chemotion _ELN, An error has occured: curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
How can i solve this problem？
thanks！

**Comment by xgui3783** [comment]
were you using the script or docker to install?

What is your OS?

error seems to suggest that it cannot make secure connection with github, github could have been a connection hiccup. Perhaps try again a little later?

**Comment by PiTrem** [comment]
Were you running the sh installation script and if yes  did it happen around the NVM installation step?

**Comment by anlancx** [comment]
> Were you running the sh installation script and if yes did it happen around the NVM installation step?

Thanks，the problem  has been solved through https://github.com/hawtim/blog/issues/10

but a new problem occurs, here is the error: An error occurred while installing rdkit_chem (2020.04.30.1), and
Bundler cannot continue.
![image](https://user-images.githubusercontent.com/74949047/108833897-66b6bd00-7608-11eb-84ba-f456c25c1ea8.png)
 
thanks!

**Comment by xgui3783** [comment]
I don't know a huge amount of ruby, but it seems the error might have occurred when the script tries to install 

https://github.com/CamAnNguyen/rdkit_chem

but failed at 

https://github.com/CamAnNguyen/rdkit_chem/blob/master/ext/rdkit_chem/extconf.rb#L27 

ENOENT is usually file/directory not found. 

Are there more errors before your terminal printout?

**Comment by PiTrem** [comment]
can you tell what system you are using?

**Comment by anlancx** [comment]
> can you tell what system you are using?

on Ubuntu 20 with VirtualBox

**Comment by anlancx** [comment]
> can you tell what system you are using?

on Ubuntu 20 with VMware

**Comment by PiTrem** [comment]
I have been testing the installation process again, I would recommend to have at least 2 CPU and 3GB for the installation

**Comment by NRayya** [comment]
Hello @anlancx 
During the last year the installation process and its documentation were improved a lot. If you are still interested, please refer to the [documentation](https://www.chemotion.net/chemotionsaurus/docs/eln/native_installation) to find the right installation (native/docker, production/development). If you still face any issues, we would be thankful if you report them in a new issue.

**Comment by NRayya** [comment]
Closing issue: issue about old installation process.
