### ISSUE TITLE
Install issue on Ubuntu 20 with VirtualBox [macOS 10.13.6]

### ISSUE THREAD

**Issue by houdini69** [ComPlat/chemotion_ELN#376]
Tried to install Chemotion on Ubuntu 20 with VirtualBox using chemotion_ELN_install.sh script. Got error at PART 8 (see snapshot)
![Erreur initiale installation Chemotion Ubuntu 20 Virtualbox](https://user-images.githubusercontent.com/24533104/108818612-ebc6b580-75b9-11eb-8a96-307b37820ee9.png)

**Comment by PiTrem** [comment]
Hi,

Was there any explicit 'error' in the ouput ? From the excerpt I can only see the warning, which I also usually get, and I assume openbabel was still being compiled. That compilation can take time depending on the available resource.
You could monitor in parallel the resource consumption and running processes using, for an example, htop. This will help you telling whether the installation is still running or not.

**Comment by houdini69** [comment]
thanks for the tip about htop!

**Comment by houdini69** [comment]
Tried again to install it after removing /var/www/chemotion_ELN but got "Using /home/production/.rvm/ruby-2.6.6" with nothing else even after 2 hours. htop isn't informative at all.
![screenshot](https://user-images.githubusercontent.com/24533104/108841563-40792900-75d8-11eb-9d70-9dcac689091e.png)

**Comment by PiTrem** [comment]
can you give a few lines more bfore the last output. 
Did the installation stalled around the same step?
Also it could help to crank up the resource of the VM just for the installation.

**Comment by houdini69** [comment]
Tried to reinstall using Ubuntu Server with increased allocated RAM (2 Go) but got this error,
![Screenshot](https://user-images.githubusercontent.com/24533104/108991257-2acb3880-7698-11eb-8321-5071adfd223d.png)

**Comment by houdini69** [comment]
This error is reproducible in my case...

**Comment by PiTrem** [comment]
I am testing the installation process again ...

⏳

**Comment by houdini69** [comment]
I was able to install vm template v20200313 on VirtualBox. Will try to connect tomorrow to chemotion ;)

**Comment by PiTrem** [comment]
I have tested the installation with different resource settings. I would recommend to have at least 2 CPUs and 3GB memory for the installation process. (I will update the installation notes.)
I will  provide a more  up-to-date VM too.

**Comment by houdini69** [comment]
I logged in to chemtion without too much trouble.
I've found it's possible to import samples to collection in chemotion. What is the accepted format? We're using open enventory till now and want to import our chemical's database in Chemotion for testing...

**Comment by PiTrem** [comment]
mdl-sd file format can be imported and the import allows a limited mapping for other fields.

Do yo have a list of fields you specifically need to be imported?

**Comment by houdini69** [comment]
We don't have a particular list of fields to import but mainly chemicals names, the related bottles and the corresponding amounts.

**Comment by PiTrem** [comment]
**xlsx** file format is another option with the first row for the headers: smiles (mandatory), name, real_amount_value, real_amount_unit  (mol or g), description, location

**Comment by NRayya** [comment]
Closing issue: installation was done.
