### ISSUE TITLE
Cosmetics: ActionController::RoutingError (No route matches [GET] "/favicon.ico")

### ISSUE THREAD

**Issue by sneumann** [ComPlat/chemotion_ELN#381]
While there is a favicon in:
https://github.com/ComPlat/chemotion_ELN/blob/development/public/favicon.ico
included from:
https://github.com/ComPlat/chemotion_ELN/blob/8e2e507f5e2ec0e04aa02295a1a2b5f72082ca9b/app/assets/javascripts/components/ChemrepoLabels.js#L13
I get the message 
```
[FATAL]:  | ActionController::RoutingError (No route matches [GET] "/favicon.ico")
```
and no favicon. Mon dieu, I can't live without the favicon !
Unfortunately I am no ruby hacker, so no PR to fix this today :-(
Yours, Steffen

**Comment by PiTrem** [comment]
should be solved with 8a667ccbc4804cd911b18ab4d5f3f9fdc35e8039
