### ISSUE TITLE
Improved yield calculation for reactions including e.g. dimerization

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#387]
Reactions that include the consumption of 2 equiv of starting material (of reagent) for the generation of 1 formal equivalent of product are at the moment entered via a work-around: 1 equiv of the material is set as starting material, 1 equiv added as reagent. If would be nice to adapt this process: e.g. 
- offer a check box for "set stoichiometry"
- if checked, allow the user to enter a number indicating that the material is consumed in an so far not considered manner
- adapt yield calculation according to the number given in the stoichiometry entry field (if stoichiometry is 2, then yieldx2 etc).

**Comment by nicolejung** [comment]
Additional related request: add stoichiometry for products to reflect the adaptation of the yield for conproportionation

**Comment by PiTrem** [comment]
this is being worked  in https://github.com/ComPlat/chemotion_ELN/issues/544
