### ISSUE TITLE
Tabs in reaction interface are hidden by default

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#392]
# Expected appearance 

To have all the tabs shown by default

# Current appearance 

Only Scheme tab is shown, other tabs need to be dragged and dropped to appear.

## Steps to Reproduce

1.  Create a new reaction or open an already existing one.
2.  Click the tabs layout button.
3.  Drag the tabs shown in grey and drop them in the white section (e.g. on scheme tab).
4.  Click out of the tabs layout window.
5.  The reaction interface should refresh and the chosen tabs will appear. 

## Context

production ready - tested in FSU.

## Failure Logs / Screenshots
![github](https://user-images.githubusercontent.com/82588017/114973548-f8acaa80-9e80-11eb-967e-b64788c11ae1.png)

**Comment by nicolejung** [comment]
Thanks a lot for the hint. Actually, we intended to hide the tabs to have the user responsible to select the right ones. At the moment, there are only a few tabs available but we will include several others and then it might look a bit crowded (the options given in the selection box will also be rearranged probably in form of a list). But a good approach would probably be to include that into the documentation in the section "first steps". The user then needs to configure the individual view on the ELN and knowns how to adapt that. Does that make sense?

**Comment by NRayya** [comment]
Thanks for your comment. 
I agree with you on the list thing, it makes a lot of sense, and actually I had to mention this point mainly because of the drag and drop thing, it seems inconvenient, so maybe if it could be replaced by one mouse click?

**Comment by NRayya** [comment]
The tabs now are organized in a list and much better looking
