### ISSUE TITLE
Collections Interface Improvement

### ISSUE THREAD

**Issue by PythonFZ** [ComPlat/chemotion_ELN#394]
Using Version 0.7.1

The Collections Tab has a black selection bar
![image](https://user-images.githubusercontent.com/46721498/116215381-ea477400-a747-11eb-8055-9feaa938182f.png)

and the `update` button is not intuitive to use to **save**.

Also, if you add a subcollection it immediatly appears on the navigation, but dissapears again, when `update` is not beeing pressed.

Maybe add a warning of unsaved changes if leaving the collection settings.

**Comment by Allenskywalker92** [comment]
solved with eeacb34720bf6ace1e9ad64cf2a58d822ca34821
