### ISSUE TITLE
alignment in analysis section

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#397]
I would be great if you could change the layout of the analysis section in the part attachments: dependent on the  availability of a preview, the content of the layout is a bit shifted: could you place the preview on the right side of the panel (that the text part is not affected by the availability of the image)? (-> or a better solution if there is any)?
<img width="1067" alt="Screenshot (1119)" src="https://user-images.githubusercontent.com/7559189/116798070-6e08b400-aaec-11eb-805e-e7db8bfa362a.png">

**Comment by cllde8** [comment]
taken & finished

**Comment by cllde8** [comment]
@nicolejung Hi Nicole, this feature is released in v0.9.0. Could we close this issue?

**Comment by nicolejung** [comment]
Yes, thanks a lot!
