### ISSUE TITLE
Generic segment/element

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#398]
It would be great to have the generic element/segment formula field adapted (or another field generated) to be able to work with text instead of integer also. E.g. for the definition of identifers for MOFs, that would be great. E.g. if there is an building block for metals and one for organic compounds and we know the necessary descriptions for that, one could combine this with the formula field working with text. 
Please see the attached picture for the requirements for the identifiers and the other picture for the current plan in ELN generic segment. If one allows to give e.g. "inorganic building block"+"."+"organic building block"+"Format signature"+"catenation"+"topology"+"comment" and creating the string für MOFs with this, this could solve a lot of problems. 

What we would need in addition: being able to combine fields of other layers within one formula (or text-formula) field

<img width="484" alt="Screenshot (1133)" src="https://user-images.githubusercontent.com/7559189/117532643-c4905980-afe8-11eb-9840-abbd926c7fc3.png">
<img width="593" alt="Screenshot (1134)" src="https://user-images.githubusercontent.com/7559189/117532848-e0482f80-afe9-11eb-9db7-f4dd5618caf3.png">

**Comment by cllde8** [comment]
taken & finished

**Comment by cllde8** [comment]
@nicolejung Hi Nicole, this feature is released in v0.9.0. Could we close this issue?

**Comment by nicolejung** [comment]
yes :-)
