### ISSUE TITLE
Upload option in generic element/segment

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#400]
It would be great to have the option to upload a file in the generic segment/element to be stored with the element. The upload function should be given with another input field that can be used for a label (e.g. CIF for MOF or similar). We could use that later on to retrieve information from this data.

**Comment by phuang26** [comment]
This feature has been taken and finished.

**Comment by cllde8** [comment]
Released, please refer to [Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)
