### ISSUE TITLE
Drag sample/molecule in generic segment

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#401]
It would be great if we could have the function "drag molecule" also in the generic segment (perhaps also drag sample but molecule is more important). 
For MOFs, it will then be important to see/copy the InChiKey or Smiles code from the assigned molecule. Sample is probably not that important.

**Comment by phuang26** [comment]
@nicolejung generic segment drag molecule feature has been finished.

**Comment by phuang26** [comment]
@nicolejung Hi Nicole, we have provided the feature "drag molecule" in the generic segment in the latest release version v0.9.0. About "drag sample", it is more complicated so we will hold it for now.

**Comment by nicolejung** [comment]
Yes, let's postpone the "drag sample" issue, thank you.
