### ISSUE TITLE
References in ELN and Repo

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#403]
could you please adapt the new field for literature entries in ELN and Repo? At the moment, the new field describing the meaning of the reference (direct reference or reference from someone else) should be more visible/mandatory. 
Please also add a new type to have three altogether: 
- reference citing exactly this experiment/same authors
- reference citing the experiment done by others
- reference similar experiments or related literature

**Comment by cllde8** [comment]
Hi @nicolejung ,

This feature has been released and deployed to REPO. For ELN, it will be included in the next release.
