### ISSUE TITLE
Markdown Language support

### ISSUE THREAD

**Issue by PythonFZ** [ComPlat/chemotion_ELN#406]
For a more general usage of chemotion the support for mathematical formulars through markdown language (LaTeX math) in (some) text fields might increase the range of possible users.

It could increase the render quality of certain analytics: 

<img alt="formula" src="https://render.githubusercontent.com/render/math?math={}^1\text{H-NMR}%20(400%20\text{%20MHz,%20ppm})%20\delta%20=%202.3,%207.5,%207.6" />

And add the possiblity for many formulas:
<img alt="formula" src="https://render.githubusercontent.com/render/math?math=\hat{F}%20|%20\phi_m>%20=%20\epsilon_m|\phi_m>" />

<img alt="formula" src="https://render.githubusercontent.com/render/math?math=F_i%20=%20-%20\dfrac{\partial%20V(r)}{\partial%20r_i}" />

I think that this could be especially useful with the Research Plan feature.

Some resources I stumbled across:
https://github.com/gettalong/kramdown  // https://kramdown.gettalong.org/syntax.html#math-blocks
https://github.com/vmg/redcarpet

**Comment by NRayya** [comment]
Hello @PythonFZ,

Your suggestion has been discussed and the mathematical functionality will be added to the ELN, but we ask for your understanding that this functionality might take some time. Thanks

**Comment by NRayya** [comment]
Closing issue: Another issue will be opened with more details about the implementation.
