### ISSUE TITLE
Suggestion: move the calendar widget

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#409]
I suggest to move the 2nd calendar widget, so that it's possible to see the selected start date when selecting the end date. Mb just move it below as you have it in the first textbox.

![calendar widget](https://user-images.githubusercontent.com/209056/117993098-b8d1c980-b33f-11eb-94e2-c245ce2cab66.gif)

**Comment by Allenskywalker92** [comment]
solved with 19e497438d60313922c3688f4f1fd388159f8ee8
