### ISSUE TITLE
Suggestion: Swap Discard and Close button

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#410]
When a new analysis is added, a pop-up window opens. Yet the top right buttons are swapped in my opinion. Usually/mostly the "Accept/Ok/Submit" buttons are on the right, but in this one case it's the left one. I suggest to swap the position of the two.
 
I would change this:
![image](https://user-images.githubusercontent.com/209056/117993296-e3238700-b33f-11eb-8ce8-a00c516f639a.png)

Being in line with these:
![image](https://user-images.githubusercontent.com/209056/117993525-1bc36080-b340-11eb-9be8-9c9ac880de24.png)

**Comment by baolanlequang** [comment]
@PiTrem I think we can close this issue because we have the new close button

![Screenshot from 2023-06-21 10-55-18](https://github.com/ComPlat/chemotion_ELN/assets/9006482/59aeb8d3-57d4-4858-9acf-c175c30086df)

**Comment by PiTrem** [comment]
resolved with cc3930d07 v1.9.0
