### ISSUE TITLE
Missing `datacollectors.yml` causes fail of installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by tsufz** [ComPlat/chemotion_ELN#412]
I am setting up a
- [x] production
- [ ] development environment

# Failure Information 

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

I am 
- [ ] using Docker
- [ ] not using Docker 
 
- OS: Ubuntu 20.04 LTS in VirtualBox
- ELN version, or branch, or commit:
- 20210514151554

## Steps to Reproduce

1. step 1
sudo bash ./chemotion_ELN_install.sh

## Failure Logs / Screenshots
** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:

 DEBUG [ced32d0e] Finished in 4.438 seconds with exit status 0 (successful).

  INFO The Gemfile's dependencies are satisfied, skipping installation

  INFO [deploy:migrate] Run `rake db:migrate`

 DEBUG [12f0f6b2] Running if test ! -d /var/www/chemotion_ELN/releases/20210514151554; then echo "Directory does not exist '/var/www/chemotion_ELN/releases/20210514151554'" 1>&2; false; fi as production@localhost

 DEBUG [12f0f6b2] Command: if test ! -d /var/www/chemotion_ELN/releases/20210514151554; then echo "Directory does not exist '/var/www/chemotion_ELN/releases/20210514151554'" 1>&2; false; fi

 DEBUG [12f0f6b2] Finished in 0.041 seconds with exit status 0 (successful).

  INFO [b9ef5ea8] Running /tmp/chemotion/nvm-exec.sh ~/.rvm/bin/rvm 2.6.6 do bundle exec rake db:migrate as production@localhost

 DEBUG [b9ef5ea8] Command: cd /var/www/chemotion_ELN/releases/20210514151554 && ( export NODE_VERSION="v12.22.1" RAILS_ENV="production" ; /tmp/chemotion/nvm-exec.sh ~/.rvm/bin/rvm 2.6.6 do bundle exec rake db:migrate )

 DEBUG [b9ef5ea8]       Now using node v12.22.1 (npm v7.11.1)

 DEBUG [b9ef5ea8]       /home/production/.rvm/gems/ruby-2.6.6/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

 DEBUG [b9ef5ea8]       Could not load configuration. No such file - /var/www/chemotion_ELN/releases/20210514151554/config/datacollectors.yml

  INFO [b9ef5ea8] Finished in 23.493 seconds with exit status 0 (successful).

 DEBUG [a73e14c2] Running if test ! -d /var/www/chemotion_ELN/releases/20210514151554; then echo "Directory does not exist '/var/www/chemotion_ELN/releases/20210514151554'" 1>&2; false; fi as production@localhost

 DEBUG [a73e14c2] Command: if test ! -d /var/www/chemotion_ELN/releases/20210514151554; then echo "Directory does not exist '/var/www/chemotion_ELN/releases/20210514151554'" 1>&2; false; fi

 DEBUG [a73e14c2] Finished in 0.060 seconds with exit status 0 (successful).

  INFO [d870e9d8] Running /tmp/chemotion/nvm-exec.sh ~/.rvm/bin/rvm 2.6.6 do bundle exec rake assets:precompile as production@localhost

 DEBUG [d870e9d8] Command: cd /var/www/chemotion_ELN/releases/20210514151554 && ( export NODE_VERSION="v12.22.1" RAILS_ENV="production" RAILS_GROUPS="" ; /tmp/chemotion/nvm-exec.sh ~/.rvm/bin/rvm 2.6.6 do bundle exec rake assets:precompile )

 DEBUG [d870e9d8]       Now using node v12.22.1 (npm v7.11.1)

 DEBUG [d870e9d8]       /home/production/.rvm/gems/ruby-2.6.6/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

 DEBUG [d870e9d8]       Could not load configuration. No such file - /var/www/chemotion_ELN/releases/20210514151554/config/datacollectors.yml

**Comment by phuang26** [comment]
@tsufz Thanks for your report.

I use the [installation_script](https://github.com/ComPlat/chemotion_ELN/blob/v0.8.0/scripts/install_production.sh) and it works fine (v0.8.0).

My Testing info:

> Server: Ubuntu 20.04.2 LTS (Focal Fossa) 
> vCPU: 4
> RAM: 8GB
> Version: v0.8.0

I have the same log as you provided, include the warning messages (No such file ... datacollectors.yml) on the capistrano.log, as they are warning and will not cause the deployment get failed, in my case, it took around 6 mins from this output (which is the last line of the log you provided) 

`"Could not load configuration. No such file - /var/www/chemotion_ELN/releases/20210517100811/config/datacollectors.yml" `

to the next output

`Writing /var/www/chemotion_ELN/releases/20210517100811/public/assets/manifest-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca49` 

The provided capistrano.log seems okay but not finish yet, what is the message on the installation console?

**Comment by phuang26** [comment]
@tsufz do you have any update on this? or we could close this issue?

**Comment by tsufz** [comment]
@phuang26 Yes, it seams that there is problem with the JAVA heap size now. I will allocate more RAM to the VM and try again.
