### ISSUE TITLE
allow interconvertible units also in the type input group in generic elements/segments/datasets

### ISSUE THREAD

**Issue by PatrickKIT** [ComPlat/chemotion_ELN#413]
It would be great to have the option to change within interconvertible units also within the field type input group. At the moment, the units are defined as label for input group.

**Comment by cllde8** [comment]
@PatrickKIT Hi Patrick, this feature has been finished and included in the release v0.9.1. Could we close it?

**Comment by PatrickKIT** [comment]
@cllde8 Sure, you can close it. Thank you!
