### ISSUE TITLE
table function

### ISSUE THREAD

**Issue by PatrickKIT** [ComPlat/chemotion_ELN#414]
Could you please add a table function to the generic element/segment/dataset to allow the addition of multiple combinations of values (given as multiple lines in the table)?

**Comment by cllde8** [comment]
This feature has been taken and finished.

**Comment by PatrickKIT** [comment]
@cllde8 thank you!

**Comment by cllde8** [comment]
Released, please refer to [Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)
