### ISSUE TITLE
new units

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#415]
Hi all, we need a few new units: 
specific volume: cm3/g
viscosity: Pa*s (interconversion to mPa*s (millipascal*second))
density: g/cm3 (=/interconversion to kg/l)

**Comment by cllde8** [comment]
taken & finished

**Comment by cllde8** [comment]
@nicolejung Hi Nicole, this feature is released in v0.9.0. Could we close this issue?

**Comment by nicolejung** [comment]
Yes :-) thanks a lot!
