### ISSUE TITLE
Open MOL file from Ketcher doesn't work

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#416]
- I am an ELNer
- I am a system/ELN admin

# Expected Behavior

Generate the sample from a MOL file

# Current Behavior

Nothing happens, although the same MOL file works perfectly when its content is copied as input.

## Steps to Reproduce

1. Create new sample
2. Open Ketcher
3. Click "Open" at top
4. From "Input" and "File" choose "File"
5. Press "Choose file"
6. Select a MOL file from your device
7. Press OK.
 
## Context

 - OS: [iOS]
 - Chrome Browser 
 - ELN version: 0.9.0
 - Jena's instance

**Comment by Allenskywalker92** [comment]
solved with df6a85ab752350faba17eb63c6fea9850f1e61d3

**Comment by NRayya** [comment]
Close issue: Merged, released and tested by users.
