### ISSUE TITLE
Nothing exported when exporting collections

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#417]
- I am an ELNer
- I am a system/ELN admin

# Expected Behavior

Have an exported collection as a zip file

# Current Behavior

The user receives a notification saying this will take a while, and then not sure if nothing happens or that it takes days to finish.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. From the toolbar, press the importing/exporting button shown in the image.
2. Select "Export collections"
3. Select a collection to be exported
4. Press "Export ZIP"
5. You will receive a notification, then nothing happens

## Context

 - OS: [IOS]
 - Chrome Browser 
 - ELN version: 0.9.0

## Failure Logs / Screenshots

<img width="1440" alt="export collection" src="https://user-images.githubusercontent.com/82588017/120045826-2f91e680-c011-11eb-8494-5151a9e2dd70.png">

**Comment by phuang26** [comment]
@NRayya Hi Noura, there was an issue on the system configuration and has been fixed already. Could you please try again? Thank you.

**Comment by NRayya** [comment]
@phuang26 Collections can be exported now, thanks.
I will close the issue.
