### ISSUE TITLE
Opening wrong file format with Ketcher: Nothing happens where a message should be given to the user

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#418]
To reproduce:

    Create new sample
    Open Ketcher
    Click "Open" at top
    From "Input" and "File" choose "File"
    Press "Choose file"
    Select any wrong file format (not a mol, sdf, or xml)
    Press OK.
    Press "Save" in Ketcher.

The samples details modal seems to be loading something but nothing happens. Instead, the user should be informed to use the right file format.

**Comment by Allenskywalker92** [comment]
solved with df6a85ab752350faba17eb63c6fea9850f1e61d3
