### ISSUE TITLE
Antiaromatic and non aromatic compounds are classified as aromatic in Ketcher's standard templates

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#419]
In the standard template "Aromatics" at the bottom of Ketcher's editor, the following compounds are classified as aromatic where they are not:

cyclohepta-1,3,5-triene
cyclopropene
cyclobutadiene
cyclooctatetraene

![aromatics](https://user-images.githubusercontent.com/82588017/120165856-46e0f780-c1fc-11eb-8c0e-22272cb192ec.png)

**Comment by NRayya** [comment]
The mentioned elements were destroyed.

**Comment by nicolejung** [comment]
The templates are a suggestion for structures to be used in addition to the available standard core structures in Ketcher. The currently available ones are only a selection of possible core structures. Every admin of an instance can use and adapt the templates according to the preferences of the user community. In cases where the structures and not well-sorted, the admin can organize/change/edit the templates on his/her own.
