### ISSUE TITLE
Ketcher shortcut to clear canvas (Ctrl+n) opens a new window instead

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#422]
Wrong shortcut  (Ctrl+n) is suggested to the user in Ketcher to clear the canavas as it actually opens a new window in both Firefox and Chrome when using Windows 10.
![shortcut](https://user-images.githubusercontent.com/82588017/120392514-e56e7500-c330-11eb-980f-ac6c11c21b64.png)

**Comment by Allenskywalker92** [comment]
Solved with 4e982473af6cfeeff718d2e31277243ad8e157f9
