### ISSUE TITLE
Integration of a TLC drawing tool

### ISSUE THREAD

**Issue by AnnettNFDI** [ComPlat/chemotion_ELN#423]
The integration of a Thin Layer Chromatography Drawing Tool in the analysis section of a reaction would be very helpdful.

**Comment by NRayya** [comment]
This issue is being dealt with through the image annotation issue
https://github.com/ComPlat/chemotion_ELN/issues/490 
And more detailed are found here https ://github.com/ComPlat/chemotion_ELN/issues/565
