### ISSUE TITLE
The permission level "delete" in sharing collections doesn't work and the receiver can't delete

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#425]
- [ ] I am an ELNer
- [ ] I am a system/ELN admin

# Expected Behavior

The receiver of a shared collection with the permission level "delete" should be able to delete samples.

# Current Behavior

The delete button is inactive and the receiver can't delete samples.

## Steps to Reproduce
The first user:

1. From a certain collection, select some samples.
2. Press "Sharing" button from the toolbar.
3. Select "Permission level" as "Delete".
4. Select a user to share the collection with.
5. Press create shared collection.
![share](https://user-images.githubusercontent.com/82588017/120611832-dda7f100-c454-11eb-942c-df6275984d48.png)

For the receiver of the collection (second user):

1. Go to the collection bar to "Shared with me", and pick the collection that was shared.
2. Select a sample from this collection
3. The delete button will not be active (The bug).
![receive](https://user-images.githubusercontent.com/82588017/120612370-69ba1880-c455-11eb-8791-4b958f9bad0c.png)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: Windows 10
 - Chrome Browser 
 - Firefox Browser
 - ELN version 0.9.0, Jena's instance

**Comment by nicolejung** [comment]
Short internal discussion necessary: do we intend the user (assigned to synchronize/share: delete level) to delete samples or only content in the samples?

**Comment by NRayya** [comment]
If the user is only able to delete the content of the sample, isn't this just a modification that is same as "writing"? so it is already provided in the previous permission level.

**Comment by nicolejung** [comment]
I agree.

**Comment by phuang26** [comment]
taken and finished, plan to be included in the next release.

**Comment by cllde8** [comment]
Released, please refer to [Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)
