### ISSUE TITLE
The admins are able to delete generic elements before deleting the corresponding segments in the ELN Administration, and this makes the "Generic segments" section inaccessible

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#426]
- [x] I am an ELNer
- [ ] I am a developer
- [x] I am a system/ELN admin

# Expected Behavior
The admin should be forbidden from deleting a generic element before deleting the corresponding segments, and they should receive an error message, or else delete all the corresponding segments automatically without having the account down. 

# Current Behavior
In my account only, I can't access the "Generic Segment (BETA)" page. When trying to open it, an empty page opens instead.
What is the current behavior?

## Steps to Reproduce

1. As an admin, go "Generic Elements (BETA)", and create a new element.
2. Go to "Generic Segment (BETA)"  and assign new segments to the created element.
3. From "Generic Elements (BETA)", delete the created element.
4. The "Generic Segment (BETA)" will not open now.

## Context

 - OS: Windows 10
 - Chrome Browser 
 - ELN version 0.9.0
![admin](https://user-images.githubusercontent.com/82588017/120688205-1bcc0180-c4a3-11eb-8877-fad8be939275.png)

**Comment by phuang26** [comment]
@NRayya This is a known issue and we've fixed it already; when admin user delete the generic element, the attached segments will also be deleted. The fix will be included in the next release.

**Comment by NRayya** [comment]
Thanks
