### ISSUE TITLE
new units for generic sections

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#434]
Hi all, could you add a few new units to the generic section units? 

-  magnetic flux density/ inductivity | Tesla | T
-  electric field | Volt/Meter | V/m 
-  current | Ampere | A ; mA; µA; nA 

thank you :-)

**Comment by phuang26** [comment]
taken and finished, plan to be included in the next release.

**Comment by cllde8** [comment]
Released, please refer to [Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)
