### ISSUE TITLE
Adding new dataset to the analyses tab of sample can't be discarded

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#435]
- [x] I am an ELNer
- [x] I am a system/ELN admin

# Expected Behavior

Pressing discard button should cancel all the changes.

# Current Behavior

a new dataset is added all the same when pressing discard.

## Steps to Reproduce

1. Go to a sample analyses tab.
2. press "add analyses"
3. scroll down to "datasets" and press the green plus sign.
4. At this point, if you press "close" or "discard" you get the same result (a new dataset), while discard should not result in one.

## Context

 - OS: [e.g. macos]
 - [x] Chrome Browser 

 - ELN version: 0.9.0

## Failure Logs / Screenshots

![discard](https://user-images.githubusercontent.com/82588017/122566085-72127600-d047-11eb-9db2-a72f20dd1327.gif)

**Comment by nicolejung** [comment]
the discard button refers to the attachments, not the dataset, the dataset is deleted with the red bin symbol. 
- open dataset, add file, close (-> dataset is saved with added file)
- open dataset, add file, discard (-> changes in the attachments are not saved, file therefore not added, reopen results in empty dataset)
