### ISSUE TITLE
new units for generic sections

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#436]
Dear all, 

thanks for implementing the new units, I am sorry, I have a request for another one: 
flow rate: µl/min, ml/min, l/m

thank you

**Comment by phuang26** [comment]
taken and finished, plan to be included in the next release.

**Comment by cllde8** [comment]
Released, please refer to [Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)
