### ISSUE TITLE
ELN Adminstration/generic elements: Create a table for drag and drop Sample/Molecule

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#437]
Currently, in the generic elements, the field types "drag sample" and "drag molecule" enable the user to drag only one object and drop it there. It would be great to have those fields as a table (like dragging and dropping samples in the reaction scheme), where adding one object results in the possibility to add another one and so on.

**Comment by cllde8** [comment]
Released, please refer to [Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)
