### ISSUE TITLE
Temp. Chart - Changing time step difficult - 25-200 wrong order of figures in scheme

### ISSUE THREAD

**Issue by CRC1333-Admin** [ComPlat/chemotion_ELN#441]
- [x] I am a system/ELN admin

# Expected Behavior

- Easily changing numbers in the table, NOT only if i mark one single figure and change it, but also if I put the cursor somewhere and then delete from there or just start typing
- If my first step in the table is 25 °C and the second 200°C this should be depicted as 25-200°C in the scheme, NOT 200-25°C (For 25-400°C it is working fine)

# Current Behavior

It is very difficult to change the time (see GIF attached)
![Bug - Temp Chart - Changing time step to 2hrs difficult - 25-200 wrong order of figures in scheme](https://user-images.githubusercontent.com/86300911/123262850-9e6f3c00-d4f8-11eb-9ace-39bad81917a4.gif)

Display of 200-25°C in the scheme

# Failure Information 

It should be 25-200°C and times should be changeable if I put the cursor somewhere and then delete from there or just start typing.

## Steps to Reproduce

see GIF attached

## Context

[x] Chrome Browser 
  Chemotion ELN
Version: 0.8.0
Base revision: 9b86adc3dbf10c16faea6599f327d4ef6d4fbe3d
Current revision: d2ee9f4389486b1dc75ea723e2336486f54e79b1

## Failure Logs / Screenshots
see attached GIF

**Comment by Allenskywalker92** [comment]
solved with cf31c7a7bdd97997e359a97037d1b27682051981
