### ISSUE TITLE
WIP: Due to server configuration issues in FSU, error with exporting collections with attachements

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#442]
- [x] I am an ELNer
- [ ] I am a developer
- [x] I am a system/ELN admin

# Expected Behavior

To be able to export collections of samples with attachments as a zip file.

# Current Behavior

When uploading files to inbox/unsorted folder, and using those files as attachments for the analysis of samples, exporting the collections that contain those samples as zip files becomes not possible even if there is nothing wrong with the file.

## Steps to Reproduce

1. You need an account on https://chemotion.uni-jena.de/
2. upload a file to Inbox/unsorted folder
3. click on a sample, go to the analysis tab.
4. click "add analysis", then in datasets field, drag and drop that file.
5. Try to export the collection containing this sample.

## Context
The issue is related to the server configuration in Jena FSU
 - ELN version: 0.9.0

**Comment by phuang26** [comment]
taken and finished, please check, thank you.

**Comment by NRayya** [comment]
Yes it is working now, thanks
