### ISSUE TITLE
Resizing window does not move popups

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#447]
- [ ] I am an ELNer
- [x] I am a developer
- [x] I am a system/ELN admin

# Expected Behavior

Popups stick to their parent button even upon window resize

# Current Behavior

They are fixed on the page, not relative to the spawning point. Resigin the window makes them "move away".

![image](https://user-images.githubusercontent.com/209056/123419050-13567a80-d5ba-11eb-8228-62166a027618.png)

**Comment by ptrxyz** [comment]
Possible fix:

- Make the button `position: relative`
- Move the `div.popover-layout` into the `button`-node.
- Remove all the `top` and `left` positioning stuff from the element's style
- instead use `translate(calc(-100% - 10px), calc(-50% + 10px))`, as the percentages in `transform` refer to the node's own size and not it's parent (as opposed to the percentages in other properties, such as `width` and `left` etc).
- Profit:
![image](https://user-images.githubusercontent.com/209056/123420598-08044e80-d5bc-11eb-945d-74bfd7f14003.png)

**Comment by PiTrem** [comment]
resolved
