### ISSUE TITLE
Improve reference/literature assignment

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#449]
no bug, only desired improvement: currently, there are two options that can be used as additional information for literature/references (cited by/referring to). The terms should be modified as it is not clear how to use them without further clarification.

**Comment by nicolejung** [comment]
In addition: we keep literature in the samples tab and references in the reactions tabs. Can we use just one term and apply it for both?

**Comment by phuang26** [comment]
Hi Nicole.
There has been some feedback and requests (https://github.com/ComPlat/chemotion_ELN/issues/451) that we think would be very useful to users, so we will deliver them together in the scope of version 1.2.0.

**Comment by cllde8** [comment]
Hi @nicolejung ,

This feature has been released and deployed to REPO. For ELN, it will be included in the next release.
