### ISSUE TITLE
Add "Literature/References" tab to all the elements in the ELN (wellplates, screens, generic elements)

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#453]
The "Literature/References" tab is a very useful feature that is already available for samples and reactions and nice to have for the other elements too.

**Comment by nicolejung** [comment]
see issue #449, two people, one thought... :-)

**Comment by NRayya** [comment]
It is the last issue in the list and I didn't see it, I should see an ophthalmologist :D
