### ISSUE TITLE
Consistency: Enable adding explanatory texts in the fields of generic elements

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#455]
For the original elements (samples, reactions, wellplates, screens), an explanatory texts is shown in gray in the fields, it disappears when writing there:
![image](https://user-images.githubusercontent.com/82588017/123540695-9acdf600-d740-11eb-84b0-77f6ae400204.png)
For the generic elements, the explanation is shown in a window by hovering the mouse over the filed. It is great to have both options available, so it would be great to enable the gray writing for the generic elements too.

**Comment by phuang26** [comment]
We have both options available for some types (e.g. Text), if there are some types you think it's needed, please let us know, thank you.

**Comment by NRayya** [comment]
I thought the placeholder will result in a default value in the field, sorry for the confusion here.

**Comment by NRayya** [comment]
Wrongly reported, should report enabling default values instead
