### ISSUE TITLE
Not all fields work normally with ipad

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#458]
- [x] I am an ELNer
- [ ] I am a developer
- [x] I am a system/ELN admin

# Expected Behavior

To have the ELN working normally on iPad 

# Current Behavior
In the reaction details modal -> scheme -> description: the text that is already added before using the iPad cannot be edited.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: [iPad ]
 - [x] Chrome Browser 
 - [ ] Firefox Browser
 - [x] Safari Browser

Software version: 14.6
Model name: iPad 6 generation
Chrome version: 91.0.4472.80

**Comment by PiTrem** [comment]
Hi @NRayya 

About Safari: Safari is not supported.

About Chrome: 

Can you reproduce the user issue.
Do you confirm the same is working with chrome on other hardware, but not with chrome on a Ipad.
Do you have an example scenario  

screenshot or console.log welcome.

**Comment by NRayya** [comment]
Hi @PiTrem @phuang26 
Here is a link for more details (photos and videos):
https://upload.uni-jena.de/data/60f530102bb2a5.41738017/Ipad_bug.zip

**Comment by phuang26** [comment]
@NRayya Thanks for the information, this issue has been fixed. 
https://bwsyncandshare.kit.edu/s/mZGZgSYBjtdEpn3

**Comment by NRayya** [comment]
Thanks @phuang26

**Comment by cllde8** [comment]
Released, please refer to [Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)
