### ISSUE TITLE
Add samples to generic element in table

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#461]
It would be great to have samples available in the table of generic element (comparable to the molecule function in the table)

**Comment by cllde8** [comment]
This feature has been taken and finished.

**Comment by cllde8** [comment]
Released, please refer to [Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)
