### ISSUE TITLE
Add "undefined structure" as default value for decoupled samples 

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#463]
I am not sure if this was mentioned in another issue but we had this point in one of our meetings: could you add the term "undefined structure" as a default value to the field "sum formula" in the properties tab for samples (save sample would give undefined structure if no change added by the user)? That would help to avoid misunderstandings and will facilitate the process.

**Comment by cllde8** [comment]
This feature has been taken and finished.

**Comment by cllde8** [comment]
Released, please refer to [Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)
