### ISSUE TITLE
remove name in scheme for decoupled sample

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#465]
It would be great if we could remove the name of the molecule from the scheme overview for decoupled samples. The type of polymer/surface is also given, this is perfect and should stay as it is (please see attached image)
<img width="624" alt="Screenshot (1334)" src="https://user-images.githubusercontent.com/7559189/124354421-3ad9c280-dc0c-11eb-9028-27b9980fc33b.png">

**Comment by cllde8** [comment]
This feature has been taken and finished.

**Comment by cllde8** [comment]
Released, please refer to [Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)

**Comment by nicolejung** [comment]
It would be good to have another change here: could you please remove all information with respect to safety information if the decoupled mode is chosen? This information (including the link to pubchem) is not valid for the non-defined structures. 

<img width="619" alt="Screenshot (1537)" src="https://user-images.githubusercontent.com/7559189/134408175-c56ee52d-1f74-4462-8a92-7f679604b53c.png">

**Comment by cllde8** [comment]
This feature has been taken and finished.

**Comment by cllde8** [comment]
Closed, this feature has been delivered as a part of release [v1.0.0-beta](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)
