### ISSUE TITLE
change text size and position in reaction scheme

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#466]
Hi all, could one of you increase the size of the text for samples given with text/name instead of the structure? And if possible align the text with the arrow of the scheme? 

<img width="624" alt="Screenshot (1343)" src="https://user-images.githubusercontent.com/7559189/124514051-71663780-dddc-11eb-927a-dd20ff0b425b.png">

**Comment by adambasha0** [comment]
Fixed. Please refer to https://git.scc.kit.edu/ComPlat/chemotion_ELN/-/issues/1220#note_307037 for more info.
