### ISSUE TITLE
Moving version information to a separate file to be able to track them more easily

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#468]
To improve tracking the current/used versions of npm, nvm, node, ruby, etc between installations/updates and when it comes to build the docker containers, I suggest to move the version information to a separate env-file.

**Comment by ptrxyz** [comment]
To add a bit of context: when it comes to building the docker container, I am not using the `scripts/install_*.sh` scripts which leads to Pierre having to keep me up to date if any versions changed or me having to check the environment constantly.
For that reason, we thought about moving the version information of ruby/nvm/node/... etc to a separate env file: this allows for easy tracking of version changes between releases and updates.

**Comment by Ira-Maier** [comment]
This feature would also be could for GitHub actions!

**Comment by PiTrem** [comment]
https://github.com/ComPlat/chemotion_ELN/blame/main/.tool-versions and https://github.com/ComPlat/chemotion_ELN/commit/b1d05b94c929fcdbc790a9f5280708ce6e78b2a5 should have resolved this
