### ISSUE TITLE
Display customized welcome message at home page. 

### ISSUE THREAD

**Issue by NishaSharma14** [ComPlat/chemotion_ELN#470]
To utilize the blank space at the Home page. Some details can be displayed to user with welcome message. 
The message should be dynamic and can be modified anytime.
The message will be extracted from a .md file. If that file is not present then no message will be displayed.

**Comment by cllde8** [comment]
Released, please refer to [Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)
