### ISSUE TITLE
Enable NMR analysis of for common hetero nuclei like 31P, 29Si, 15N 

### ISSUE THREAD

**Issue by AnnettNFDI** [ComPlat/chemotion_ELN#476]
Spectra editor needs more NMR layouts for common hetero nuclei like 31P, 29Si, 15N etc.. Chemotion choses 13C as layout for the aforementioned nuclei. Consequently, this causes troubles with NMRshiftDB because it tries to retrieve the shift data for the 13C layout.

**Comment by schatzsc** [comment]
Actually, the **NMR spectra editor** should be **totally independent of the particular nucleus used** in the NMR experiments, as in addition to the abovementioned ones, in some fields of chemistry there is also regular use of 2H, 10B, 11B, 77Se, 195Pt and many more, see for example
[](https://www.cup.lmu.de/ac/krumm/site/assets/files/1040/ac_lmu_nmr-frequency-table.pdf)
for only some of the most common choices. It's possibly ok to have 1H, 13C, 19F, 31P as the standard choices offered but user should be able to switch to any other nucleus as well.
Furthermore, it should be taken into account that the **chemical shift range for some of the non-standard nuclei can widely deviated from the normal range** (0-15 ppm for 1H and 0-200 ppm for 13C) For example, in 195Pt NMR, the resonance can appear somewhere between -4000 and +4000 ppm, which usual spectral shift width of 1000 ppm. Also, even in 1H NMR, metal hydrides M-H for example appear in the range of 0 to -5 ppm and paramagnetic 1H NMR can also cover a very wide range of shifts, something like 0-400 ppm (yes, in 1H NMR of high-spin Fe(II) for example). Thus, also **make sure that negative shift values are possible**.

**Comment by NRayya** [comment]
Dear @schatzsc 
Thanks for your comment. At the moment having the NMR spectra editor totally independent of the nuclei could be a little difficult, but I will open new issues about the points you have raised so that the developers team could take care of them as soon as possible.
