### ISSUE TITLE
generic elements, segments and analyses

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#480]
Hi all, is it possible to add a function to the tables in generic sections (user view) to enable the sorting of lines of a table?

**Comment by cllde8** [comment]
This feature has been taken and finished.

**Comment by cllde8** [comment]
Released, please refer to [Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)
