### ISSUE TITLE
Customized welcome email to new user.

### ISSUE THREAD

**Issue by NishaSharma14** [ComPlat/chemotion_ELN#483]
A welcome email should be sent to the new user on sign up/register, which some basic info such as links to documentation, mailing list subscription details, and some guidelines on reporting bugs/request features.
The message should be dynamic and can be modified if required.

**Comment by cllde8** [comment]
Released, please refer to [Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)
