### ISSUE TITLE
Molecule preview gets clipped

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#488]
-  I am a system/ELN admin

# Expected Behavior

Molecule should be visible.

# Current Behavior

It's covered by the following row if the browser's width is below 974px (when the "responsive realignment" kicks in ...).

# Failure Information 

![image](https://user-images.githubusercontent.com/209056/127629720-ae9d946f-5c88-4a9d-b94f-24c5991b784a.png)

**Comment by PiTrem** [comment]
resolved
