### ISSUE TITLE
Image Annotation

### ISSUE THREAD

**Issue by fbroda** [ComPlat/chemotion_ELN#490]
The new feature should provide means to annotate images in research plans, i.e. to highlight spots in thin layer chromatography or bands in agarose gel images. A solution should have at least the following properties:

- the original image data (png, jpeg, tiff, ...) is kept for reference (cf. obligation to keep primary data)
- a preview (png or jpeg) is generated for view mode and for report generation, i.e. displaying the annotated image is computationally cheap
- the solution should not preclude versioning of the research plan
- the used browser plugin must be license compatible to ChemotionELN

The ability to process tiff images is of particular interest to molecular biologists, as some of their equipment produces tiff images that regularly cannot be displayed in browsers.

**Comment by PiTrem** [comment]
resolved with https://github.com/ComPlat/chemotion_ELN/pull/1121
