### ISSUE TITLE
Converter app/client: set identifier function 

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#492]
- [ x] I am an ELNer
- [ ] I am a developer
- [ ] I am a system/ELN admin

# Expected Behavior

using the identifier generation by "metadata" such as file name works
using the identifier generation by "table headers" and giving a line does not work for me. I used the same file for both applications (csv, name cary61). Github does not support it but I can provide it on request to solve this issue

# Current Behavior
Creating the template with the converter app works but the generation of the jdx with the converter client fails (file cannot be processed error)

 - [x ] Chrome Browser 
 - [ ] Firefox Browser
 - ELN version, or branch, or commit

## Failure Logs / Screenshots

Include any relevant log snippets or files here.

**Comment by phuang26** [comment]
taken and finished
