### ISSUE TITLE
font of "Inbox" is serif.

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#498]
- [X] I am an ELNer
- [X] I am a developer
- [X] I am a system/ELN admin

# Expected Behavior

Font of "Inbox" should be sans.

# Current Behavior

It is set to "fontawesome" as the label is inside the `<i> tag`. Moving the label text outside of the tag should fix this.

# Failure Information 

No es bueno.

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/209056/127992598-431ab741-a1d1-4793-b923-dfe301ab16e9.png)

**Comment by NRayya** [comment]
This issue was duplicated here:
https://github.com/ComPlat/chemotion_ELN/issues/573
