### ISSUE TITLE
Element details tab layout: segment tab to show if data present

### ISSUE THREAD

**Issue by PiTrem** [ComPlat/chemotion_ELN#506]
As a ELNer 
Who has set my sample-tabs layout to hide most of the tabs globally 
When I open   sample with  segment data
I want  the tab of the segment to show up
so that I don t have to change the tabs layout

**Comment by cllde8** [comment]
Released ([Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta))
