### ISSUE TITLE
generic element cannot be assigned to/moved to other collection

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#508]
- [ x] I am an ELNer
- [ ] I am a developer
- [ ] I am a system/ELN admin

# Expected Behavior

Please describe the behavior you are expecting

After the generation of a generic element, one would like to assign it to another collection, this is currently not enabled

The system where the error occurred: test server

**Comment by phuang26** [comment]
Hi, I've tried Assign to Collection and Move to Collection functions on the test server and both worked fine (see attached). If you encounter this error again, could you please provide the element and then I investigate the issue. Thank you.

https://user-images.githubusercontent.com/70375322/129897539-c948b70b-fc88-418b-a220-f183bbb50a26.mp4

**Comment by NRayya** [comment]
Closing issue: The issue was fixed and tested in the test instance.
