### ISSUE TITLE
move/duplicate checkbox for decoupled sample

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#509]
It would be great to have the checkbox for the decoupled sample in addition at another place. 
Currently, the checkbox is located at sample, tab: properties. 
A problem may arise if the properties tab is not necessary for some type of decoupled sample. The used would have to keep the properties tab for only this function (also most of the other information is not required). 
-> availability in the sample ?

**Comment by cllde8** [comment]
This feature has been taken and finished ([GitLab#1282](https://git.scc.kit.edu/ComPlat/chemotion_ELN/-/issues/1282))

A checkbox for the decoupled sample is added in the header of sample detail. Please refer to the video below or try on the  [testing instance](http://193.196.38.77):

https://user-images.githubusercontent.com/42910431/134241051-9683d995-4f42-46ad-833e-7ee37ff278e3.mp4

**Comment by phuang26** [comment]
it has been included in ELN v1.1.0 already.
