### ISSUE TITLE
rename chemotion.net to chemotion-repository.net in the Collection Bar

### ISSUE THREAD

**Issue by Ira-Maier** [ComPlat/chemotion_ELN#515]
...because chemotion.net points to the documentation
![image](https://user-images.githubusercontent.com/73794984/129412402-e66538a8-ba2c-4745-9500-312d7eddb068.png)

**Comment by cllde8** [comment]
Released, please refer to [Chemotion_ELN Changelog](https://github.com/ComPlat/chemotion_ELN/blob/development-5/CHANGELOG.md#v100-beta)
