### ISSUE TITLE
UV-vis layout extension

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#531]
add further functions to the UV-Vis layout. Gdocs description available
https://docs.google.com/document/d/11ckiAgwQcJeESUvu-Lv7xlJgN4u4phEQ/edit#

**Comment by baolanlequang** [comment]
Status on 21/09/2021

### What were done
**1. ChemSpectra Function**

- Peak selection/deletion
- Peak integration, manual and by algorithm (baseline)
- Calculation AUC (area under curve) for each peak
- Calculation area percent of selected peaks
- Simultaneous view of several spectra (overlaying/superimposing of spectra)

Demo video

https://user-images.githubusercontent.com/9006482/134158708-9ccaf04b-05df-4836-84d9-fa8c342692db.mp4


### What is needs to be discussed (DO WE NEED TO IMPLEMENT IT?)

**1. ChemSpectra Function**

- Peak separation (splitting of peaks)
- Assignment of molecules to peaks for mixtures, or simple comment function for a peak
- Table in ChemSecptra: give the peak name, retention times of the peaks, the AUC and the area percent (of all selected peaks) → data table should be submitted to analysis tab 

**2. For analysis tab:**

- in description: create text blocks (as existing for H, C, IR, UV, MS), for metadata like instrument name, column,temperature [°C], flow rate [mL/min], eluent, and , detection wavelength (UV) [nm], Fluorescence detection (Extinction wavelength [nm], emission wavelength [nm], Standard

- create text block: table function for eluent gradients (Time [min], Eluent A, B, C, Name, Percentages [%] for each eluent)

- Data table as a separate section within the analysis (like content, description, etc) , that can be exported as single csv (see function research plan)

**3. ELN report:**
information from analyses with fields name, status, type (chemical methods ontology), content, description, data table

**Comment by baolanlequang** [comment]
Status on 24/09/2021
Demo functions as below

https://user-images.githubusercontent.com/9006482/134732956-f045fc49-8e26-41f3-9e71-7e3af3416f6c.mp4

**Comment by NRayya** [comment]
Closing issue: Done. Points left for discussion will be mentioned in new issues and linked to this issue.
