### ISSUE TITLE
Add further functions to XRD layout

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#532]
Details to be discussed, here users' information 

"To convert 2Theta to d-values you have to know the X-ray source (and thereby the wavelength).
You can then use Bragg's law: nλ=2dsin(Theta) where n is the order, λ is the wavelength of the X-ray beam (0,15406 nm for CuKalpha, the usual source), d is the distance between the planes, and theta is the diffraction angle (half of 2Theta).
So if you have a CuKalpha X-ray source (usually used) and the 2Theta values you can get the d values by this formula:
d = λ/(2 * sin(theta))
or:
d = 0,15406nm /(2 * sin(Theta))
d is then given in nm
please note, you get Theta by dividing 2Theta by two
P.S. if the sinus function is in degree you don’t have to do anything. If it uses radians, than you have to divide Theta by 180 and multiply with Pi"

**Comment by baolanlequang** [comment]
Shipped issue to https://git.scc.kit.edu/ComPlat/chemotion_ELN/-/issues/1290
