### ISSUE TITLE
Private note rework

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#534]
Can we minimize the field "private note" field? its quite large and only used in certain cases. Also, it would be good to remove the save button if possible (the only field with additional save function)

**Comment by baolanlequang** [comment]
Finished and waiting to merge at https://git.scc.kit.edu/ComPlat/chemotion_ELN/-/merge_requests/1545

**Comment by baolanlequang** [comment]
This function will be released in next version
