### ISSUE TITLE
Inbox enhancement

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#537]
We tested the new inbox function and had some requests, hoping that can be included: 

(1) It would be great if the assignment of data to samples can be done based on:
"name" (sample) <-> "analysis title" (as is at the moment)
"external name" (sample) <-> "analysis title" (in addition to the current process)

(2) The assignment should work case-insensitive if possible (tolerate mistakes coming from upper and lower case letters). 

(3) The selection of possible suitable target samples gives currently (due to the selection per "name") for most of the measurements two matches (one for the molecule used as starting material and one for the same molecule obtained as product). This is confusing and it would be great to see additional information in the selection mode such as the role in a reaction. Then the user could see directly that the product is meant and could choose it. 

(4) in the current version, the transfer action induces the automatic deletion of the analysis in the inbox + the generation of a new analysis for the selected sample. This causes the problem that the action is out of tracking of the user (corresponding sample is not opened -> no control if everything went fine). It would be great if the user could have a list of transactions with each successfully assigened analysis creating a new line (while deleted in the inbox). The list of transactions should list the target sample and should contain a link to the sample if the user wants to check the transfer directly. 
Opening the sample with the transfer is not desired as it takes too long.

**Comment by nicolejung** [comment]
<img width="1267" alt="Screenshot (1484)" src="https://user-images.githubusercontent.com/7559189/132912714-2e300f87-0454-4478-9da9-798baa23647b.png">

**Comment by phuang26** [comment]
This feature has been taken and finished.

**Comment by phuang26** [comment]
has been included to ELN v1.1.0.
