### ISSUE TITLE
Download button: all analyses  for a given sample

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#538]
It would be great to have all analyses saved to one sample to be downloaded with one button

**Comment by phuang26** [comment]
Hi Nicole, we have a "Download Analysis" button in sample, it downloads all analyses in one go. You can find it in both ELN and Repository site. Please see the image below:

Is this what you want?

![2021-09-10_230807](https://user-images.githubusercontent.com/70375322/132918286-0067ac36-54bd-46ee-b0d0-d60a25583d16.png)

**Comment by nicolejung** [comment]
Perfect, thanks! I received the request from a user... I will let him know
