### ISSUE TITLE
"Save sample" function "hangs" on incorrect values in "properties" tab

### ISSUE THREAD

**Issue by schatzsc** [ComPlat/chemotion_ELN#540]
In the `sample properties` tab, if one enters a number > 1 to the field `Purity` and then selects `Save sample` the update "hangs" with the "two circulating arrows" icon shown indefinitely.

It is unclear to the end user that in this field the allowed range is 0 < x <= 1, as chemical vendors usually give the purity in 98% format or so.

Interestingly, an entry of "0.000001" works as expected with short save time but "1.000001" also leads to hang up, which can only be stoped by browser "reload tab" function.

Introduce check of valid range before trying to save?

**Comment by adambasha0** [comment]
https://user-images.githubusercontent.com/55552142/133971379-fcfb67ff-8459-47dd-9069-82a814f0ca9b.mp4

**Comment by schatzsc** [comment]
Honestly, from a chemical point of view, this is not a good choice, as a value of 1 would indicate 100% purity

The best would be - if no valid value is provided - to have an alternative entry as "purity not determined" or "data not available", maybe internally coded as -1 or so

If this is not possible or would require a major rework of the data structure, I think a numer "0" (zero) would be then better default, as it would be almost clear to anybody that this is not a useful figure and thus only a placeholder.

But a default value of 1 (= 100% pure) gives a wrong impression that by default, the sample is ultrapure, which it is not.

**Comment by adambasha0** [comment]
Thanks Prof. @schatzsc. Your request will be discussed further in a seperate discussion. because your proposal impacts previous work done in this regard.
