### ISSUE TITLE
Issue for Chemotion-Repo

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#548]
Example Sample: https://www.chemotion-repository.net/home/publications/molecules/5153
Clicking the preview image of an analysis to enlarge the image actually does not enlarge it.
See attached GIF.
![Peek 2021-10-05 10-09](https://user-images.githubusercontent.com/209056/135985352-925de587-8fd6-4cbe-a56b-e052d12a6ee9.gif)

**Comment by cllde8** [comment]
Hi @ptrxyz ,

I have analyzed the issue and provided a fix. This fix will be delivered in the next deployment.

Thank you for raising this issue.

Best regards,
Claire

![screencast-localhost_3000-2021 10 05-17_08_25](https://user-images.githubusercontent.com/42910431/136157885-c027a81f-e9d8-487b-91a8-1e2c52541627.gif)

**Comment by phuang26** [comment]
has been deployed to Chemotion Repository
