### ISSUE TITLE
Color code for keys is not consistent

### ISSUE THREAD

**Issue by Alexwelle1** [ComPlat/chemotion_ELN#552]
- [ x] I am an ELNer
- [ ] I am a developer
- [ ] I am a system/ELN admin

# Expected Behavior

Function keys like "save", "cancel", "close" on the modules and the ketcher editor should be uniform with respect to their color code

# Current Behavior

On the ketcher structure editor "cancel" is yellow, "create" is blue. However, when creating a new sample "save" is yellow and "cancel" blue.

# Failure Information 

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - [ x] Chrome Browser 
 - [ ] Firefox Browser
 - ELN version, or branch, or commit

## Failure Logs / Screenshots

![image](https://user-images.githubusercontent.com/92295214/136751813-e20e88bc-eb0c-4243-be35-eec5a0f282eb.png)
![image](https://user-images.githubusercontent.com/92295214/136751838-51359d06-3f62-4660-87ad-3bc5576e8ba2.png)

**Comment by NRayya** [comment]
Hello @Alexwelle1
Thanks for reporting this. We have opened a new issue with more details and we will solve it soon.
