### ISSUE TITLE
Exporting literature is not possible currently

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#554]
The users are trying to export the DOI of the references added to the literature section of a sample into the spreadsheet. It would be great to have just one column there for that. Currently there is no way to link the literature to samples neither by exporting nor by creating a report.

**Comment by phuang26** [comment]
Please refer to below video:

report with sample literature info:
https://drive.google.com/file/d/10hgPTxBKP2x_C_bvgIQ41AQCM-WLrs4x/view?usp=sharing

export with sample literature info:
https://drive.google.com/file/d/1CCQ-oOBHl4_u0RN4BCWxlwHLhsv0sW_I/view?usp=sharing

**Comment by phuang26** [comment]
the DOI, author, issn and published year info are added to the report function

**Comment by phuang26** [comment]
taken and finished
