### ISSUE TITLE
selection of tabs - lists

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#559]
The alternative way to select/sort tabs is better but we need a better color: grey is almost not visible. please change to more intuitive  and clearer color coding

**Comment by TasnimMehzabin** [comment]
The lighter grey colour is replaced with a darker one to make it more prominent.

![image](https://user-images.githubusercontent.com/8912580/159285845-46dbd7ee-5c83-44d9-9b18-23049b9c1f4a.png)

![image](https://user-images.githubusercontent.com/8912580/159285911-1f09d87e-6253-4d47-b4d5-39a847d2e5c7.png)
