### ISSUE TITLE
fixing js imports in postinstall script fails with alternative NODE_PATH.

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#560]
When installing node modules to a different path than ./node_modules, the `package_postinstall.sh` script will fail sind the paths are hard coded. Node/Yarn/npm however allow different module paths (i.e. through `NODE_PATH`, `yarn global` or `yarn install --modules-folder`, etc).

I suggest to resolve the module files using [require.resolve](https://nodejs.org/api/modules.html#requireresolverequest-options).

**Comment by PiTrem** [comment]
👍
