### ISSUE TITLE
a few reaction related issues

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#562]
- can we have the solvents section not collapsed per default (was mentioned in another issue some time ago)?
- can we add a checkbox for dry solvents in the solvents section in the reactions table (see proposed place)?
- can we add the following chemicals/actions to the ELN lists:? 
**Reagents list (quick selection list):** 
sodium bicarbonate (NaHCO3):   smiles: C(=O)(O)[O-].[Na+]
Tetramethylethylenediamine (TMEDA), smiles = CN(C)CCN(C)C 
**Solvents list:** 
2-Butanone, smiles: CCC(=O)C
Tetramethylethylenediamine (TMEDA), smiles = CN(C)CCN(C)C 
**Purification method (in tab scheme of reactions):**
filtration
<img width="1280" alt="Screenshot (1636)" src="https://user-images.githubusercontent.com/7559189/138285163-74ffb10e-d19e-4aeb-8c73-d517daee5993.png">

**Comment by adambasha0** [comment]
Issue shipped to [gitLab](https://git.scc.kit.edu/ComPlat/chemotion_ELN/-/issues/1325)

**Comment by adambasha0** [comment]
https://user-images.githubusercontent.com/55552142/142431864-3caa50a3-5ca5-43e3-9335-3578e8aa8d04.mp4


https://user-images.githubusercontent.com/55552142/142432069-472a1a56-3bfe-4cda-831b-45369ec804ba.mp4

**Comment by adambasha0** [comment]
mentioned points from Nicole were applied in #1433 and #1432. The issue should be closed.
