### ISSUE TITLE
delete multiple inbox items at once

### ISSUE THREAD

**Issue by PiTrem** [ComPlat/chemotion_ELN#571]
As a ELNer
 
 when sorting my attachments in the Inbox
 
 I want to delete many items at once
 
 so that I dont have to click thousand times to clear part of my inbox
 
 
![image](https://user-images.githubusercontent.com/15799181/141113219-279f9719-9032-4433-8039-eb7c3e384ac3.png)

**Comment by adambasha0** [comment]
issues shipped to Gitlap[https://git.scc.kit.edu/ComPlat/chemotion_ELN/-/issues/1342](url)

**Comment by adambasha0** [comment]
[MR of issue on Gitlab](https://git.scc.kit.edu/ComPlat/chemotion_ELN/-/merge_requests/1604)

Video:

https://user-images.githubusercontent.com/55552142/158971470-0167e36e-3b8f-49d8-aa6c-2b3c8b6084a9.mp4

**Comment by nicolejung** [comment]
Please check with scientists for rework of the feature. There are some suggestions for further improvements (Sylvia/Simone)

**Comment by adambasha0** [comment]
Hi @SylviaVanderheiden, please let us know if something else is needed with respect to deleting multiple inbox items once, after last improvements from @f-idiris. Otherwise we will close this ticket.

**Comment by SylviaVanderheiden** [comment]
Dear @adambasha0 in the version we currently use, Version: 1.7.2, there is no possibility to delete multiple items and no checkbox is available. I do not know if this will change once we use version 1.8...

**Comment by SylviaVanderheiden** [comment]
@adambasha0 @f-idiris @PiTrem 
I tested on uncharted and it seems to work fine.
Thanks,
Sylvia
