### ISSUE TITLE
Melting point temperature range

### ISSUE THREAD

**Issue by victorlarignon** [ComPlat/chemotion_ELN#581]
Would it be possible to change the melting point text box so we can enter a temperature range instead ? Melting points are rarely just a point and currently we have to enter the range in description additionaly.

**Comment by cllde8** [comment]
Hi @victorlarignon 

The boiling points and melting points can be added as range, by typing the first value, space and second value. The video for your reference

https://user-images.githubusercontent.com/42910431/142607881-67bd5575-051d-49d6-9f5e-14425fbfa81b.mp4

Best regards,
Claire Lin

**Comment by victorlarignon** [comment]
Hi Claire,
Thank you for the feedback, I wasn't aware of this.
Best regards,
Victor
