### ISSUE TITLE
Show associated collection when searching for an elemnt in All collections

### ISSUE THREAD

**Issue by AnnettNFDI** [ComPlat/chemotion_ELN#594]
As  a user I would like to see to which collection an elemnt belongs to if I am searching in the "All" collection. If I am searching for an element (e.g. sample) then I have to select a specific collection to search in or I have the option to search in "All" collection. However, if I search in "All" collection, theres is no information provided to which collection the resultsing e.g. sample belongs to. 
As a solution the name of the collection could be added in the results list of the serach together with the elemnt information. Alternatively, the name of the collection could be stored with the element information (see screensho
![Collection_reference](https://user-images.githubusercontent.com/84778300/143886461-7a4417c1-1308-4cee-9c5b-66b6f3f5cee0.GIF)
t)

**Comment by NRayya** [comment]
Closing issue: It is currently possible to see the collection by pressing on the white rectangle (1-0) where the collection name will be shown.
