### ISSUE TITLE
Generic elements: system defined filed: New unit needed for Vmax

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#602]
- [x] I am an ELNer
- [ ] I am a developer
- [x] I am a system/ELN admin

# Description
Currently there is no unit available for the maximum rate of an enzymatic reaction (Vmax). The unit mol/g/min and its conversions are needed for enzyme data.

**Comment by cllde8** [comment]
Dear @NRayya,

We have reviewed the supportive units. Please refer to the list at this [link](https://github.com/LabIMotion/labimotion/wiki/Supported-Units-for-System-Defined-Field) for the enzyme-related units.

If the current supportive units are not applicable to your application, please kindly create an issue or start a discussion at https://github.com/LabIMotion/labimotion.

Thank you.

Best regards,
Claire
