### ISSUE TITLE
Color code for keys is not consistent

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#603]
- [x] I am an ELNer
- [ ] I am a developer
- [x] I am a system/ELN admin

# Description
Currently, keys with the same functionality have different names (close, cancel) and different colors.

To deal with this issue, the following convention is suggested (As most keys in the ELN follow it):

- Generating data: Dark blue (keys like "Add")
- Modifying data: yellow (keys like "save", "update") 
- Losing data: red (keys like "delete", "cancel")

This file has a summary of most [buttons in the ELN](https://docs.google.com/spreadsheets/d/1_SltG3_423LVUbUb9TEipLP7BFrNJVJwbgwKVTjVJms/edit?usp=sharing)

Buttons that need to change:

- toolbar: remove elements (yellow) -> red
- Sample, reaction... modal: Close (blue) -> red
- Ketcher: Save (dark blue) -> yellow
- Ketcher: Cancel (yellow) -> Close (red)

Optional: To comply with the above description, One can restrict the three colors for the described purposes. (e.g. buttons like synchronize collections are not in blue any more)
Also one can restrict the purposes to the three colors (e.g., buttons like add data set become in blue instead of green).

Possible solutions are provided here:
![image](https://user-images.githubusercontent.com/82588017/145270768-cd838156-2148-4fab-a776-040e2700a482.png)
![image](https://user-images.githubusercontent.com/82588017/145270824-dfd6eadc-8f5e-47d2-bda4-380c21e789a1.png)
![image](https://user-images.githubusercontent.com/82588017/145270900-a2f5533d-4f1b-4a69-aabf-c54a74435fae.png)

Additionally, the relative location of cancel and save buttons needs discussion

**Comment by NRayya** [comment]
Duplicated issues: 
https://github.com/ComPlat/chemotion_ELN/issues/552

**Comment by NRayya** [comment]
High priority:
Change the buttons in Ketcher to fit with the sample modal

**Comment by dp19982** [comment]
> High priority: Change the buttons in Ketcher to fit with the sample modal

Ketcher buttons changed to fit with sample modal:
https://react-bootstrap.github.io/components/buttons/ - Primary (blue) and Warning (yellow) are the two button styles used in sample modal

Sample Modal:
![sample modal](https://user-images.githubusercontent.com/67055123/162748952-c8cfbd16-026f-42c1-b12c-495fd2702757.png)

Previous Ketcher buttons:
![old_ketcher_buttons](https://user-images.githubusercontent.com/67055123/162748001-e38c8057-e368-4f77-b268-3fb2dfe094b7.png)

New Ketcher buttons
![new_ketcher_buttons](https://user-images.githubusercontent.com/67055123/162748327-33166d3a-db83-4e50-8253-38a534eb043f.png)

Changes are only local right now.

**Comment by dp19982** [comment]
The following (read-only) spreadsheet contains a list of the major buttons, their function, current style, and a proposed style change (if required). I shall be implementing these changes in a local branch and will add comments in the spreadsheet, and add images to the document showing the changes.

Google spreadsheet detailing proposed changed (read-only): https://docs.google.com/spreadsheets/d/1sxmV0QZDneh7t4pJI8C9b8BLTEhS4dYbYwhv4B6Uck8/edit?usp=sharing

Google document for images of proposed changes (read-only): https://docs.google.com/document/d/1TO_7mIOWTVZJamOPIFwPfuzObJdBESOQuuteLmezkAY/edit?usp=sharing

**Comment by dp19982** [comment]
Issue closed - refer to #874

**Comment by endevor-music** [comment]
For posterity - a hard copy of the document and spreadsheet.
[603 - Colour code for keys is not consistent.docx](https://github.com/ComPlat/chemotion_ELN/files/13498276/603.-.Colour.code.for.keys.is.not.consistent.docx)
[603 - List of Buttons.xlsx](https://github.com/ComPlat/chemotion_ELN/files/13498277/603.-.List.of.Buttons.xlsx)
