### ISSUE TITLE
Generic elements/system defined: fix Enzyme activity unit

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#607]
- [x] I am an ELNer
- [ ] I am a developer
- [x] I am a system/ELN admin

Currently the provided unit for enzyme activity is U/L, while it should be "U" or "IU" (the same). Also conversions to  "katal" (kat) which is the preferred unit now would be great to have, along with its submultiples (millikatal mkat, microkatal µkat, nanokatal nkat).

1 U = 16.67 nkat

**Comment by phuang26** [comment]
more discussion is needed to clarify the requirement.
