### ISSUE TITLE
Reaction label preview

### ISSUE THREAD

**Issue by victorlarignon** [ComPlat/chemotion_ELN#608]
- [X] I am an ELNer
- [ ] I am a developer
- [ ] I am a system/ELN admin

# Expected Behavior

In the Account and Profile menu, in the reaction label subdivision, the "Next reaction label will be:" should display the reaction label for the next reaction generated.

# Current Behavior

The reaction label doesn't show anymore.
![reaction label bug](https://user-images.githubusercontent.com/93988038/146910661-f0793849-9b6e-4223-a9ac-5a308c2b3c77.png)

**Comment by TasnimMehzabin** [comment]
This issue could not be reproduced on the current version. I have added a screenshot for reference.

![image](https://github.com/ComPlat/chemotion_ELN/assets/8912580/8836bf13-6baf-4f16-a583-e1b07b7284c1)

**Comment by PiTrem** [comment]
resolved with [#1556](https://github.com/ComPlat/chemotion_ELN/pull/1556)
