### ISSUE TITLE
Editability of pre-set text building blocks for the description of reactions

### ISSUE THREAD

**Issue by JohnJolliffe-JGU** [ComPlat/chemotion_ELN#612]
- [x] I am an ELNer

# Description
We find the text building blocks for writing the description of a reaction very practical, but unfortunately the preset text blocks are only partially suitable or entirely unsuitable for our normal work steps. 

It would be great if users could create their own preset text building blocks for reaction descriptions.

**Comment by PiTrem** [comment]
At this stage, a user itself cannot provide new building blocks , but the ELN Admin can  (AdminUI -> Text Templates).  
Then the user can customize its text editor toolbar with them.


![image](https://user-images.githubusercontent.com/15799181/150305889-54eade2e-95b1-43a6-b178-8d42d3c9f69f.png)

**Comment by JohnJolliffe-JGU** [comment]
Thanks for your feedback - I think this will work as an interim solution while we do not have too many ELN users. However, once this number picks up, it would be very time consuming for the Admins to continuously add and update these descriptions from all the users. Therefore it would be great if the users could create there own templates without having to go through the admins.

**Comment by PiTrem** [comment]
ok I will close this one for now. (documentation is missing. i have opened a ticket here https://github.com/ComPlat/chemotion_saurus/issues/67)

I agree that the feature as well as some others of those customization functions have to be enabled to others not just the admin. ( maybe not all the users but  the group-admins )
