### ISSUE TITLE
rework of templates for description and analysis

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#637]
- [x] I am an ELNer
- [ ] I am a developer
- [ ] I am a system/ELN admin

# Expected Behavior

Option to define templates for description or analyses 
Option to upload icons

**Comment by adambasha0** [comment]
issue shipped to [Gitlab](https://git.scc.kit.edu/ComPlat/chemotion_ELN/-/issues/1371)
