### ISSUE TITLE
Same sample number for multiple samples

### ISSUE THREAD

**Issue by NRayya** [ComPlat/chemotion_ELN#645]
- [x] I am an ELNer
- [ ] I am a developer
- [x] I am a system/ELN admin

# Expected Behavior

Each sample gets a unique sample number

# Current Behavior

A user has reported that he was getting the same number for multiple samples.

## Steps to Reproduce

I didn't manage to reproduce the bug.

## Failure Logs / Screenshots

![image](https://user-images.githubusercontent.com/82588017/155985120-5304f847-9283-40a6-aa1e-89c37815f6e1.png)
![image](https://user-images.githubusercontent.com/82588017/155985155-1fd012bc-91d0-419e-818c-0f694511b0a0.png)

**Comment by phuang26** [comment]
already solved and released on v1.1.1
