### ISSUE TITLE
Enhancement Issue for referencing to general procedure-entries

### ISSUE THREAD

**Issue by MTenb** [ComPlat/chemotion_ELN#646]
- [ x] I am an ELNer

# Description
For reactions marked as "Part of GP" there is an drag&drop'able field for the corresponding general procedure in the scheme-tab. I think it would be good, if the assigned entry also becomes a clickable link which directly opens the entry of the general procedure-entry. This would be a very convenient way of navigating from a "part of GP"-entry to its parent GP-entry without scrolling through the list or having to use the search-tool.
![gp](https://user-images.githubusercontent.com/100708486/156205613-9c17a9ee-ba4a-427b-8195-a6059a53d76e.PNG)

**Comment by dp19982** [comment]
Please see the following video for a demonstration of  the added functionality.

https://user-images.githubusercontent.com/67055123/168546373-2c7bb1c3-f69d-4fa0-a952-c390f0f0bad9.mp4

**Comment by MTenb** [comment]
Perfect! Thanks for adding this.

**Comment by dp19982** [comment]
Not a problem - I shall post here when it has been implemented into a release.
