### ISSUE TITLE
default settings for structure search options

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#650]
Hi all, it would be great if someone could change the default settings in the search window for structure search. Currently, we have similarity search as default, but substructure search (RDKit or Openbabel) is most feasible. This change will avoid some problems with the search function. 
Also: it would be great to have the option "exact search"

**Comment by cllde8** [comment]
Hi @nicolejung,

The default search option has been updated from "Similarity Search " to "Substructure Search" and will be available in the next release.

For the "Exact Search" task, I have created another ticket for it [Add Exact Search as one of the structure search options](https://github.com/ComPlat/chemotion_ELN/issues/664), so I will close this ticket.
