### ISSUE TITLE
Labels can't be assigned when generating supportiung info - label-tab empty

### ISSUE THREAD

**Issue by MTenb** [ComPlat/chemotion_ELN#661]
- [X ] I am an ELNer

# Expected Behavior

While generating a report of selected samples/reactions labels for the different structures can be assigned in the "label"-tab.

# Current Behavior

If you open teh label-tab the page is showing a loading wheel for a few seconds, when finished loading the label-tab is completely empty, therefore no label can be assigned ans all structured are assigned with the generic label "(xx)" in the corresponding report.

## Steps to Reproduce

1. select random entry
2. click on green botton -> Report
3. select supporting info tamplate -> click on Label-Tab

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: Windows
 - [x ] Chrome Browser 
 - [x ] Firefox Browser
 - ELN v1.1.3

## Failure Logs / Screenshots

![label_bug](https://user-images.githubusercontent.com/100708486/162761231-2bafb607-c89d-4762-8a2a-d183a26b4d80.PNG)

**Comment by nicolejung** [comment]
Hi MTenb, could you contact me by email: nicole.jung@kit.edu? I think it's not a bug but a problem of missing settings, but it would be great to meet virtually and have a quick look. We can then post the solution here after clarification if this is fine with you

**Comment by nicolejung** [comment]
Bug confirmed
