### ISSUE TITLE
No more Notifications in Chrome

### ISSUE THREAD

**Issue by MTenb** [ComPlat/chemotion_ELN#662]
- [ x] I am an ELNer

# Expected Behavior

Chemotion usually sends notifications when a newly generated report/export/import is finished or ready for download.

# Current Behavior

After a Report is generated no notification is send. The new downloadable report is only found after refreshing the archive-tab.

## Steps to Reproduce

1. select random entry -> Report (random settings)
2. click on generate 

## Context

 - OS: Windowns
 - [x ] Chrome Browser 
 - [ ] Firefox Browser
 - ELN v1.1.3

This Bug only occurs in Chrome (latest version), Firefox seems to work fine.

## Failure Logs / Screenshots
![notification_bug](https://user-images.githubusercontent.com/100708486/162767966-877eca00-47d3-47cd-97ff-04c1cac98b28.PNG)

**Comment by NRayya** [comment]
Hi @MTenb , thanks for reporting the issue
We didn't manage to reproduce the bug, are you still having it?

**Comment by MTenb** [comment]
Hi @NRayya,
Yes, I'm still having it. I updated Chrome just now to the newest available Version 100.0.4896.127 (Official Build) (32-bit), which sadly did not fix the issue. Interestingly, the issue only occurs in Chrome.

**Comment by NRayya** [comment]
Hi @MTenb, thanks for trying again.
If you have some time, could we get in a call to see what's happening? Please feel free to contact me on my email: noura.rayya@uni-jena.de

**Comment by MTenb** [comment]
Hi @NRayya,
Have you recieved my mail or did it get lost on the way?

**Comment by phuang26** [comment]
Hi @MTenb it's a server configuration issue and has been fixed by Johannes, could you reload the page and try again? Thank you.

**Comment by MTenb** [comment]
Hi @phuang26,
I just tried on two different computers. I had to delete the cookies/site data in chrome on one of them, but now it works fine again. 
Thanks for your help!
