### ISSUE TITLE
Right-clicking the "Add" button results in dragging things around.

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#670]
Found in version 1.2.0:

https://user-images.githubusercontent.com/209056/164023423-389f1735-ae34-4bd5-9949-55dfe31b5b87.mp4

Its a bit counter-intuitive that you can drag this around ... :D

**Comment by FabianMauz** [comment]
It is not only a problem of right clicking. Also the "dropzones" are not defined correctly and leads to a hard crash if dropped on some tab titles.

https://github.com/ComPlat/chemotion_ELN/assets/23172219/7c897079-ccb9-4b9e-9758-931b41753947

**Comment by FabianMauz** [comment]
Happens only if the "root" collection is dragged

**Comment by JanCBrammer** [comment]
The drag-and-drop is not implemented using the `react-dnd` package we're usually using.
Instead the drag-and-drop is implemented using https://github.com/swiftcarrot/react-ui-tree.
It seems that there's no obvious / easy way to configure the drag-and-drop with the letter library.
