### ISSUE TITLE
Enhancement of research plan

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#672]
- [x] I am an ELNer
- [ ] I am a developer
- [ ] I am a system/ELN admin

1. Research Plan is missing currently the option to see the collections where the research plan belongs to. 
It would be great to have this. 
2. In the attachment part of the research plan, the preview function for png (perhaps also others) is currently not working.

**Comment by TasnimMehzabin** [comment]
The preview issue has been resolved.

https://user-images.githubusercontent.com/8912580/176265716-0fe5b012-f6d9-4cf8-9e70-ba23ba9db840.png
