### ISSUE TITLE
Removal of reaction arrow for reactions without samples

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#691]
- [x ] I am an ELNer
- [ ] I am a developer
- [ ] I am a system/ELN admin

# Description
Please provide a description of:
1. what enhancement you suggest
For reactions without samples, the arrow is added to the scheme. It would look a lot nicer without. Arrow should appear in the scheme when the first sample is added
<img width="1280" alt="Screenshot (2311)" src="https://user-images.githubusercontent.com/7559189/166804286-d16f79f7-6e92-4622-8a2d-a2cfd930a869.png">

**Comment by dp19982** [comment]
The simplest solution is to not render the scheme image, unless there are samples present (starting materials, reactants, products and solvents) - please see the video for a demo.

https://user-images.githubusercontent.com/67055123/168552307-a9873f0f-f70b-46b3-9c58-c825aedfd529.mp4

**Comment by adambasha0** [comment]
Hello @endevor-music,
The reaction arrow is still available in the left side view though, is this wanted?
please refer to [here](https://github.com/ComPlat/chemotion_ELN/issues/885#issuecomment-1308924981) to see the video

**Comment by endevor-music** [comment]
> Hello @endevor-music, The reaction arrow is still available in the left side view though, is this wanted? please refer to [here](https://github.com/ComPlat/chemotion_ELN/issues/885#issuecomment-1308924981) to see the video

HI Adam,

No, I don't think that's wanted - I didn't consider changing the reaction image in favour of a simple solution at the time, my apologies!
