### ISSUE TITLE
Reference Style improvement 

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#695]
- [ x] I am an ELNer
- [ ] I am a developer
- [ ] I am a system/ELN admin

# Expected Behavior

See information in reference for ISBN only one - see screenshot
![Uploading Screenshot (2333).png…]()

**Comment by cllde8** [comment]
Hi @nicolejung ,

The screenshot does not exist. Could you please upload it? Thank you.

**Comment by nicolejung** [comment]
<img width="627" alt="Screenshot (2333)" src="https://user-images.githubusercontent.com/7559189/167296229-9bbe5964-62e1-4250-bf15-5dc78b4854db.png">

**Comment by ptrxyz** [comment]
In 1.2.1 it seems to look ok: 
![image](https://user-images.githubusercontent.com/209056/169019410-bccba194-a02b-4504-9e5f-4a1ad31dbcd2.png)

**Comment by ptrxyz** [comment]
Found a way, this ISBN seems to produce long http links: 3442151473

**Comment by cllde8** [comment]
Hi @ptrxyz ,

I am already working on this, so if you have any questions, you can contact me.

Best regards,
Claire Lin

**Comment by ptrxyz** [comment]
Ok! Can I find you on discord? I found a few other bugs (#706 #707 #708), I just wanted to pitch. And maybe the idea of sticking to a common citation format as the data from the API services that are used seem pretty structured.

**Comment by ptrxyz** [comment]
I keep these links here, as they might be helpful:

https://style.mla.org/urls-some-practical-advice/    (addressing the problem of long links in citations); 
https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_works_cited_electronic_sources.html         (some suggestions on how to order fields in citations)
