### ISSUE TITLE
Cannot display the latest image of updated jdx on preview chemspectra

### ISSUE THREAD

**Issue by baolanlequang** [ComPlat/chemotion_ELN#697]
- [ ] I am an ELNer
- [x] I am a developer
- [ ] I am a system/ELN admin

# Expected Behavior

1. Upload two jdx files
2. Open chemspectra modal window
3. Select the second jdx file
4. Add peaks and select the saving function
5. The preview image should be the image of the second jdx file

# Current Behavior

1. Upload two jdx files
2. Open chemspectra modal window
3. Select the second jdx file
4. Add peaks and select the saving function
5. The preview always is the image of the first jdx file

**Comment by fbroda** [comment]
The creation of thumbnail / preview images during upload of images / attachments / spectra / datasets is currently analyzed by @FabianMauz. We plan to rework / unify this entire mechanism. We cannot judge yet, whether this is feasible, i.e. how big this task is (side effects, ...). I'd suggest (kindly ask) to get into contact with Fabian, e.g. via Rocket Chat.
