### ISSUE TITLE
Not able to enter spaces in Reference Title

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#706]
When it comes to entering a title for a reference, I'm not able to type in spaces as a last character.
So simply typing "This is a title", results in "ThisIsATitle". Spaces can be added manually afterwards but I suppose this is a bug.

![image](https://user-images.githubusercontent.com/209056/169021091-185fcce8-14be-4077-a6ec-56a0cc9cba2b.png)

Using Version 1.2.1 (PRODUCTION).

**Comment by ptrxyz** [comment]
This seems to be also true for the other text boxes.

**Comment by PiTrem** [comment]
resolved
