### ISSUE TITLE
My affiliation drop-down suggestion list no longer works

### ISSUE THREAD

**Issue by phuang26** [ComPlat/chemotion_ELN#712]
my affiliations drop down suggestion list is not working anymore

was working (Version: 0.8.0):

https://user-images.githubusercontent.com/70375322/169157574-a329dd5a-13d4-4617-80b1-2d19f4017c78.mp4

is not working anymore (Version: 1.2.0-pre):

https://user-images.githubusercontent.com/70375322/169157622-cc8b6373-d306-4219-9243-360f9e729221.mp4

**Comment by PiTrem** [comment]
resolved with 02934c1b6  https://github.com/ComPlat/chemotion_ELN/pull/1190
