### ISSUE TITLE
In CHN analysis reports, all values should be given with two relevant digits

### ISSUE THREAD

**Issue by schatzsc** [ComPlat/chemotion_ELN#721]
- [x] I am an ELNer
- [ ] I am a developer
- [x] I am a system/ELN admin

# Expected Behavior

When reporting CHN analysis data, all values should be given with two relevant digits, even if the digits to the right of the decimal separator are zero, since these are precisely known while digit not shown means "unknown"

# Current Behavior

Values are incorrectly given as 76.9 instead of correctly as 76.90 (and possibly also 76 instead of 76.00)

# Failure Information 

Insufficient number of digits to right of decimal separator given although they are precisely known

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: Windows
 - [ ] Chrome Browser 
 - [ x] Firefox Browser
 - ELN version, or branch, or commit: 1.13

## Failure Logs / Screenshots

Include any relevant log snippets or files here.
![Screenshot 2022-05-20 at 17-24-48 Chemotion](https://user-images.githubusercontent.com/88166560/169561601-bc761ddd-6a6a-4cea-baaf-7707c1633f1e.png)

**Comment by dp19982** [comment]
The values are rrepresented as atrings, so this was a simple regular expression conditional - if the value has one decimal place, concatenate a single 0 to the string. This should cover all instances, but in case, there is a conditional that adds ".00" to a whole number.

The initial example (2,2-bipyridine) is now:
![bipyridine](https://user-images.githubusercontent.com/67055123/170698346-665ae902-018b-44a8-aed8-14db9f155f36.png)


Example 2 (C10H18MnO6):
Original
![old1](https://user-images.githubusercontent.com/67055123/170696056-bad0bf1d-9a66-4dad-9834-25aaa3f2a81b.png)
New
![new1](https://user-images.githubusercontent.com/67055123/170696055-c76d98c7-ddde-468d-8419-894320459ebf.png)
