### ISSUE TITLE
In sample/molecule window, add field to specify room-temperature aggregation state and color

### ISSUE THREAD

**Issue by schatzsc** [ComPlat/chemotion_ELN#722]
- [ x] I am an ELNer
- [ ] I am a developer
- [ x] I am a system/ELN admin

# Description

In the sample/molecule window, currently only properties such as boiling/melting point, density, and purity can be provided.

It would be nice to also have additional fields here for (room-temperature) aggregration state (e.g. solid, liquid, oil, ...) and color.

In the 20.05.2022 Chemotion "Stammtisch" Kevin Jablonka from EPFL also showed a nice system how to assign colors more systematically based on picture and match to RGB color table

# Image

**Comment by dp19982** [comment]
After internal discussion, this issue is to be closed. @schatzsc, the functionality required can be replicated by adding generic segments (which allow for customisable fields) to the specific instance of Chemotion ELN that you are using.
