### ISSUE TITLE
UI-issue: Changing size/parts of ELN-components collection-list-details

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#723]
- [ x] I am an ELNer
- [ ] I am a developer
- [ ] I am a system/ELN admin

# Description
Please provide a description of:
I suggest to increase the width of the details level in the ELN UI and reduce the width of the list area

**Comment by dp19982** [comment]
The current split of list:details is 5:7 -

![7-5 ratio](https://user-images.githubusercontent.com/67055123/170267740-94d62209-53c9-4282-965c-25e38bf379f5.png)

The only other acceptable ratio that does not significantly impede users is 4:8 -

![8-4 ratio](https://user-images.githubusercontent.com/67055123/170267906-aabd09ae-9826-49a3-9311-1c699fbbdeb0.png)

**Comment by nicolejung** [comment]
Could you provide an image including the collections list?

**Comment by dp19982** [comment]
> Could you provide an image including the collections list?

@nicolejung 
Please note that these were taken on a laptop, and the previous ones were taken on a larger monitor.

5:7 -
![5-7 ratio](https://user-images.githubusercontent.com/67055123/170652028-b7375729-18cc-4654-9d14-b580e4c6b9b0.png)

4:8 -
![4-8 ratio](https://user-images.githubusercontent.com/67055123/170652020-35ea0135-27a3-4cee-bd3b-bbc509242fbc.png)

**Comment by endevor-music** [comment]
Closing as uncompleted, due to reoccuring issues (see PR #732)
