### ISSUE TITLE
Showing decoupled samples in Research Plan

### ISSUE THREAD

**Issue by Alexwelle1** [ComPlat/chemotion_ELN#727]
- [x ] I am an ELNer
- [ ] I am a developer
- [ ] I am a system/ELN admin

G'day, being more from the material science I'm using decoupled samples quite frequently (simply, samples are complex and have no clear molecular structure). Other than that I'm using research plans quite often, and I'm linking samples to thee protocols.
What -to me- is a bit disappointing is the way these decoupled samples are shown later:
![image](https://user-images.githubusercontent.com/92295214/169768203-ff0d5f11-04f9-4ea0-9aa4-2f2961aab993.png)

As you can see for molecular structures it's quite fine, but not for decoupled samples (below the molecule). Can one improve this?
Also, it would be super nice if these images would be links, to open directly the sample sheet in Chemotion.
Peace,
Alex

**Comment by dp19982** [comment]
Hi Alex,

> Also, it would be super nice if these images would be links, to open directly the sample sheet in Chemotion.

The functionality to add links to the research plan is #666, but only for reactions right now, I can add links to open the samples via clicking on the image / structure name, whichever suits best. 😄

**Comment by dp19982** [comment]
Hi @Alexwelle1, in order to eliminate the (unlikely?) possibility below, could you please provide steps in reproducing the error?

The following images are 2 examples of opening document.html, which contains a single decoupled sample.

Sample:
![polymer](https://user-images.githubusercontent.com/67055123/169788515-9462d81a-ddde-406a-80a8-6d5531efb27a.png)

Zipped research plan:
![zipped_research_plan](https://user-images.githubusercontent.com/67055123/169787893-1d883f6b-ca13-40a4-8eec-ae09e2129620.png)

Unzipped / extracted research plan:
![unzipped_research_plan](https://user-images.githubusercontent.com/67055123/169787892-d06f7cb3-adde-4f3e-b448-70a766096167.png)

Thanks,
Dev

**Comment by Alexwelle1** [comment]
Hi Devang,

give me a bit of time and’ll go deeper into this issue. Do you think a MSTeams screen sharin could help?

Alex

 

_____________________________________________________

 

Dr. Alexander Welle

 

Karlsruher Institut für Technologie (KIT)

 

Institut für Funktionelle Grenzflächen (IFG), Abt. Chemie oxydischer und organischer Grenzflächen,

Geb. 330, R. 351

 

Hermann-von-Helmholtz-Platz 1

76344 Eggenstein-Leopoldshafen

 <http://www.ifg.kit.edu/> http://www.ifg.kit.edu/ 

 

Telefon: +49 (0)721/608-26559

Fax: +49 (0)721/608-23478

Email:  ***@***.***> ***@***.***

 

Sitz der Körperschaft:

Kaiserstr. 12, 76131 Karlsruhe

 

KIT- Die Forschungsuniversität in der Helmholtz-Gemeinschaft

**Comment by dp19982** [comment]
Hi Alex,

If possible, a video would be better, if that's doable?

Thanks,
Devang

**Comment by Alexwelle1** [comment]
https://user-images.githubusercontent.com/92295214/169800621-6245bd61-e834-4581-a110-309befd88c94.mp4

**Comment by dp19982** [comment]
Lovely, thank you very much. I'll get to work on this ASAP.

What would the ideal solution be for you, @Alexwelle1, given that the issue seems to be caused by no image being rendered?

**Comment by Alexwelle1** [comment]
Dear Devang,
my answer to the "ideal solution" question goes along the lines of what exactly is called a sample. Even assuming we're not dealing with decoupled samples but molecules, depending on which synthesis was done or which supplier used, there might be subtle differences in the properties of that very sample. So it's fine showing the molecular structure, but if you want to be specific as to which specimen is actually described in this protocol one has to refer to the actual sample name. Thereby, the experimentator can define exactly what he or she's talking about. So, ideal would be the structure of the molecule if available but in any case I'd like to see the sample name created by Chemotion. See second 5 in the video: Chemotion created rz6502-158. This is an absolutely unique description of what I'd like to refer to. If one additionally has a link opening this sample description this would be great.
Greetings,
Alex

**Comment by dp19982** [comment]
Dear Alex,

Thank you for your answer, it seems we are on the same wavelength regarding an ideal solution, I'll work on that now!

Thanks,
Devang

**Comment by dp19982** [comment]
Hi @Alexwelle1, I hope this video provides a good solution?

https://user-images.githubusercontent.com/67055123/169821113-00f5c310-ef35-414c-bd63-7dcaeff85da8.mp4

**Comment by Alexwelle1** [comment]
That's fantastic!
Many thanks for solving this issue.
Greetings,
Alex
