### ISSUE TITLE
Enhancement of screen

### ISSUE THREAD

**Issue by TasnimMehzabin** [ComPlat/chemotion_ELN#751]
- [ ] I am an ELNer
- [x] I am a developer
- [ ] I am a system/ELN admin

# Description
1. Screen is missing currently the option to see the collections where the screen belongs to. 
It would be great to have this.

# Image
![image](https://user-images.githubusercontent.com/8912580/173586702-f134cfec-6731-44bb-83f7-ddebb87e11bd.png)

**Comment by TasnimMehzabin** [comment]
The option to see the collections where the screen belongs to has been added.

![image](https://user-images.githubusercontent.com/8912580/173587078-bdaf28d6-4812-4095-a667-cc5eb6349729.png)

**Comment by ptrxyz** [comment]
Could you please link the PR so that the code can be reviewed?
