### ISSUE TITLE
reaction description editing to not trigger svg update

### ISSUE THREAD

**Issue by PiTrem** [ComPlat/chemotion_ELN#759]
currently editing the reaction description triggers the reaction svg composer (round trip to server) and can impact the user exp

- **as a** ELNer
- **when** I edit the reaction description
- **I want** the reaction image to not update
- **so that**  inputing text is kept fluid

suggested req: 
- [ ] input in description field does not trigger reaction svg update
- [ ] check debounce for text input ?
- [ ]  check for other fields that might also trigger unecessary svg update

**Comment by harivyasi** [comment]
Okay, I reopened it by mistake. ;|

**Comment by harivyasi** [comment]
Replaced with a new issue https://github.com/ComPlat/chemotion_ELN/issues/1052
