### ISSUE TITLE
Refactor upload image in Research Plan

### ISSUE THREAD

**Issue by Allenskywalker92** [ComPlat/chemotion_ELN#794]
# Description
Refactor the image handling in the "Research plan" tab of research plans.
 - [x] Replace the upload process
 - [x] Replace the "show process"
 - [x] Handling the "image attachments" in the tab "Attachments"
 - [x] Refactor the export process of research plan
 - [x] Refactor the import process of research plan
 - [- ]  Refactor the report process of research plan - DONT EFFECT THIS PART
 - [x]  Refactor the delete image process of research plan

**Comment by FabianMauz** [comment]
Was done in https://github.com/ComPlat/chemotion_ELN/pull/997
