### ISSUE TITLE
Collection management - tab assignment

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#795]
- [ x] I am an ELNer
- [ ] I am a developer
- [ ] I am a system/ELN admin

# Description
Please provide a description of:
1. what enhancement you suggest
Enhancement for the planned assignment of tabs to collections: it would be very helpful if we could offer this feature in a way that also allows the assignment of subcollections to a certain tab-setting: 
(1) tab selection/visibility per default as given by the main-collection (if possible)
(2) option to change the default setting as given by (1) 

3. why you think it is needed (You might provide a use case here): 
structuring of collections will be made on the level of subcollections in many cases. Limiting the tab-management only on the first level will probably not solve the challenge

**Comment by PiTrem** [comment]
resolved with https://github.com/ComPlat/chemotion_ELN/pull/681
