### ISSUE TITLE
clickable reaction links in research plan table

### ISSUE THREAD

**Issue by endevor-music** [ComPlat/chemotion_ELN#823]
- I am a developer

# Description
Within a research plan table, if a column is named Sample, and a short label for a sample is provided as one of the fields in that column, the table will link to the sample automatically (provided by jhmegorei initially)

This issue is for recreating that functionality for reactions.

**Comment by dp19982** [comment]
Video of functionality:
Please note that the URL's pointing to the samples / reactions clicked via the research plan table have also been fixed.

https://user-images.githubusercontent.com/67055123/181247960-f6eb9227-619e-4443-8164-0d6647d4e606.mp4

**Comment by nicolejung** [comment]
nice!

**Comment by endevor-music** [comment]
Closed #825 due to error, reopening as PR #999
