### ISSUE TITLE
Adding methods to the purification drop-down menu in reactions

### ISSUE THREAD

**Issue by BenjaminGolub** [ComPlat/chemotion_ELN#826]
- [x] I am an ELNer
- [ ] I am a developer
- [x] I am a system/ELN admin

# Description
Please add "Dialysis" and "Recrystallization" to the purification methods in the drop-down menu in the "Scheme" tab of reactions. 

Our users use these methods very frequently, and therefore it would help if these are included. "Recrystallization" is more precise than using "Crystallization".

**Comment by dp19982** [comment]
Dialysis and Recrystallisation methods added.

![image](https://user-images.githubusercontent.com/67055123/182113300-2d7c256f-2621-4989-9588-034256676af3.png)
