### ISSUE TITLE
molecule svg is missing

### ISSUE THREAD

**Issue by phuang26** [ComPlat/chemotion_ELN#846]
After upgrading to ELN 1.3.0, some molecules do not create SVGs properly.

Please try to create molecule with SMILE `CCC(C)C(C(=O)O)NC(=O)OCC1C2=CC=CC=C2C3=CC=CC=C13`
refer to [here](https://github.com/ComPlat/chemotion_ELN/issues/836#issuecomment-1199690804)

**Comment by Alexwelle1** [comment]
Anther test piece:
C1=CC(=CC=C1C2=C3C=CC(=C(C4=NC(=C(C5=CC=C([N-]5)C(=C6C=CC2=N6)C7=CC=C(C=C7)C(=O)O)C8=CC=C(C=C8)C(=O)O)C=C4)C9=CC=C(C=C9)C(=O)O)[N-]3)C(=O)O.[Pd+2]

(does work in http://www.cheminfo.org/Chemistry/Cheminformatics/Smiles/index.html )
Alex

**Comment by Alexwelle1** [comment]
The molecular structure is not shown:
![image](https://user-images.githubusercontent.com/92295214/182140029-4a4fd40a-696f-45d5-969c-a394c4d5c780.png)

But is computed. One can see it when clicking the edit button on the ketcher window:
![image](https://user-images.githubusercontent.com/92295214/182140205-b19598ff-58a2-482e-8fe3-f291408060d7.png)
