### ISSUE TITLE
Wellplate - trash button is not a button - cannot remove an item from a well

### ISSUE THREAD

**Issue by endevor-music** [ComPlat/chemotion_ELN#880]
- I am a developer

# Expected Behavior

The red trash button in Well Details should remove the current item in the well.

# Current Behavior

The item in the well is not removed - the trash button does not function as a button!

## Steps to Reproduce

1. Create a wellplate
2. Add an item to a well & save
3. Attempt to remove item, and fail.

## Context

 - OS: Windows
 - Chrome
 - ELN version 1.3.1 (development instance & deployed instance at TU Braunschweig)

## Failure Logs / Screenshots

https://user-images.githubusercontent.com/67055123/184837411-4f0a2ea8-92bd-41a6-8e94-c6b2725753a9.mp4

**Comment by PiTrem** [comment]
https://github.com/ComPlat/chemotion_ELN/pull/1148
