### ISSUE TITLE
Function "show external label" in settings of the list tools is not working correctly

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#884]
- I am an ELNer

# Expected Behavior
deselect "show sample external label on title" should result in change of the title (as it does if one select the option - just the opposite behaviour)

# Current Behavior
the changes are not applied and the checkbox change is not saved (close and reopen shows that the checkbox uncheck failed). Only refresh of the browser solved the issue

Also: please rename the function to: 
 "show sample external label as title and replace sample short label and sample name" 
even better would be: offer three checkboxes with: 
- show sample short label
- show sample name
- show external label

**Comment by PiTrem** [comment]
shipped with v1.4.0
