### ISSUE TITLE
Generic elements: sorting of tabs

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#889]
Generic elements can be enriched with additional tabs (generic segments). Currently, the tabs are added without the option to sort/order them. 
It would be great to have the sorting option for generic elements with generic segments as well

**Comment by StarmanMartin** [comment]
This issue is covered by the issue: [Activate segment-visibility field in generic elements #845](https://github.com/ComPlat/chemotion_ELN/issues/845)
