### ISSUE TITLE
Wellplate - ui issues

### ISSUE THREAD

**Issue by FabianMauz** [ComPlat/chemotion_ELN#895]
- I am a developer

# Current Behavior

- When in wellplate designer, the combolist of possible tags is behind an inputfield.

![image](https://user-images.githubusercontent.com/23172219/187155067-d23e874a-af8c-4ff8-aa20-68d0303c9999.png)

- there is a strange string in the heading : zzz

# Failure Information 

## Context

 - OS: Windows
 - Chrome Browser 
 - ELN version: 1.3.1

**Comment by dp19982** [comment]
The first bullet regarding drop down list is planned for v1.4.0 - https://github.com/ComPlat/chemotion_ELN/issues/797

**Comment by PiTrem** [comment]
resolved with a974b7560 https://github.com/ComPlat/chemotion_ELN/pull/813
