### ISSUE TITLE
Removing entry in generic element not possible

### ISSUE THREAD

**Issue by BenjaminGolub** [ComPlat/chemotion_ELN#897]
- [x] I am an ELNer
- I am a developer
- [x] I am a system/ELN admin

# Expected Behavior
Removing an entry in a generic element should be possible by selecting the entry and then click "remove from current collection", as it is possible for the non-genereic elements.
![grafik](https://user-images.githubusercontent.com/107389350/187161356-25f8690b-dd0e-4c10-90e2-a2b6f3267776.png)

# Current Behavior
After selecting the entry, the button "remove from current collection" is not clickable. 
![grafik](https://user-images.githubusercontent.com/107389350/187161500-bd6635ec-6a39-44eb-b183-55b210ca0eea.png)

If an entry in a non-generic element, as well as the entry in the generic element are selected, the button is clickable and both can be removed. 
![grafik](https://user-images.githubusercontent.com/107389350/187162733-69e7846d-ef7d-4097-ac95-25ffb83eeeda.png)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Make a new generic element (admin)
2. Generate a new entry with this generic element
3. Try to remove the entry by selecting the entry and clicking the button "remove from current collection"

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: windows 10
 - Chrome Browser 
 - [x] Firefox Browser
 - ELN version 1.3.1

**Comment by PiTrem** [comment]
resolved some time ago 😓 but cant find the actual PR or commit
