### ISSUE TITLE
Exporting a reasearch plan to docx sometimes not working

### ISSUE THREAD

**Issue by Alexwelle1** [ComPlat/chemotion_ELN#902]
- I am an ELNer

# Expected Behavior

![image](https://user-images.githubusercontent.com/92295214/188630406-1af086ff-b013-4f93-a193-2e3dec614839.png)
Hitting the export button and selection *.docs should yield a docx

# Current Behavior

In the case shown above it worked. In this case:

![image](https://user-images.githubusercontent.com/92295214/188631022-8ca9db8b-cd08-412b-ac74-2c3ca3495122.png)

with a longer research pan, mainly text field with some copy&pasted images, it looks fine on screen but hitting export does nothing.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: [e.g. iOS]: Windows 10
 - Chrome Browser 
 - ELN version, or branch, or commit: Current version at IFG/KIT

Thanks for taking care, as always feel free to contact me for a online demo.
Cheers,
Alex

**Comment by mehreenmansur** [comment]
[Screencast from 20.11.2022 12:56:42.webm](https://user-images.githubusercontent.com/26220177/202901144-64451928-2dd7-441a-b656-7d09ca5803a0.webm)

**Comment by Alexwelle1** [comment]
G'day,
here at IFg I can reproduce the error.
http://ifgs6.ifg.kit.edu/zip/3f474268-d542-47f5-a311-98b59729b487.zip  is a link to an exported collection having the two research plans shown. One works the other, aw1636, doesn't.
I don't know if you can access this collection.
