### ISSUE TITLE
Error while adding reference per DOI link to reactions

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#903]
# Expected Behavior
Adding doi-link to references will add the reference, example: https://doi.org/10.3762/bjoc.18.117

# Current Behavior
nothing happens and error occurs

What is the current behavior?
error message

**Comment by cllde8** [comment]
Hi @nicolejung ,

We have tried this function on the latest ELN version and were unable to reproduce the issue. Could you please try it again on your instance to see if it works?

This video is for your reference.

[903_Error while adding reference per DOI link to reactions-2022.09.06-18_43_17.webm](https://user-images.githubusercontent.com/42910431/188696445-1a40fc29-3502-4c4f-9951-55a2665723bd.webm)

Best regards,
Claire

**Comment by nicolejung** [comment]
clarified: seemed to be a problem of DOI resolver/network issue. No action needed
