### ISSUE TITLE
Chemdraw JS doesn't work on Google Chrome

### ISSUE THREAD

**Issue by cllde8** [ComPlat/chemotion_ELN#907]
There is a known issue that ChemDraw JS cannot work properly with Google Chrome 104.x (104.0.5112.80 and 104.0.5112.81).

Please update Google Chrome to v105 (currently 105.0.5195.102) if you are using ChemDraw JS of the Structure Editor. 

**How to check/update your Google Chrome**

Please refer to the link [Update Google Chrome](https://support.google.com/chrome/answer/95414?hl=en&co=GENIE.Platform%3DDesktop) or a quick video for your reference.

[check google chrome version-2022.09.08-12_58_23.webm](https://user-images.githubusercontent.com/42910431/189105728-52bace41-f266-461e-8deb-6efa5392d943.webm)

**Comment by TasnimMehzabin** [comment]
Chemdraw JS does not work once again on Google Chrome.

![image](https://user-images.githubusercontent.com/8912580/226328282-9322f66c-ef55-4d09-afc5-c1138469a8f4.png)

Chrome version: 111.0.5563.65

**Comment by cllde8** [comment]
Hi @TasnimMehzabin /all,

The issue occurs after upgrading to Google Chrome version 111.0.5563.x. Before updating Chrome, everything was functioning normally. However, after updating to version 111.0.5563.x, the issue appeared.

I have created an [issue](https://github.com/ComPlat/chemotion_ELN/issues/1265) to track this problem and will be closing this one.
