### ISSUE TITLE
Adding analysis button is missing in some Surmof reactions

### ISSUE THREAD

**Issue by Alexwelle1** [ComPlat/chemotion_ELN#910]
- I am an ELNer

# Expected Behavior

![ice_screenshot_20220909-141119](https://user-images.githubusercontent.com/92295214/189353755-acf29c82-0142-4cf6-a088-95e2de779786.jpeg)

# Current Behavior

Sometimes the button is missing:
![ice_screenshot_20220909-141144](https://user-images.githubusercontent.com/92295214/189353814-5936545b-4eb1-47d5-b210-b5590d3bb348.jpeg)

So far, reported only by one user of the IFG / KIT group.

## Steps to Reproduce
Upon creating a new Surmof reaction the button is missing.
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: [e.g. iOS] Windows 10
 - Chrome Browser 
 - ELN version, or branch, or commit: Standrad IFG setup

## Failure Logs / Screenshots

Include any relevant log snippets or files here.

**Comment by phuang26** [comment]
It was an old bug that created elements without an analysis root. The issue has been fixed since ELN version 1.3+, but elements created without an analysis root will need to be fixed manually.
