### ISSUE TITLE
Please update hereon.chemotion.scc.kit.edu to version 1.4

### ISSUE THREAD

**Issue by martin-held-hereon** [ComPlat/chemotion_ELN#913]
1) Please update my test platform "hereon.chemotion.scc.kit.edu" to version 1.4, so I can use the drag'n'drop for generic elements. 
2) Please add the pages with the details for devices or send the json code for that to me (martin.held@hereon.de)

**Comment by martin-held-hereon** [comment]
Nicole solved Part 2 by e-mailing the json files to me

**Comment by PiTrem** [comment]
AFAIK this has been resolved.

(Also for this type of request  could be tracked faster through the [helpdesk](https://chemotion.net/helpdesk)

:handshake:
