### ISSUE TITLE
Sidebar menu fails

### ISSUE THREAD

**Issue by harivyasi** [ComPlat/chemotion_ELN#926]
- I am a developer
- I am a system/ELN admin

# Expected Behavior

Sidebar menu should be served.

# Current Behavior

The page crashes with an error when the button is clicked -- see screenshot.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install fresh copy of Chemotion from branch v1.4
2. click on the sidebar hamburger menu icon

## Context

 - OS: Ubuntu 20, focal
 - Chrome Browser 
 - ELN version, or branch, or commit - v1.4 0c606b1daf35708a0df514c0276b0ff854c021fc
 - RAILS_ENV=development
 - NODE_ENV=development

## Failure Logs / Screenshots

Include any relevant log snippets or files here.

https://user-images.githubusercontent.com/45761248/191031590-63d3118f-e649-4ce6-8403-69d1f315c270.mp4

**Comment by FabianMauz** [comment]
Can not confirm it


https://user-images.githubusercontent.com/23172219/217859374-dca37e27-3c58-478b-bab6-c0a667ca8c57.webm

**Comment by PiTrem** [comment]
happens when on /home 

feature/btn should not be present when on this page

**Comment by harivyasi** [comment]
@TasnimMehzabin thanks for taking care of it :)
