### ISSUE TITLE
I need the “polymer details” segment

### ISSUE THREAD

**Issue by martin-held-hereon** [ComPlat/chemotion_ELN#929]
Could you send me (martin.held@hereon.de) the code/ json file for the “polymer details” segment?  I can't find it in the code. I attached a screenshot that I received from Nicole in 2021. 

<img width="1280" alt="sample_polymer tab_new_teil1" src="https://user-images.githubusercontent.com/91550882/191259493-df234878-fc72-437e-9957-c958842377a2.png">

**Comment by endevor-music** [comment]
Hi Martin,

The link takes you to the raw json code for the polymer details segment, hope this helps.

https://github.com/ComPlat/Chemotion-Templates/blob/main/Polymer%20Templates/Polymer%20details_V3.json

Kind regards,
Devang

**Comment by martin-held-hereon** [comment]
Perfect! Thanks! Sorry for not being able to find it myself. Now, I nknow where to look :-)
