### ISSUE TITLE
Vessel Element

### ISSUE THREAD

**Issue by dpatelev** [ComPlat/chemotion_ELN#950]
- I am a developer

# Description
Ongoing implementation of a new element to record reaction vessels and other equipments in the ELN.

The purpose of this element is to allow users to create a vessel template (similar to molecules) for their reaction vessels / equipment, and assign a vessel entity (akin to samples) to a reaction. 

The basis of this comes from a generic element implementation, that allows for the user to pick between vessels (various flasks / beakers), reactors (flow reactors, electrochemical cells) and other equipment (TBD), and state the material details and volume.

Back end - database model - https://github.com/ComPlat/chemotion_ELN/pull/1548
API - functional
Front end - functional, needs refining & CSS

**Comment by jhmegorei** [comment]
Can you add a description what reaction vessels are and how you would model them in the context of the ELN?

**Comment by endevor-music** [comment]
> Can you add a description what reaction vessels are and how you would model them in the context of the ELN?

I hope the following information helps,
Devang

**Comment by endevor-music** [comment]
For developers: please see PR #1476 for the initial model and API implementation for this element.

**Comment by cbuggle** [comment]
The  "Back end - database model" part is provided by [#1548] which when merged eventually renders [#1476] obsolete.
