### ISSUE TITLE
Fast-creating a sample from CAS does not store the CAS number in the sample detail form

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#954]
See the following video:

[Peek 2022-10-05 22-38.webm](https://user-images.githubusercontent.com/209056/194159561-27138c34-b451-4a63-aee5-0c2409c2f766.webm)

When creating a sample using the fast-create feature, the CAS number is not added to the details of the sample but has to be selected manually.

I, as a non-chemist, would expect that the CAS number would be auto-associated with the sample since the sample was created from it.

Is this a bug or is this a feature?

**Comment by adambasha0** [comment]
https://user-images.githubusercontent.com/55552142/204142742-143a7164-df66-453f-b9fd-6d92c5aef82d.mp4

**Comment by adambasha0** [comment]
solved and shipped with [issue -955](https://github.com/ComPlat/chemotion_ELN/issues/955)
