### ISSUE TITLE
CAS numbers in sample detail pane behave mega weird

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#955]
When it comes to associating a CAS number with a sample, the drop-down behaves mega weird:

- you have to click to "create the option" which is already confusing.
- Sometimes CAS numbers are stored and presented as an option the next time the sample is loaded, sometimes the options are discarded. The pattern is unclear to me.
- CAS numbers that do not appear to be valid CAS numbers also work. I could type in any random string without proper validation.

I recorded a video to show what I mean:
[Peek 2022-10-05 22-47.webm](https://user-images.githubusercontent.com/209056/194160892-dd231b75-f622-491f-8035-301b870d19ed.webm)

**Comment by adambasha0** [comment]
[

https://user-images.githubusercontent.com/55552142/204144857-780c8caf-917d-43f1-919b-1aefd31ce437.mp4

](url)
