### ISSUE TITLE
Page numbers in pagination footer break

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#956]
Sadly the pagination is a bit messed up:

![image](https://user-images.githubusercontent.com/209056/194393733-77cfbd78-ba90-4b5c-baa0-00ce2aee6542.png)

(Screenshot taken 1920x1080 @100% zoom, v1.4.0)

**Comment by endevor-music** [comment]
Also a problem due to changing the ratio of list and details segments (#723)
