### ISSUE TITLE
Open NMRium wrapper from ELN

### ISSUE THREAD

**Issue by baolanlequang** [ComPlat/chemotion_ELN#964]
- I am a developer

# Description
1. User can view NMR spectra data in NMRium from Chemotion ELN

**Comment by FabianMauz** [comment]
seems to be duplicate of

https://github.com/ComPlat/chemotion_ELN/issues/439

can somebody confirm this?

**Comment by baolanlequang** [comment]
@FabianMauz Yes, it is a duplicate.

**Comment by FabianMauz** [comment]
@baolanlequang  Thank you, i will close the other on to avoid confusion.
