### ISSUE TITLE
Export URL is missing the host address

### ISSUE THREAD

**Issue by martin-held-hereon** [ComPlat/chemotion_ELN#978]
- I am an ELNer
- I am a system/ELN admin

# Expected Behavior
Properly exporting a collection as a zip

# Current Behavior
Currently the export URL is missing the host address:
it shows 
"https:///zip/4df4ds5fdf"
instead of
"https://hereon.chemotion.scc.kit.edu/zip/4df4ds5fdf"

## Context
 - any browser 
 - ELN version: V1.2
 - Hereon chemotion instance on SCC KIT server (hereon.chemotion.scc.kit.edu)

## Screenshots

![Chemotion V1-2 export error](https://user-images.githubusercontent.com/91550882/196467345-c59f396e-747e-4f39-9e4d-06d07a52a01b.png)

**Comment by PiTrem** [comment]
fixed with vs 1.4
