### ISSUE TITLE
Length unit conversion is incorrect

### ISSUE THREAD

**Issue by martin-held-hereon** [ComPlat/chemotion_ELN#979]
- I am an ELNer
- I am a system/ELN admin

# Current & Expected Behavior
Changing the units in the system-defined Length-field does not change the order of magnitude correctly

 Unit | current | Expected
 mm | 200       | 200
 cm  | 20         | 20
 m   | 0.2        | 0.2
 pm | 20000   | 2 E11
 nm | 2000     | 2 E8

## Context

 - OS:  Win 10
 - Chrome Browser 
 - Firefox Browser
 - ELN version V 1.2.
 - Hereon chemotion instance on SCC KIT server (hereon.chemotion.scc.kit.edu)

**Comment by cllde8** [comment]
Dear @martin-held-hereon,

I tried to reproduce the issue with the latest version, but I was unable to replicate the problem. Please feel free to create an issue at https://github.com/LabIMotion/labimotion if the issue persists on your end.

Thank you.

Best regards,
Claire

**Comment by martin-held-hereon** [comment]
The issue resolved itself by taking "nm" and "pm" out of the system-defined "Length" field (and moving it into the system-defined "Subatomic Length" field). Thanks!
