### ISSUE TITLE
Add µm to length & µm² to area

### ISSUE THREAD

**Issue by martin-held-hereon** [ComPlat/chemotion_ELN#980]
- I am an ELNer / system/ELN admin

Maybe after solving issue #979:

# Description
Please add "µm" to the system-defined length, and "µm²" to the system-defined area, ideally with the correct unit conversion :-P

**Comment by cllde8** [comment]
Dear @martin-held-hereon,

We have provided "µm" for subatomic length measurements and "µm²" for surface area measurements. You can find the full list at this [link](https://github.com/LabIMotion/labimotion/wiki/Supported-Units-for-System-Defined-Field).

If you have any further questions or suggestions, please create an issue or start a discussion at our GitHub repository: https://github.com/LabIMotion/labimotion.

Thank you.

Best regards,
Claire

**Comment by martin-held-hereon** [comment]
thanks!
