### ISSUE TITLE
System-defined area units do not convert

### ISSUE THREAD

**Issue by martin-held-hereon** [ComPlat/chemotion_ELN#981]
- I am an ELNer
- I am a system/ELN admin

# Current Behavior

Changing the units in the system-defined area-field does not change the order of magnitude correctly

Unit | current | Expected
mm² | 100     | 100
cm²  | 100     | 1
A²    | 100      | 1 E8

## Context

  -  OS: Win 10
   - Chrome Browser
   - Firefox Browser
   - ELN version V 1.2.
   - Hereon chemotion instance on SCC KIT server (hereon.chemotion.scc.kit.edu)

**Comment by cllde8** [comment]
Dear @martin-held-hereon,

The issue was resolved some time ago.

If you have any further questions or suggestions, please create an issue or start a discussion at https://github.com/LabIMotion/labimotion.

Thank you.

Best regards,
Claire

**Comment by martin-held-hereon** [comment]
thanks!
