### ISSUE TITLE
can not open ChemSpectra in Research Plan

### ISSUE THREAD

**Issue by phuang26** [ComPlat/chemotion_ELN#988]
received a blank page with console error when open ChemSpecta in Research Plan.

Error message:

`react_devtools_backend.js:4026 TypeError: e.datasetContainers is not a function
    at r.getDSList (ViewSpectra.js:123:24)
    at r.renderTitle (ViewSpectra.js:677:23)`

`TypeError: e.datasetContainers is not a function
    at r.getDSList (ViewSpectra.js:123:24)
    at r.renderTitle (ViewSpectra.js:677:23)
    at r.render (ViewSpectra.js:749:18)`

**Comment by baolanlequang** [comment]
@phuang26 Which version of ELN of this bug?

**Comment by phuang26** [comment]
ELN v1.4.0, with react-spectra-editor 0.10.15 (https://github.com/ComPlat/react-spectra-editor/releases/tag/0.10.15)

**Comment by baolanlequang** [comment]
@phuang26 I fixed on this PR https://github.com/ComPlat/chemotion_ELN/pull/989

**Comment by baolanlequang** [comment]
Done at https://github.com/ComPlat/chemotion_ELN/pull/989
